// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<MvtAcessoActiveDirectory> MvtAcessoActiveDirectory { get; set; }

    public virtual DbSet<MvtAcessoAjuda> MvtAcessoAjuda { get; set; }

    public virtual DbSet<MvtAcessoAtualizacaoPeriodo> MvtAcessoAtualizacaoPeriodo { get; set; }

    public virtual DbSet<MvtAcessoCfgAtendentePermissao> MvtAcessoCfgAtendentePermissao { get; set; }

    public virtual DbSet<MvtAcessoEstacao> MvtAcessoEstacao { get; set; }

    public virtual DbSet<MvtAcessoGrupo> MvtAcessoGrupo { get; set; }

    public virtual DbSet<MvtAcessoGrupoMembro> MvtAcessoGrupoMembro { get; set; }

    public virtual DbSet<MvtAcessoLog> MvtAcessoLog { get; set; }

    public virtual DbSet<MvtAcessoMensagem> MvtAcessoMensagem { get; set; }

    public virtual DbSet<MvtAcessoPermissao> MvtAcessoPermissao { get; set; }

    public virtual DbSet<MvtAcessoProcesso> MvtAcessoProcesso { get; set; }

    public virtual DbSet<MvtAcessoUsuario> MvtAcessoUsuario { get; set; }

    public virtual DbSet<MvtAcessoUsuarioCliente> MvtAcessoUsuarioCliente { get; set; }

    public virtual DbSet<MvtAcessoUsuarioConsultaColuna> MvtAcessoUsuarioConsultaColuna { get; set; }

    public virtual DbSet<MvtAcessoUsuarioEmpresa> MvtAcessoUsuarioEmpresa { get; set; }

    public virtual DbSet<MvtAcessoUsuarioErp> MvtAcessoUsuarioErp { get; set; }

    public virtual DbSet<MvtAcessoUsuarioFavorito> MvtAcessoUsuarioFavorito { get; set; }

    public virtual DbSet<MvtAcessoUsuarioFornecedor> MvtAcessoUsuarioFornecedor { get; set; }

    public virtual DbSet<MvtAcessoUsuarioHistoricoAcesso> MvtAcessoUsuarioHistoricoAcesso { get; set; }

    public virtual DbSet<MvtAcessoUsuarioModulo> MvtAcessoUsuarioModulo { get; set; }

    public virtual DbSet<MvtAcessoUsuarioRepresentante> MvtAcessoUsuarioRepresentante { get; set; }

    public virtual DbSet<MvtAcessoUsuarioSupervisor> MvtAcessoUsuarioSupervisor { get; set; }

    public virtual DbSet<MvtAcessoUsuarioTransportadora> MvtAcessoUsuarioTransportadora { get; set; }

    public virtual DbSet<MvtAcessoVersao> MvtAcessoVersao { get; set; }

    public virtual DbSet<MvtAcessoVersaoReferencia> MvtAcessoVersaoReferencia { get; set; }

    public virtual DbSet<MvtCadCentroCusto> MvtCadCentroCusto { get; set; }

    public virtual DbSet<MvtCadCentroCustoTipo> MvtCadCentroCustoTipo { get; set; }

    public virtual DbSet<MvtCadCidade> MvtCadCidade { get; set; }

    public virtual DbSet<MvtCadCliente> MvtCadCliente { get; set; }

    public virtual DbSet<MvtCadCotacaoMoeda> MvtCadCotacaoMoeda { get; set; }

    public virtual DbSet<MvtCadEnvioEmail> MvtCadEnvioEmail { get; set; }

    public virtual DbSet<MvtCadFuncionario> MvtCadFuncionario { get; set; }

    public virtual DbSet<MvtCadGrupoEmpresa> MvtCadGrupoEmpresa { get; set; }

    public virtual DbSet<MvtCadGrupoEmpresaItem> MvtCadGrupoEmpresaItem { get; set; }

    public virtual DbSet<MvtCadMoeda> MvtCadMoeda { get; set; }

    public virtual DbSet<MvtCadNivelHierarq> MvtCadNivelHierarq { get; set; }

    public virtual DbSet<MvtCadNivelHierarqCentroCusto> MvtCadNivelHierarqCentroCusto { get; set; }

    public virtual DbSet<MvtCadOrganograma> MvtCadOrganograma { get; set; }

    public virtual DbSet<MvtCadProduto> MvtCadProduto { get; set; }

    public virtual DbSet<MvtCadenvioEmailDestinatario> MvtCadenvioEmailDestinatario { get; set; }

    public virtual DbSet<MvtCtbCadLancamentoCcustoContaDesp> MvtCtbCadLancamentoCcustoContaDesp { get; set; }

    public virtual DbSet<MvtCtbCadLancamentoCentroCustoConta> MvtCtbCadLancamentoCentroCustoConta { get; set; }

    public virtual DbSet<MvtCtbContaContabil> MvtCtbContaContabil { get; set; }

    public virtual DbSet<MvtCtbFinanciamento> MvtCtbFinanciamento { get; set; }

    public virtual DbSet<MvtCtbFinanciamentoCaptacao> MvtCtbFinanciamentoCaptacao { get; set; }

    public virtual DbSet<MvtCtbFinanciamentoParcela> MvtCtbFinanciamentoParcela { get; set; }

    public virtual DbSet<MvtCtbFinanciamentoParcelaOrcamento> MvtCtbFinanciamentoParcelaOrcamento { get; set; }

    public virtual DbSet<MvtCtbIndicadores> MvtCtbIndicadores { get; set; }

    public virtual DbSet<MvtCtbIndicadoresDados> MvtCtbIndicadoresDados { get; set; }

    public virtual DbSet<MvtCtbOrcamentoCapitais> MvtCtbOrcamentoCapitais { get; set; }

    public virtual DbSet<MvtCtbOrcamentoCapitaisCapa> MvtCtbOrcamentoCapitaisCapa { get; set; }

    public virtual DbSet<MvtCtbOrcamentoCapitaisParcelas> MvtCtbOrcamentoCapitaisParcelas { get; set; }

    public virtual DbSet<MvtCtbPacote> MvtCtbPacote { get; set; }

    public virtual DbSet<MvtCtbPacoteConta> MvtCtbPacoteConta { get; set; }

    public virtual DbSet<MvtCtbPacoteResponsavel> MvtCtbPacoteResponsavel { get; set; }

    public virtual DbSet<MvtCtbPlanoConta> MvtCtbPlanoConta { get; set; }

    public virtual DbSet<MvtCusProduto> MvtCusProduto { get; set; }

    public virtual DbSet<MvtEngProduto> MvtEngProduto { get; set; }

    public virtual DbSet<MvtEstPosicaoMensal> MvtEstPosicaoMensal { get; set; }

    public virtual DbSet<MvtFatRepresentante> MvtFatRepresentante { get; set; }

    public virtual DbSet<MvtGeoCep> MvtGeoCep { get; set; }

    public virtual DbSet<MvtGeoCidade> MvtGeoCidade { get; set; }

    public virtual DbSet<MvtGeoEstrutura> MvtGeoEstrutura { get; set; }

    public virtual DbSet<MvtGeoEstruturaItem> MvtGeoEstruturaItem { get; set; }

    public virtual DbSet<MvtGeoEstruturaTipo> MvtGeoEstruturaTipo { get; set; }

    public virtual DbSet<MvtGeoPerimetro> MvtGeoPerimetro { get; set; }

    public virtual DbSet<MvtGeoPerimetroVinculo> MvtGeoPerimetroVinculo { get; set; }

    public virtual DbSet<MvtGestaoAdministrador> MvtGestaoAdministrador { get; set; }

    public virtual DbSet<MvtGestaoAnaliseCausa> MvtGestaoAnaliseCausa { get; set; }

    public virtual DbSet<MvtGestaoAnaliseCausaEfeito> MvtGestaoAnaliseCausaEfeito { get; set; }

    public virtual DbSet<MvtGestaoAnaliseCausaPlanoAcao> MvtGestaoAnaliseCausaPlanoAcao { get; set; }

    public virtual DbSet<MvtGestaoAnaliseCausaPlanoAcaoAnexo> MvtGestaoAnaliseCausaPlanoAcaoAnexo { get; set; }

    public virtual DbSet<MvtGestaoAnaliseCausaPlanoAcaoHistorico> MvtGestaoAnaliseCausaPlanoAcaoHistorico { get; set; }

    public virtual DbSet<MvtGestaoAnalisePorque> MvtGestaoAnalisePorque { get; set; }

    public virtual DbSet<MvtGestaoCfgCaderno> MvtGestaoCfgCaderno { get; set; }

    public virtual DbSet<MvtGestaoContratoLog> MvtGestaoContratoLog { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialAcao> MvtGestaoDadoGerencialAcao { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialArea> MvtGestaoDadoGerencialArea { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialAtributo> MvtGestaoDadoGerencialAtributo { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialCfgFechamento> MvtGestaoDadoGerencialCfgFechamento { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialConfigOrcDespesa> MvtGestaoDadoGerencialConfigOrcDespesa { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialConfigOrcVenda> MvtGestaoDadoGerencialConfigOrcVenda { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialConfigPdiprazo> MvtGestaoDadoGerencialConfigPdiprazo { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIndicador> MvtGestaoDadoGerencialIndicador { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIndicadorAtributo> MvtGestaoDadoGerencialIndicadorAtributo { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIndicadorCcusto> MvtGestaoDadoGerencialIndicadorCcusto { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIndicadorCtb> MvtGestaoDadoGerencialIndicadorCtb { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIndicadorDependencia> MvtGestaoDadoGerencialIndicadorDependencia { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIndicadorEmpresa> MvtGestaoDadoGerencialIndicadorEmpresa { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIndicadorMatrizResultado> MvtGestaoDadoGerencialIndicadorMatrizResultado { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIndicadorOrcVenda> MvtGestaoDadoGerencialIndicadorOrcVenda { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIndicadorVariacao> MvtGestaoDadoGerencialIndicadorVariacao { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialIniciativa> MvtGestaoDadoGerencialIniciativa { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialMatrizResultado> MvtGestaoDadoGerencialMatrizResultado { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialMatrizResultadoImportacao> MvtGestaoDadoGerencialMatrizResultadoImportacao { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialMeta> MvtGestaoDadoGerencialMeta { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialModelo> MvtGestaoDadoGerencialModelo { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialModeloAtributo> MvtGestaoDadoGerencialModeloAtributo { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialNivel> MvtGestaoDadoGerencialNivel { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialObjetivo> MvtGestaoDadoGerencialObjetivo { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialPermissao> MvtGestaoDadoGerencialPermissao { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialRealizado> MvtGestaoDadoGerencialRealizado { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialRealizadoAnexo> MvtGestaoDadoGerencialRealizadoAnexo { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialUnidadeNegocio> MvtGestaoDadoGerencialUnidadeNegocio { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialVisao> MvtGestaoDadoGerencialVisao { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialVisaoItem> MvtGestaoDadoGerencialVisaoItem { get; set; }

    public virtual DbSet<MvtGestaoDadoGerencialVisaoUsuario> MvtGestaoDadoGerencialVisaoUsuario { get; set; }

    public virtual DbSet<MvtGestaoDreContasNatureza> MvtGestaoDreContasNatureza { get; set; }

    public virtual DbSet<MvtGestaoDreModeloAjusteContabil> MvtGestaoDreModeloAjusteContabil { get; set; }

    public virtual DbSet<MvtGestaoDrecfgLiberacaoAbas> MvtGestaoDrecfgLiberacaoAbas { get; set; }

    public virtual DbSet<MvtGestaoDrecfgLiberacaoModelo> MvtGestaoDrecfgLiberacaoModelo { get; set; }

    public virtual DbSet<MvtGestaoDrecfgProjecaoConta> MvtGestaoDrecfgProjecaoConta { get; set; }

    public virtual DbSet<MvtGestaoDreconsultaSalva> MvtGestaoDreconsultaSalva { get; set; }

    public virtual DbSet<MvtGestaoDreconsultaSalvaCenario> MvtGestaoDreconsultaSalvaCenario { get; set; }

    public virtual DbSet<MvtGestaoDreconsultaSalvaControle> MvtGestaoDreconsultaSalvaControle { get; set; }

    public virtual DbSet<MvtGestaoDrecontas> MvtGestaoDrecontas { get; set; }

    public virtual DbSet<MvtGestaoDrecontasContasContabeis> MvtGestaoDrecontasContasContabeis { get; set; }

    public virtual DbSet<MvtGestaoDrecontasDivisoes> MvtGestaoDrecontasDivisoes { get; set; }

    public virtual DbSet<MvtGestaoDrecontasEmpresaCalculada> MvtGestaoDrecontasEmpresaCalculada { get; set; }

    public virtual DbSet<MvtGestaoDrecontasFormulas> MvtGestaoDrecontasFormulas { get; set; }

    public virtual DbSet<MvtGestaoDredados> MvtGestaoDredados { get; set; }

    public virtual DbSet<MvtGestaoDredadosBi> MvtGestaoDredadosBi { get; set; }

    public virtual DbSet<MvtGestaoDredadosContaContabil> MvtGestaoDredadosContaContabil { get; set; }

    public virtual DbSet<MvtGestaoDredadosContaContabilBi> MvtGestaoDredadosContaContabilBi { get; set; }

    public virtual DbSet<MvtGestaoDredadosDetalha> MvtGestaoDredadosDetalha { get; set; }

    public virtual DbSet<MvtGestaoDreimpressao> MvtGestaoDreimpressao { get; set; }

    public virtual DbSet<MvtGestaoDremodelos> MvtGestaoDremodelos { get; set; }

    public virtual DbSet<MvtGestaoDreresultadoManual> MvtGestaoDreresultadoManual { get; set; }

    public virtual DbSet<MvtGestaoDresimulacao> MvtGestaoDresimulacao { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoAnexo> MvtGestaoDresimulacaoAnexo { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoCampoOrcVenda> MvtGestaoDresimulacaoCampoOrcVenda { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoCenario> MvtGestaoDresimulacaoCenario { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoCfgBase> MvtGestaoDresimulacaoCfgBase { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoCfgBaseCapa> MvtGestaoDresimulacaoCfgBaseCapa { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoCfgBaseContaProporcao> MvtGestaoDresimulacaoCfgBaseContaProporcao { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoCfgBaseTipoAjuste> MvtGestaoDresimulacaoCfgBaseTipoAjuste { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoCfgContas> MvtGestaoDresimulacaoCfgContas { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoCfgContasProporcao> MvtGestaoDresimulacaoCfgContasProporcao { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoCfgContasValorAjuste> MvtGestaoDresimulacaoCfgContasValorAjuste { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoDados> MvtGestaoDresimulacaoDados { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoDadosDetalha> MvtGestaoDresimulacaoDadosDetalha { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoOrcCustoMp> MvtGestaoDresimulacaoOrcCustoMp { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoOrcCustoMpvalor> MvtGestaoDresimulacaoOrcCustoMpvalor { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoPeriodos> MvtGestaoDresimulacaoPeriodos { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoPermissao> MvtGestaoDresimulacaoPermissao { get; set; }

    public virtual DbSet<MvtGestaoDresimulacaoSimOrcVenda> MvtGestaoDresimulacaoSimOrcVenda { get; set; }

    public virtual DbSet<MvtGestaoDreverificacaoCtbModelo> MvtGestaoDreverificacaoCtbModelo { get; set; }

    public virtual DbSet<MvtGestaoIndicadorBloqueio> MvtGestaoIndicadorBloqueio { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContrato> MvtGestaoIndicadorContrato { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContratoCctb> MvtGestaoIndicadorContratoCctb { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContratoCfg> MvtGestaoIndicadorContratoCfg { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContratoConfig> MvtGestaoIndicadorContratoConfig { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContratoDespCc> MvtGestaoIndicadorContratoDespCc { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContratoInd> MvtGestaoIndicadorContratoInd { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContratoIndGer> MvtGestaoIndicadorContratoIndGer { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContratoOrcVendas> MvtGestaoIndicadorContratoOrcVendas { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContratoPerm> MvtGestaoIndicadorContratoPerm { get; set; }

    public virtual DbSet<MvtGestaoIndicadorContratoResu> MvtGestaoIndicadorContratoResu { get; set; }

    public virtual DbSet<MvtGestaoIndicadorGenerico> MvtGestaoIndicadorGenerico { get; set; }

    public virtual DbSet<MvtGestaoPainelPermissaoCadastro> MvtGestaoPainelPermissaoCadastro { get; set; }

    public virtual DbSet<MvtGestaoPainelPermissaoCriacao> MvtGestaoPainelPermissaoCriacao { get; set; }

    public virtual DbSet<MvtGestaoPainelVisao> MvtGestaoPainelVisao { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoArea> MvtGestaoPainelVisaoArea { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoAreaColuna> MvtGestaoPainelVisaoAreaColuna { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoAreaLinha> MvtGestaoPainelVisaoAreaLinha { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoObjeto> MvtGestaoPainelVisaoObjeto { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoObjetoFaixa> MvtGestaoPainelVisaoObjetoFaixa { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoObjetoIndicador> MvtGestaoPainelVisaoObjetoIndicador { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoObjetoIndicadorEmpresa> MvtGestaoPainelVisaoObjetoIndicadorEmpresa { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoPermissaoGrupo> MvtGestaoPainelVisaoPermissaoGrupo { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoPermissaoUsuario> MvtGestaoPainelVisaoPermissaoUsuario { get; set; }

    public virtual DbSet<MvtGestaoPainelVisaoSlide> MvtGestaoPainelVisaoSlide { get; set; }

    public virtual DbSet<MvtMenuAgendamento> MvtMenuAgendamento { get; set; }

    public virtual DbSet<MvtMenuAgendamentoErro> MvtMenuAgendamentoErro { get; set; }

    public virtual DbSet<MvtMenuAgendamentoLock> MvtMenuAgendamentoLock { get; set; }

    public virtual DbSet<MvtMenuAgendamentoLog> MvtMenuAgendamentoLog { get; set; }

    public virtual DbSet<MvtMenuAgendamentoPermissao> MvtMenuAgendamentoPermissao { get; set; }

    public virtual DbSet<MvtMenuAjuda> MvtMenuAjuda { get; set; }

    public virtual DbSet<MvtMenuDiasUteis> MvtMenuDiasUteis { get; set; }

    public virtual DbSet<MvtMenuEmpresa> MvtMenuEmpresa { get; set; }

    public virtual DbSet<MvtMenuFeriados> MvtMenuFeriados { get; set; }

    public virtual DbSet<MvtMenuItem> MvtMenuItem { get; set; }

    public virtual DbSet<MvtMenuItemReferencia> MvtMenuItemReferencia { get; set; }

    public virtual DbSet<MvtMenuLock> MvtMenuLock { get; set; }

    public virtual DbSet<MvtMenuModulo> MvtMenuModulo { get; set; }

    public virtual DbSet<MvtMenuPendencia> MvtMenuPendencia { get; set; }

    public virtual DbSet<MvtMenuProcesso> MvtMenuProcesso { get; set; }

    public virtual DbSet<MvtMenuSistema> MvtMenuSistema { get; set; }

    public virtual DbSet<MvtOrcamentoBalancoPartida> MvtOrcamentoBalancoPartida { get; set; }

    public virtual DbSet<MvtOrcamentoBalancoPartidaCfgBaixa> MvtOrcamentoBalancoPartidaCfgBaixa { get; set; }

    public virtual DbSet<MvtOrcamentoBloqueioContaContabil> MvtOrcamentoBloqueioContaContabil { get; set; }

    public virtual DbSet<MvtOrcamentoCfgCtbGeral> MvtOrcamentoCfgCtbGeral { get; set; }

    public virtual DbSet<MvtOrcamentoCfgCtbGeralAdicaoExclusao> MvtOrcamentoCfgCtbGeralAdicaoExclusao { get; set; }

    public virtual DbSet<MvtOrcamentoCfgCtbGeralBaseLucroContas> MvtOrcamentoCfgCtbGeralBaseLucroContas { get; set; }

    public virtual DbSet<MvtOrcamentoCfgCtbGeralEquivalencia> MvtOrcamentoCfgCtbGeralEquivalencia { get; set; }

    public virtual DbSet<MvtOrcamentoCfgCtbGeralFilial> MvtOrcamentoCfgCtbGeralFilial { get; set; }

    public virtual DbSet<MvtOrcamentoConfigConta> MvtOrcamentoConfigConta { get; set; }

    public virtual DbSet<MvtOrcamentoConfigContaContas> MvtOrcamentoConfigContaContas { get; set; }

    public virtual DbSet<MvtOrcamentoConfigContaNatureza> MvtOrcamentoConfigContaNatureza { get; set; }

    public virtual DbSet<MvtOrcamentoConfigContaPm> MvtOrcamentoConfigContaPm { get; set; }

    public virtual DbSet<MvtOrcamentoConfigContaSalario> MvtOrcamentoConfigContaSalario { get; set; }

    public virtual DbSet<MvtOrcamentoConfigContaValor> MvtOrcamentoConfigContaValor { get; set; }

    public virtual DbSet<MvtOrcamentoConfigJustificativaDespesa> MvtOrcamentoConfigJustificativaDespesa { get; set; }

    public virtual DbSet<MvtOrcamentoConfigJustificativaPrazo> MvtOrcamentoConfigJustificativaPrazo { get; set; }

    public virtual DbSet<MvtOrcamentoConfigOrcDespesa> MvtOrcamentoConfigOrcDespesa { get; set; }

    public virtual DbSet<MvtOrcamentoConfigVenda> MvtOrcamentoConfigVenda { get; set; }

    public virtual DbSet<MvtOrcamentoContaControlada> MvtOrcamentoContaControlada { get; set; }

    public virtual DbSet<MvtOrcamentoContaControladaCcexcecao> MvtOrcamentoContaControladaCcexcecao { get; set; }

    public virtual DbSet<MvtOrcamentoCotacaoMoeda> MvtOrcamentoCotacaoMoeda { get; set; }

    public virtual DbSet<MvtOrcamentoCustoProduto> MvtOrcamentoCustoProduto { get; set; }

    public virtual DbSet<MvtOrcamentoGestorOrcamento> MvtOrcamentoGestorOrcamento { get; set; }

    public virtual DbSet<MvtOrcamentoGrupoContabilizacao> MvtOrcamentoGrupoContabilizacao { get; set; }

    public virtual DbSet<MvtOrcamentoGrupoContabilizacaoItem> MvtOrcamentoGrupoContabilizacaoItem { get; set; }

    public virtual DbSet<MvtOrcamentoGrupoContabilizacaoItemNatureza> MvtOrcamentoGrupoContabilizacaoItemNatureza { get; set; }

    public virtual DbSet<MvtOrcamentoGrupoContabilizacaoItemPercMes> MvtOrcamentoGrupoContabilizacaoItemPercMes { get; set; }

    public virtual DbSet<MvtOrcamentoGrupoContabilizacaoItemPm> MvtOrcamentoGrupoContabilizacaoItemPm { get; set; }

    public virtual DbSet<MvtOrcamentoLiberacaoCentroCusto> MvtOrcamentoLiberacaoCentroCusto { get; set; }

    public virtual DbSet<MvtOrcamentoMatDespesaDireta> MvtOrcamentoMatDespesaDireta { get; set; }

    public virtual DbSet<MvtOrcamentoMatrizDespesaDireta> MvtOrcamentoMatrizDespesaDireta { get; set; }

    public virtual DbSet<MvtOrcamentoMovimentoPartida> MvtOrcamentoMovimentoPartida { get; set; }

    public virtual DbSet<MvtOrcamentoNaturezaFinanceira> MvtOrcamentoNaturezaFinanceira { get; set; }

    public virtual DbSet<MvtOrcamentoOrcamento> MvtOrcamentoOrcamento { get; set; }

    public virtual DbSet<MvtOrcamentoOrcamentoDespesa> MvtOrcamentoOrcamentoDespesa { get; set; }

    public virtual DbSet<MvtOrcamentoOrcamentoDespesaDetalha> MvtOrcamentoOrcamentoDespesaDetalha { get; set; }

    public virtual DbSet<MvtOrcamentoOrcamentoDespesaJustifica> MvtOrcamentoOrcamentoDespesaJustifica { get; set; }

    public virtual DbSet<MvtOrcamentoOrcamentoDetalhe> MvtOrcamentoOrcamentoDetalhe { get; set; }

    public virtual DbSet<MvtOrcamentoOrcamentoLiberacao> MvtOrcamentoOrcamentoLiberacao { get; set; }

    public virtual DbSet<MvtOrcamentoOrcamentoLiberacaoOrcEspecifico> MvtOrcamentoOrcamentoLiberacaoOrcEspecifico { get; set; }

    public virtual DbSet<MvtOrcamentoOrcamentoManual> MvtOrcamentoOrcamentoManual { get; set; }

    public virtual DbSet<MvtOrcamentoOrcamentoPessoas> MvtOrcamentoOrcamentoPessoas { get; set; }

    public virtual DbSet<MvtOrcamentoRevisaoDespesa> MvtOrcamentoRevisaoDespesa { get; set; }

    public virtual DbSet<MvtOrcamentoSimulacaoOrcVenda> MvtOrcamentoSimulacaoOrcVenda { get; set; }

    public virtual DbSet<MvtOrcamentoSimulacaoOrcVendaCampo> MvtOrcamentoSimulacaoOrcVendaCampo { get; set; }

    public virtual DbSet<MvtOrcamentoSimulacaoOrcVendaItemCampo> MvtOrcamentoSimulacaoOrcVendaItemCampo { get; set; }

    public virtual DbSet<MvtOrcamentoSimulacaoOrcVendaItemValor> MvtOrcamentoSimulacaoOrcVendaItemValor { get; set; }

    public virtual DbSet<MvtOrcamentoTipoInvestimento> MvtOrcamentoTipoInvestimento { get; set; }

    public virtual DbSet<MvtOrcamentoVenda> MvtOrcamentoVenda { get; set; }

    public virtual DbSet<MvtOrcamentoVendaCfgConversao> MvtOrcamentoVendaCfgConversao { get; set; }

    public virtual DbSet<MvtOrcamentoVendaCfgConversaoItem> MvtOrcamentoVendaCfgConversaoItem { get; set; }

    public virtual DbSet<MvtOrcamentoVendaCfgInclusao> MvtOrcamentoVendaCfgInclusao { get; set; }

    public virtual DbSet<MvtOrcamentoVendaCfgInclusaoVersao> MvtOrcamentoVendaCfgInclusaoVersao { get; set; }

    public virtual DbSet<MvtOrcamentoVendaHistAlteracao> MvtOrcamentoVendaHistAlteracao { get; set; }

    public virtual DbSet<MvtOrcamentoVendaTabPreco> MvtOrcamentoVendaTabPreco { get; set; }

    public virtual DbSet<MvtOrcamentoVendaTabPrecoItem> MvtOrcamentoVendaTabPrecoItem { get; set; }

    public virtual DbSet<MvtOrcamentoVendaTabPrecoMes> MvtOrcamentoVendaTabPrecoMes { get; set; }

    public virtual DbSet<MvtOrcamentoVendaVersao> MvtOrcamentoVendaVersao { get; set; }

    public virtual DbSet<MvtOrcamentoVendaVersaoTeste> MvtOrcamentoVendaVersaoTeste { get; set; }

    public virtual DbSet<MvtOrcamentoVersaoOrcVenda> MvtOrcamentoVersaoOrcVenda { get; set; }

    public virtual DbSet<MvtRhOrcamentoSalarial> MvtRhOrcamentoSalarial { get; set; }

    public virtual DbSet<MvtRhSitMensalFuncion> MvtRhSitMensalFuncion { get; set; }

    public virtual DbSet<MvtRhbtCargos> MvtRhbtCargos { get; set; }

    public virtual DbSet<MvtStatsConsulta> MvtStatsConsulta { get; set; }

    public virtual DbSet<MvtStatsConsultaUsuario> MvtStatsConsultaUsuario { get; set; }

    public virtual DbSet<MvtStatsDashFiltro> MvtStatsDashFiltro { get; set; }

    public virtual DbSet<MvtStatsDashFiltroTipo> MvtStatsDashFiltroTipo { get; set; }

    public virtual DbSet<MvtStatsDashGeraEstatistica> MvtStatsDashGeraEstatistica { get; set; }

    public virtual DbSet<MvtStatsDashObjeto> MvtStatsDashObjeto { get; set; }

    public virtual DbSet<MvtStatsDashObjetoEstatistica> MvtStatsDashObjetoEstatistica { get; set; }

    public virtual DbSet<MvtStatsDashObjetoFiltro> MvtStatsDashObjetoFiltro { get; set; }

    public virtual DbSet<MvtStatsDashObjetoFiltroOrigem> MvtStatsDashObjetoFiltroOrigem { get; set; }

    public virtual DbSet<MvtStatsDashObjetoItem> MvtStatsDashObjetoItem { get; set; }

    public virtual DbSet<MvtStatsDashObjetoItemFaixa> MvtStatsDashObjetoItemFaixa { get; set; }

    public virtual DbSet<MvtStatsDashObjetoItemOrigem> MvtStatsDashObjetoItemOrigem { get; set; }

    public virtual DbSet<MvtStatsDashObjetoNivel> MvtStatsDashObjetoNivel { get; set; }

    public virtual DbSet<MvtStatsDashPermissaoCriacao> MvtStatsDashPermissaoCriacao { get; set; }

    public virtual DbSet<MvtStatsDashPermissaoGrupo> MvtStatsDashPermissaoGrupo { get; set; }

    public virtual DbSet<MvtStatsDashPermissaoUsuario> MvtStatsDashPermissaoUsuario { get; set; }

    public virtual DbSet<MvtStatsDashRecipiente> MvtStatsDashRecipiente { get; set; }

    public virtual DbSet<MvtStatsDashRecipientePosicao> MvtStatsDashRecipientePosicao { get; set; }

    public virtual DbSet<MvtStatsDashVisao> MvtStatsDashVisao { get; set; }

    public virtual DbSet<MvtStatsDashVisaoFiltro> MvtStatsDashVisaoFiltro { get; set; }

    public virtual DbSet<MvtStatsPermissaoDadosCfg> MvtStatsPermissaoDadosCfg { get; set; }

    public virtual DbSet<MvtStatsPermissaoImpUsuario> MvtStatsPermissaoImpUsuario { get; set; }

    public virtual DbSet<MvtTempPermissaoCentroCusto> MvtTempPermissaoCentroCusto { get; set; }

    public virtual DbSet<MvtVendasCadastroPlanoMeta> MvtVendasCadastroPlanoMeta { get; set; }

    public virtual DbSet<MvtVendasCfgAcessoUsuario> MvtVendasCfgAcessoUsuario { get; set; }

    public virtual DbSet<MvtVendasCfgEmailDinamico> MvtVendasCfgEmailDinamico { get; set; }

    public virtual DbSet<MvtVendasCfgEmailDinamicoEmp> MvtVendasCfgEmailDinamicoEmp { get; set; }

    public virtual DbSet<MvtVendasCfgEquipePermissao> MvtVendasCfgEquipePermissao { get; set; }

    public virtual DbSet<MvtVendasCfgFiltroAdicional> MvtVendasCfgFiltroAdicional { get; set; }

    public virtual DbSet<MvtVendasCfgUsuarioExterno> MvtVendasCfgUsuarioExterno { get; set; }

    public virtual DbSet<MvtVendasEstatisticaCadastro> MvtVendasEstatisticaCadastro { get; set; }

    public virtual DbSet<MvtVendasEstatisticaConsultaSalvaApp> MvtVendasEstatisticaConsultaSalvaApp { get; set; }

    public virtual DbSet<MvtVendasEstatisticaConsultaSalvaPermissaoApp> MvtVendasEstatisticaConsultaSalvaPermissaoApp { get; set; }

    public virtual DbSet<MvtVendasEstatisticaModulosApp> MvtVendasEstatisticaModulosApp { get; set; }

    public virtual DbSet<MvtVendasEstatisticaPermissaoApp> MvtVendasEstatisticaPermissaoApp { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsulta> MvtVendasEstruturaConsulta { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaColuna> MvtVendasEstruturaConsultaColuna { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaColunaOpcao> MvtVendasEstruturaConsultaColunaOpcao { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaColunaOpcaoTipo> MvtVendasEstruturaConsultaColunaOpcaoTipo { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaMes> MvtVendasEstruturaConsultaMes { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaSalva> MvtVendasEstruturaConsultaSalva { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaSalvaCapa> MvtVendasEstruturaConsultaSalvaCapa { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaTipoAgrupamento> MvtVendasEstruturaConsultaTipoAgrupamento { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaValor> MvtVendasEstruturaConsultaValor { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaValorOpcao> MvtVendasEstruturaConsultaValorOpcao { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaValorOpcaoTipo> MvtVendasEstruturaConsultaValorOpcaoTipo { get; set; }

    public virtual DbSet<MvtVendasEstruturaConsultaValorOpcaoVinculo> MvtVendasEstruturaConsultaValorOpcaoVinculo { get; set; }

    public virtual DbSet<MvtVendasEstruturaCorPercent> MvtVendasEstruturaCorPercent { get; set; }

    public virtual DbSet<MvtVendasEstruturaFaturamento> MvtVendasEstruturaFaturamento { get; set; }

    public virtual DbSet<MvtVendasEstruturaImpLogEmail> MvtVendasEstruturaImpLogEmail { get; set; }

    public virtual DbSet<MvtVendasEstruturaImportacaoCfg> MvtVendasEstruturaImportacaoCfg { get; set; }

    public virtual DbSet<MvtVendasEstruturaImportacaoCfgCampo> MvtVendasEstruturaImportacaoCfgCampo { get; set; }

    public virtual DbSet<MvtVendasEstruturaMetaCliente> MvtVendasEstruturaMetaCliente { get; set; }

    public virtual DbSet<MvtVendasEstruturaPermissaoColunaExibicao> MvtVendasEstruturaPermissaoColunaExibicao { get; set; }

    public virtual DbSet<MvtVendasEstruturaPermissaoDados> MvtVendasEstruturaPermissaoDados { get; set; }

    public virtual DbSet<MvtVendasEstruturaPermissaoGrupoValor> MvtVendasEstruturaPermissaoGrupoValor { get; set; }

    public virtual DbSet<MvtVendasEstruturaPermissaoUsuarioDados> MvtVendasEstruturaPermissaoUsuarioDados { get; set; }

    public virtual DbSet<MvtVendasEstruturaPermissaoUsuarioEstatistica> MvtVendasEstruturaPermissaoUsuarioEstatistica { get; set; }

    public virtual DbSet<MvtVendasEstruturaPermissaoUsuarioEstatisticaNova> MvtVendasEstruturaPermissaoUsuarioEstatisticaNova { get; set; }

    public virtual DbSet<MvtVendasEstruturaPermissaoUsuarioValor> MvtVendasEstruturaPermissaoUsuarioValor { get; set; }

    public virtual DbSet<MvtVendasHistoricoMensal> MvtVendasHistoricoMensal { get; set; }

    public virtual DbSet<MvtVendasLockAtualizacaoEstatistica> MvtVendasLockAtualizacaoEstatistica { get; set; }

    public virtual DbSet<MvtVendasTipoEstatistica> MvtVendasTipoEstatistica { get; set; }

    public virtual DbSet<MvtVendasTipoEstatisticaAgrupamento> MvtVendasTipoEstatisticaAgrupamento { get; set; }

    public virtual DbSet<MvtVendasTipoEstatisticaAgrupamentoCampo> MvtVendasTipoEstatisticaAgrupamentoCampo { get; set; }

    public virtual DbSet<MvtVendasTipoEstatisticaAgrupamentoSimultaneo> MvtVendasTipoEstatisticaAgrupamentoSimultaneo { get; set; }

    public virtual DbSet<MvtVendasTipoEstatisticaCfop> MvtVendasTipoEstatisticaCfop { get; set; }

    public virtual DbSet<MvtVendasTipoEstatisticaImportacao> MvtVendasTipoEstatisticaImportacao { get; set; }

    public virtual DbSet<MvtVendasTipoEstatisticaImportacaoDias> MvtVendasTipoEstatisticaImportacaoDias { get; set; }

    public virtual DbSet<MvtVendasTipoEstatisticaImportacaoEmpresas> MvtVendasTipoEstatisticaImportacaoEmpresas { get; set; }

    public virtual DbSet<MvtVendasTipoEstatisticaLogImportacao> MvtVendasTipoEstatisticaLogImportacao { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-N9LAKIF\\SQLEXPRESS;Initial Catalog=Movtech;Trust Server Certificate=true;User ID=sa;Password=123");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.Entity<MvtAcessoGrupo>(entity =>
        {
            entity.Property(e => e.CodGrupo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtCadCentroCustoTipo>(entity =>
        {
            entity.HasKey(e => e.CodTipoCc).HasName("PK_MVTCADCENTROCUSTOTIPO");

            entity.Property(e => e.CodTipoCc).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtCadCidade>(entity =>
        {
            entity.HasKey(e => e.CodCidade).HasName("PK_MvtCadCidade_1");
        });

        modelBuilder.Entity<MvtCadEnvioEmail>(entity =>
        {
            entity.HasKey(e => e.Identificador).HasName("PK__MvtCadEn__C83612B1286302EC");
        });

        modelBuilder.Entity<MvtCadGrupoEmpresa>(entity =>
        {
            entity.Property(e => e.CodGrupo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtCadMoeda>(entity =>
        {
            entity.Property(e => e.CodMoeda).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtCadNivelHierarq>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.CodNivel }).HasName("PK_MVTCADNIVELHIERARQ");
        });

        modelBuilder.Entity<MvtCadNivelHierarqCentroCusto>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.CodNivel, e.CodCentroCusto }).HasName("PK_MVTCADNIVELHIERARQCENTROCUSTO");
        });

        modelBuilder.Entity<MvtCadOrganograma>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.Ano, e.CodNivelAgrupador, e.CodNivel }).HasName("PK_MVTCADORGANOGRAMA");
        });

        modelBuilder.Entity<MvtCadProduto>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.CodProduto }).HasName("PK__MvtCadPr__C6CDB0445614BF03");
        });

        modelBuilder.Entity<MvtCadenvioEmailDestinatario>(entity =>
        {
            entity.HasKey(e => new { e.Identificador, e.Email, e.Tipo }).HasName("PK__MvtCaden__CB670DF12C3393D0");
        });

        modelBuilder.Entity<MvtCtbCadLancamentoCcustoContaDesp>(entity =>
        {
            entity.Property(e => e.NomeCentroCusto).HasComputedColumnSql("([dbo].[getNomeCentroCusto]([codEmpresa],[codCentroCusto]))", false);
            entity.Property(e => e.NomeContaContabil).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaContabil]))", false);
            entity.Property(e => e.TipoConta).HasComputedColumnSql("([dbo].[getTipoConta]([codEmpresa],[codContaContabil]))", false);
        });

        modelBuilder.Entity<MvtCtbCadLancamentoCentroCustoConta>(entity =>
        {
            entity.Property(e => e.NomeCentroCusto).HasComputedColumnSql("([dbo].[getNomeCentroCusto]([codEmpresa],[codCentroCusto]))", false);
            entity.Property(e => e.NomeContaContabil).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaContabil]))", false);
            entity.Property(e => e.TipoConta).HasComputedColumnSql("([dbo].[getTipoConta]([codEmpresa],[codContaContabil]))", false);
        });

        modelBuilder.Entity<MvtCtbIndicadores>(entity =>
        {
            entity.Property(e => e.CodIndicador).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtCtbOrcamentoCapitaisParcelas>(entity =>
        {
            entity.Property(e => e.Antecipada).HasDefaultValueSql("((0))");
        });

        modelBuilder.Entity<MvtCtbPacote>(entity =>
        {
            entity.Property(e => e.CodPacote).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtEngProduto>(entity =>
        {
            entity.HasKey(e => new { e.CodProduto, e.CodInsumo, e.DataInicio, e.DataTermino, e.CodSequencia, e.CodOperacao }).HasName("PK_MvtEngProduto_1");
        });

        modelBuilder.Entity<MvtGeoCidade>(entity =>
        {
            entity.Property(e => e.CodCidade).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtGestaoAnaliseCausaPlanoAcao>(entity =>
        {
            entity.Property(e => e.StatusPrazo).HasComputedColumnSql("(case [situacao] when 'Cancelado' then 'Cancelado' when 'Encerrado' then [dbo].[getStatusPrazo]([dataPrazo],[dataBaixa]) else [dbo].[getStatusPrazo]([dataPrazo],getdate()) end)", false);
        });

        modelBuilder.Entity<MvtGestaoAnalisePorque>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.Data, e.Identificador, e.Sequencia }).HasName("PK_MvtGestaoAnaliseCausaPorque");
        });

        modelBuilder.Entity<MvtGestaoDadoGerencialCfgFechamento>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.CodModelo, e.Mes }).HasName("Pk_MvtGestaoDadoGerencialCfgFechamento");
        });

        modelBuilder.Entity<MvtGestaoDadoGerencialConfigPdiprazo>(entity =>
        {
            entity.HasKey(e => new { e.CodModelo, e.Ano, e.Sequencia }).HasName("PK_MvtGestaoDadoGerencialConfigPDIPrazo_1");

            entity.Property(e => e.CodModelo).IsFixedLength();
        });

        modelBuilder.Entity<MvtGestaoDadoGerencialVisao>(entity =>
        {
            entity.Property(e => e.CodVisao).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtGestaoDreContasNatureza>(entity =>
        {
            entity.HasKey(e => new { e.CodModelo, e.CodConta, e.CodNatureza }).HasName("PK_MvtGestaoDreContasNatureza_1");
        });

        modelBuilder.Entity<MvtGestaoDrecfgProjecaoConta>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.CodModelo, e.CodConta, e.Data, e.NumeroOrcamento }).HasName("PK__MvtGesta__19BDD58B5629CD9C");
        });

        modelBuilder.Entity<MvtGestaoDreconsultaSalva>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtGestaoDrecontas>(entity =>
        {
            entity.HasKey(e => new { e.CodModelo, e.CodConta }).HasName("PK_MGDCONTAS");

            entity.Property(e => e.Permissao).HasDefaultValueSql("('Todos')");
        });

        modelBuilder.Entity<MvtGestaoDrecontasFormulas>(entity =>
        {
            entity.HasKey(e => new { e.CodModelo, e.CodConta, e.Sequencia }).HasName("PK_MGDCONTASFORMULAS");
        });

        modelBuilder.Entity<MvtGestaoDredados>(entity =>
        {
            entity.Property(e => e.DataProjecao).HasDefaultValueSql("('1900-01-01')");
        });

        modelBuilder.Entity<MvtGestaoDredadosBi>(entity =>
        {
            entity.Property(e => e.Mercado).HasDefaultValueSql("('Interno')");
            entity.Property(e => e.DataProjecao).HasDefaultValueSql("('1900-01-01')");
        });

        modelBuilder.Entity<MvtGestaoDredadosContaContabil>(entity =>
        {
            entity.Property(e => e.Mercado).HasDefaultValueSql("('Interno')");
            entity.Property(e => e.DataProjecao).HasDefaultValueSql("('2013-01-06')");
        });

        modelBuilder.Entity<MvtGestaoDredadosContaContabilBi>(entity =>
        {
            entity.Property(e => e.Mercado).HasDefaultValueSql("('Interno')");
            entity.Property(e => e.DataProjecao).HasDefaultValueSql("('1900-01-01')");
        });

        modelBuilder.Entity<MvtGestaoDreimpressao>(entity =>
        {
            entity.Property(e => e.Codigo).ValueGeneratedNever();
            entity.Property(e => e.Expandir).HasDefaultValueSql("((1))");
        });

        modelBuilder.Entity<MvtGestaoDremodelos>(entity =>
        {
            entity.HasKey(e => e.CodModelo).HasName("PK_MGDMODELOS");

            entity.Property(e => e.CodModelo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtGestaoDreresultadoManual>(entity =>
        {
            entity.HasKey(e => new { e.CodConta, e.CodEmpresa, e.CodModelo, e.Data, e.TipoResultado, e.NumeroOrcamento }).HasName("PK_MGDRESMANUAL");
        });

        modelBuilder.Entity<MvtGestaoDresimulacao>(entity =>
        {
            entity.HasKey(e => e.IdSimulacao).HasName("PK__MvtGesta__E00501147C4F7684");

            entity.Property(e => e.IdSimulacao).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtGestaoDresimulacaoCampoOrcVenda>(entity =>
        {
            entity.HasKey(e => new { e.IdSimulacao, e.CodCampo }).HasName("PK__MvtGesta__431325A302084FDA");
        });

        modelBuilder.Entity<MvtGestaoDresimulacaoCfgContas>(entity =>
        {
            entity.HasKey(e => new { e.IdSimulacao, e.CodModelo, e.IdConta }).HasName("PK__MvtGesta__84CC00A70F624AF8");
        });

        modelBuilder.Entity<MvtGestaoDresimulacaoCfgContasValorAjuste>(entity =>
        {
            entity.HasKey(e => new { e.IdSimulacao, e.CodModelo, e.IdConta, e.Sequencia, e.DataMes }).HasName("PK__MvtGesta__4A51D5D0151B244E");
        });

        modelBuilder.Entity<MvtGestaoDresimulacaoDados>(entity =>
        {
            entity.Property(e => e.DataProjecao).HasDefaultValueSql("('1900-01-01')");
        });

        modelBuilder.Entity<MvtGestaoDresimulacaoOrcCustoMp>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.IdSimulacao, e.Sequencia }).HasName("PK__MvtGesta__92F74D681CBC4616");
        });

        modelBuilder.Entity<MvtGestaoDresimulacaoOrcCustoMpvalor>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.IdSimulacao, e.Sequencia, e.Data }).HasName("PK__MvtGesta__8CEAD08A208CD6FA");
        });

        modelBuilder.Entity<MvtGestaoDresimulacaoPeriodos>(entity =>
        {
            entity.HasKey(e => new { e.IdSimulacao, e.Sequencia }).HasName("PK__MvtGesta__A41E9273245D67DE");
        });

        modelBuilder.Entity<MvtGestaoDresimulacaoSimOrcVenda>(entity =>
        {
            entity.HasKey(e => new { e.IdSimulacao, e.EmpresaPrincipal }).HasName("PK__MvtGesta__649CCEEB2A164134");
        });

        modelBuilder.Entity<MvtGestaoIndicadorContratoCctb>(entity =>
        {
            entity.Property(e => e.NomeContaContabil).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaContabil]))", false);
        });

        modelBuilder.Entity<MvtGestaoIndicadorContratoDespCc>(entity =>
        {
            entity.Property(e => e.NomeCentroCusto).HasComputedColumnSql("([dbo].[getNomeCentroCusto]([codEmpresa],[codCentroCusto]))", false);
            entity.Property(e => e.NomeContaContabil).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaContabil]))", false);
        });

        modelBuilder.Entity<MvtGestaoPainelVisao>(entity =>
        {
            entity.Property(e => e.CodVisao).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtMenuAgendamento>(entity =>
        {
            entity.Property(e => e.Sequencia).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtMenuAgendamentoLock>(entity =>
        {
            entity.Property(e => e.Sequencia).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtMenuAjuda>(entity =>
        {
            entity.Property(e => e.Codigo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtMenuDiasUteis>(entity =>
        {
            entity.HasKey(e => e.DiaUtil).HasName("PK__MvtMenuD__A67C35A3395884C4");
        });

        modelBuilder.Entity<MvtMenuEmpresa>(entity =>
        {
            entity.Property(e => e.CodEmpresa).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtOrcamentoCfgCtbGeralFilial>(entity =>
        {
            entity.Property(e => e.CodEmpresaFilial).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtOrcamentoConfigConta>(entity =>
        {
            entity.Property(e => e.NomeContaContabil).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaContabil]))", false);
        });

        modelBuilder.Entity<MvtOrcamentoConfigContaContas>(entity =>
        {
            entity.Property(e => e.NomeContaConta).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaConta]))", false);
        });

        modelBuilder.Entity<MvtOrcamentoConfigOrcDespesa>(entity =>
        {
            entity.HasKey(e => e.CodEmpresa).HasName("PK__MvtOrcam__B8B6A44F671F4F74");

            entity.Property(e => e.CodEmpresa).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtOrcamentoConfigVenda>(entity =>
        {
            entity.HasKey(e => new { e.NumeroOrcamento, e.AnoOrcamento, e.CodEmpresa }).HasName("PK_MvtOrcamentoConfigVenda_1");
        });

        modelBuilder.Entity<MvtOrcamentoGrupoContabilizacao>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.Ano, e.NumeroOrcamento, e.CodGrupo }).HasName("PK_MvtOrcGrupoContabilizacao");
        });

        modelBuilder.Entity<MvtOrcamentoGrupoContabilizacaoItem>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.Ano, e.NumeroOrcamento, e.CodGrupo, e.Sequencia }).HasName("PK_MvtOrcGrupoContabilizacaoItem");

            entity.Property(e => e.NomeContaCredito).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaCredito]))", false);
            entity.Property(e => e.NomeContaDebito).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaDebito]))", false);
        });

        modelBuilder.Entity<MvtOrcamentoGrupoContabilizacaoItemNatureza>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.Ano, e.NumeroOrcamento, e.CodGrupo, e.Sequencia, e.SeqRateio, e.AnoMes }).HasName("PK_MvtOrcGrupoContabilizacaoItemNatureza");
        });

        modelBuilder.Entity<MvtOrcamentoGrupoContabilizacaoItemPm>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.Ano, e.NumeroOrcamento, e.CodGrupo, e.Sequencia, e.Dias }).HasName("PK_MvtOrcGrupoContabilizacaoItemPM");
        });

        modelBuilder.Entity<MvtOrcamentoMovimentoPartida>(entity =>
        {
            entity.Property(e => e.DataMov).HasDefaultValueSql("('1900-01-01 00:00:00.000')");
        });

        modelBuilder.Entity<MvtOrcamentoNaturezaFinanceira>(entity =>
        {
            entity.HasKey(e => e.CodNatureza).HasName("PKMVTORCNATFIN");
        });

        modelBuilder.Entity<MvtOrcamentoOrcamento>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.NumeroOrcamento }).HasName("PK__MvtOrcam__D372AD2C03BB8E22");
        });

        modelBuilder.Entity<MvtOrcamentoOrcamentoDespesa>(entity =>
        {
            entity.Property(e => e.NomeCentroCusto).HasComputedColumnSql("([dbo].[getNomeCentroCusto]([codEmpresa],[codCentroCusto]))", false);
            entity.Property(e => e.NomeContaContabil).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaContabil]))", false);
            entity.Property(e => e.TipoConta).HasComputedColumnSql("([dbo].[getTipoConta]([codEmpresa],[codContaContabil]))", false);
        });

        modelBuilder.Entity<MvtOrcamentoOrcamentoDespesaDetalha>(entity =>
        {
            entity.Property(e => e.NomeCentroCusto).HasComputedColumnSql("([dbo].[getNomeCentroCusto]([codEmpresa],[codCentroCusto]))", false);
            entity.Property(e => e.NomeContaContabil).HasComputedColumnSql("([dbo].[getNomeContaContabil]([codEmpresa],[codContaContabil]))", false);
            entity.Property(e => e.TipoConta).HasComputedColumnSql("([dbo].[getTipoConta]([codEmpresa],[codContaContabil]))", false);
        });

        modelBuilder.Entity<MvtOrcamentoSimulacaoOrcVenda>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.CodSimulacao }).HasName("PK__MvtOrcam__6E6A0EF414E61A24");
        });

        modelBuilder.Entity<MvtOrcamentoSimulacaoOrcVendaCampo>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.CodSimulacao, e.CodCampo }).HasName("PK__MvtOrcam__145B6CBF18B6AB08");
        });

        modelBuilder.Entity<MvtOrcamentoSimulacaoOrcVendaItemCampo>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.CodSimulacao, e.Sequencia, e.CodCampo, e.NomeCampo }).HasName("PK__MvtOrcam__FE9FFD341C873BEC");
        });

        modelBuilder.Entity<MvtOrcamentoSimulacaoOrcVendaItemValor>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.CodSimulacao, e.Sequencia, e.Data }).HasName("PK__MvtOrcam__04362A202057CCD0");
        });

        modelBuilder.Entity<MvtOrcamentoVendaHistAlteracao>(entity =>
        {
            entity.Property(e => e.Seq).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<MvtOrcamentoVendaVersaoTeste>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.Ano, e.Versao }).HasName("PK_MvtOrcamentoVendaVersaoTesteTeste");
        });

        modelBuilder.Entity<MvtOrcamentoVersaoOrcVenda>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.NumeroOrcamento, e.Ano }).HasName("PK__MvtOrcam__93ACFA875F9E293D");
        });

        modelBuilder.Entity<MvtRhOrcamentoSalarial>(entity =>
        {
            entity.HasKey(e => new { e.CodEmpresa, e.NumeroOrcamento, e.Data, e.CodCentroCusto, e.CodCargo, e.CodFuncionario }).HasName("PK_MvtRhOrcamentoSalarial_1");
        });

        modelBuilder.Entity<MvtRhbtCargos>(entity =>
        {
            entity.Property(e => e.CodCargo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtStatsDashFiltroTipo>(entity =>
        {
            entity.HasKey(e => new { e.CodFiltro, e.CodTipo }).HasName("PK__MvtStats__183172B7689D8392");
        });

        modelBuilder.Entity<MvtStatsDashGeraEstatistica>(entity =>
        {
            entity.HasKey(e => e.Codigo).HasName("PK__MvtStats__40F9A20764CCF2AE");

            entity.Property(e => e.Codigo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtStatsDashObjeto>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.CodObjeto }).HasName("PK__MvtStats__8AD1AD3260FC61CA");
        });

        modelBuilder.Entity<MvtStatsDashObjetoFiltro>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.CodObjeto, e.CodFiltro }).HasName("PK__MvtStats__336D8F1E5D2BD0E6");
        });

        modelBuilder.Entity<MvtStatsDashObjetoFiltroOrigem>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.CodObjeto, e.CodFiltro, e.CodTipo }).HasName("PK__MvtStats__3CC99C40595B4002");
        });

        modelBuilder.Entity<MvtStatsDashObjetoItem>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.CodObjeto, e.CodItem }).HasName("PK__MvtStats__4F7A08A0558AAF1E");
        });

        modelBuilder.Entity<MvtStatsDashObjetoItemOrigem>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.CodObjeto, e.CodItem, e.CodTipo }).HasName("PK__MvtStats__40DE1BFE370627FE");
        });

        modelBuilder.Entity<MvtStatsDashPermissaoCriacao>(entity =>
        {
            entity.HasKey(e => e.Usuario).HasName("PK__MvtStats__9AFF8FC73AD6B8E2");
        });

        modelBuilder.Entity<MvtStatsDashPermissaoGrupo>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.CodGrupo }).HasName("PK__MvtStats__87DC23493EA749C6");
        });

        modelBuilder.Entity<MvtStatsDashPermissaoUsuario>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.Usuario }).HasName("PK__MvtStats__147DE5094277DAAA");
        });

        modelBuilder.Entity<MvtStatsDashRecipiente>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.CodRecipiente }).HasName("PK__MvtStats__3DA28A3046486B8E");
        });

        modelBuilder.Entity<MvtStatsDashRecipientePosicao>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.CodRecipiente, e.CodPosicao }).HasName("PK__MvtStats__3CAF68354A18FC72");
        });

        modelBuilder.Entity<MvtStatsDashVisao>(entity =>
        {
            entity.HasKey(e => e.CodVisao).HasName("PK__MvtStats__7DD21DF54DE98D56");

            entity.Property(e => e.CodVisao).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtStatsDashVisaoFiltro>(entity =>
        {
            entity.HasKey(e => new { e.CodVisao, e.CodFiltro }).HasName("PK__MvtStats__E6103F3E51BA1E3A");
        });

        modelBuilder.Entity<MvtStatsPermissaoDadosCfg>(entity =>
        {
            entity.Property(e => e.Codigo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtVendasCfgEmailDinamico>(entity =>
        {
            entity.Property(e => e.Codigo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtVendasCfgFiltroAdicional>(entity =>
        {
            entity.Property(e => e.CodFiltro).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtVendasEstatisticaCadastro>(entity =>
        {
            entity.Property(e => e.Codigo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtVendasEstatisticaConsultaSalvaApp>(entity =>
        {
            entity.Property(e => e.Codigo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtVendasEstatisticaModulosApp>(entity =>
        {
            entity.Property(e => e.Codigo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtVendasEstruturaConsultaColunaOpcaoTipo>(entity =>
        {
            entity.HasKey(e => new { e.Nome, e.CodTipo }).HasName("PK__MvtVenda__CB629ED24242D080");
        });

        modelBuilder.Entity<MvtVendasEstruturaConsultaValorOpcaoTipo>(entity =>
        {
            entity.HasKey(e => new { e.Nome, e.CodTipo }).HasName("PK__MvtVenda__CB629ED24EA8A765");
        });

        modelBuilder.Entity<MvtVendasEstruturaCorPercent>(entity =>
        {
            entity.Property(e => e.CodEmpresa).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtVendasEstruturaFaturamento>(entity =>
        {
            entity.Property(e => e.Ano).HasDefaultValueSql("((0))");
            entity.Property(e => e.CodMesorregiao).HasComputedColumnSql("([dbo].[getCodMesorregiaoCidade]([codCidade]))", false);
            entity.Property(e => e.CodMicrorregiao).HasComputedColumnSql("([dbo].[getCodMicrorregiaoCidade]([codCidade]))", false);
            entity.Property(e => e.CodRepresentanteAtual).HasComputedColumnSql("([dbo].[getRepresentanteAtual]([codEmpresa],[codCliente]))", false);
            entity.Property(e => e.Mesorregiao).HasComputedColumnSql("([dbo].[getMesorregiaoCidade]([codCidade]))", false);
            entity.Property(e => e.Microrregiao).HasComputedColumnSql("([dbo].[getMicrorregiaoCidade]([codCidade]))", false);
            entity.Property(e => e.NomeRepresentanteAtual).HasComputedColumnSql("([dbo].[getNomeRepresentanteAtual]([codEmpresa],[dbo].[getRepresentanteAtual]([codEmpresa],[codCliente])))", false);
            entity.Property(e => e.Peso).HasDefaultValueSql("((0))");
            entity.Property(e => e.QuantidadeDevolvidaUn).HasDefaultValueSql("((0))");
            entity.Property(e => e.Valor).HasDefaultValueSql("((0))");
            entity.Property(e => e.ValorDevolucao).HasDefaultValueSql("((0))");
            entity.Property(e => e.ValorFaturado).HasDefaultValueSql("((0))");
            entity.Property(e => e.ValorPrecoMedioUnitarioVendas).HasDefaultValueSql("((0))");
            entity.Property(e => e.ValorTabela).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrCofins).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrComiss).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrCsll).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrCustoTotal).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrFrete).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrFreteAdicional).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrFreteFechamento).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrFreteM3).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrFreteTxEntrada).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrIcms).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrIpi).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrPis).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrSeguro).HasDefaultValueSql("((0))");
            entity.Property(e => e.VlrTaxaDescarga).HasDefaultValueSql("((0))");
        });

        modelBuilder.Entity<MvtVendasEstruturaMetaCliente>(entity =>
        {
            entity.Property(e => e.Ano).HasDefaultValueSql("((0))");
            entity.Property(e => e.CodClienteAgrupador).HasDefaultValueSql("((0))");
            entity.Property(e => e.CodGerente).HasDefaultValueSql("((0))");
            entity.Property(e => e.CodRepreentanteCongelado).HasDefaultValueSql("((0))");
            entity.Property(e => e.CodRepresentanteCliCalc).HasDefaultValueSql("((0))");
            entity.Property(e => e.CodRepresentanteMetaCalc).HasDefaultValueSql("((0))");
            entity.Property(e => e.CodSupervisor).HasDefaultValueSql("((0))");
            entity.Property(e => e.CodVendedor).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaCashMargin).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaDepartamento).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaLucroBruto).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaLucroBrutoDepartamento).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaMargemDepartamento).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaMargemMercado).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaPercDesc).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaPositivacao).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaQtdeSubCat).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaRol).HasDefaultValueSql("((0))");
            entity.Property(e => e.MetaRoldepartamento).HasDefaultValueSql("((0))");
            entity.Property(e => e.Percent).HasDefaultValueSql("((0))");
            entity.Property(e => e.PercentCalc).HasDefaultValueSql("((0))");
            entity.Property(e => e.PrecoMedio).HasDefaultValueSql("((0))");
            entity.Property(e => e.QtdeMeta).HasDefaultValueSql("((0))");
            entity.Property(e => e.QtdeMetaCli).HasDefaultValueSql("((0))");
            entity.Property(e => e.ValorAcumuladoMetaCli).HasDefaultValueSql("((0))");
            entity.Property(e => e.ValorMeta).HasDefaultValueSql("((0))");
            entity.Property(e => e.ValorMetaCli).HasDefaultValueSql("((0))");
        });

        modelBuilder.Entity<MvtVendasHistoricoMensal>(entity =>
        {
            entity.Property(e => e.Estabelecimento).HasDefaultValueSql("((1))");
        });

        modelBuilder.Entity<MvtVendasLockAtualizacaoEstatistica>(entity =>
        {
            entity.Property(e => e.CodEmpresa).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtVendasTipoEstatistica>(entity =>
        {
            entity.Property(e => e.Codigo).ValueGeneratedNever();
        });

        modelBuilder.Entity<MvtVendasTipoEstatisticaAgrupamento>(entity =>
        {
            entity.Property(e => e.Codigo).ValueGeneratedNever();
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
