// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace api_orcamento.Models
{
    public partial class GetEngenhariaExplodidaResult
    {
        public string codInsumo { get; set; }
        public double qtdeUtilizada { get; set; }
    }
}
