// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using api_orcamento.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace api_orcamento.Models
{
    public partial interface IContextProcedures
    {
        Task<int> gravaCustoItensFaturadosAsync(int? codEmpresa, DateTime? dataDe, DateTime? dataAte, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
