// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Keyless]
public partial class MvtAcessoMensagem
{
    [Column("de")]
    [StringLength(50)]
    [Unicode(false)]
    public string De { get; set; }

    [Column("para")]
    [StringLength(50)]
    [Unicode(false)]
    public string Para { get; set; }

    [Column("dataHora")]
    [StringLength(50)]
    [Unicode(false)]
    public string DataHora { get; set; }

    [Column("mensagem")]
    [StringLength(3000)]
    [Unicode(false)]
    public string Mensagem { get; set; }

    [Column("todos")]
    [StringLength(3000)]
    [Unicode(false)]
    public string Todos { get; set; }

    [Column("lida")]
    public int? Lida { get; set; }
}