// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Keyless]
public partial class MvtAcessoPermissao
{
    [Column("sistema")]
    [StringLength(50)]
    [Unicode(false)]
    public string Sistema { get; set; }

    [Column("nomeBotao")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeBotao { get; set; }

    [Column("tipo")]
    public int? Tipo { get; set; }

    [Column("usuarioGrupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string UsuarioGrupo { get; set; }
}