// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Keyless]
public partial class MvtAcessoAtualizacaoPeriodo
{
    [Column("dataHoraInicio", TypeName = "datetime")]
    public DateTime? DataHoraInicio { get; set; }

    [Column("dataHoraFim", TypeName = "datetime")]
    public DateTime? DataHoraFim { get; set; }

    [Column("systemName")]
    [StringLength(50)]
    [Unicode(false)]
    public string SystemName { get; set; }
}