// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Keyless]
public partial class MvtAcessoActiveDirectory
{
    [Column("server1")]
    [StringLength(50)]
    [Unicode(false)]
    public string Server1 { get; set; }

    [Column("server2")]
    [StringLength(50)]
    [Unicode(false)]
    public string Server2 { get; set; }

    [Column("systemName")]
    [StringLength(50)]
    [Unicode(false)]
    public string SystemName { get; set; }
}