// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Usuario", "CodGrupo")]
public partial class MvtAcessoGrupoMembro
{
    [Key]
    [Column("usuario")]
    [StringLength(500)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Key]
    [Column("codGrupo")]
    public int CodGrupo { get; set; }
}