// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Keyless]
public partial class MvtAcessoLog
{
    [Column("data", TypeName = "datetime")]
    public DateTime? Data { get; set; }

    [Column("hora", TypeName = "datetime")]
    public DateTime? Hora { get; set; }

    [Column("usuario")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Column("valores")]
    [StringLength(2000)]
    [Unicode(false)]
    public string Valores { get; set; }

    [Column("programa")]
    [StringLength(100)]
    [Unicode(false)]
    public string Programa { get; set; }

    [Column("comandoExecutado")]
    [StringLength(50)]
    [Unicode(false)]
    public string ComandoExecutado { get; set; }
}