// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodSupervisor", "Usuario")]
public partial class MvtAcessoUsuarioSupervisor
{
    [Key]
    [Column("codSupervisor")]
    [StringLength(50)]
    [Unicode(false)]
    public string CodSupervisor { get; set; }

    [Key]
    [Column("usuario")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }
}