// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Keyless]
public partial class MvtAcessoUsuarioHistoricoAcesso
{
    [Column("data", TypeName = "datetime")]
    public DateTime? Data { get; set; }

    [Column("hora", TypeName = "datetime")]
    public DateTime? Hora { get; set; }

    [Column("usuario")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Required]
    [Column("nomeBotao")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeBotao { get; set; }

    [Column("nomeModulo")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeModulo { get; set; }

    [Column("nomeExibicao")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeExibicao { get; set; }

    [Column("sistema")]
    [StringLength(50)]
    [Unicode(false)]
    public string Sistema { get; set; }

    [Column("situacao")]
    public int? Situacao { get; set; }
}