// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Keyless]
public partial class MvtAcessoEstacao
{
    [Column("sistema")]
    [StringLength(50)]
    [Unicode(false)]
    public string Sistema { get; set; }

    [Column("usuario")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Column("estacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Estacao { get; set; }

    [Column("ip")]
    [StringLength(50)]
    [Unicode(false)]
    public string Ip { get; set; }

    [Column("data", TypeName = "datetime")]
    public DateTime? Data { get; set; }

    [Column("hora", TypeName = "datetime")]
    public DateTime? Hora { get; set; }
}