// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVersao", "NomeReferencia")]
public partial class MvtAcessoVersaoReferencia
{
    [Column("arquivos")]
    [StringLength(100)]
    [Unicode(false)]
    public string Arquivos { get; set; }

    [Key]
    [Column("codVersao")]
    [StringLength(50)]
    [Unicode(false)]
    public string CodVersao { get; set; }

    [Column("data", TypeName = "date")]
    public DateTime? Data { get; set; }

    [Column("estacao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Estacao { get; set; }

    [Column("hora")]
    public TimeSpan? Hora { get; set; }

    [Key]
    [Column("nomeReferencia")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeReferencia { get; set; }

    [Column("observacao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Observacao { get; set; }

    [Column("usuario")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }
}