// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodProduto")]
public partial class MvtCadProduto
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codProduto")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodProduto { get; set; }

    [Column("nomeProduto")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeProduto { get; set; }

    [Column("nomeProdutoCompleto")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeProdutoCompleto { get; set; }

    [Column("unidadeMedida")]
    [StringLength(10)]
    [Unicode(false)]
    public string UnidadeMedida { get; set; }

    [Column("codGrupo")]
    public int? CodGrupo { get; set; }

    [Column("codSubGrupo")]
    public int? CodSubGrupo { get; set; }
}