// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodMoeda", "Data")]
public partial class MvtCadCotacaoMoeda
{
    [Key]
    [Column("codMoeda")]
    public int CodMoeda { get; set; }

    [Key]
    [Column("data", TypeName = "datetime")]
    public DateTime Data { get; set; }

    [Column("cotacao")]
    public double? Cotacao { get; set; }

    [Column("taxa")]
    public double? Taxa { get; set; }
}