// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtCtbIndicadores
{
    [Key]
    [Column("codIndicador")]
    public int CodIndicador { get; set; }

    [Required]
    [Column("descricao")]
    [StringLength(50)]
    public string Descricao { get; set; }

    [Column("tipo")]
    public int Tipo { get; set; }

    [Column("periodo")]
    public int Periodo { get; set; }

    [Column("codBacen")]
    public int? CodBacen { get; set; }
}