// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodCliente")]
public partial class MvtCadCliente
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codCliente")]
    public int CodCliente { get; set; }

    [Column("cpfCnpj")]
    [StringLength(30)]
    [Unicode(false)]
    public string CpfCnpj { get; set; }

    [Column("nomeCliente")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeCliente { get; set; }

    [Column("nomeFantasia")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeFantasia { get; set; }

    [Column("codRepresentante")]
    public int? CodRepresentante { get; set; }

    [Column("codGrupoCliente")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodGrupoCliente { get; set; }

    [Column("codSetor")]
    public int? CodSetor { get; set; }

    [Column("codDistrito")]
    public int? CodDistrito { get; set; }

    [Column("ativo")]
    public int? Ativo { get; set; }

    [Column("uf")]
    [StringLength(8)]
    [Unicode(false)]
    public string Uf { get; set; }

    [Column("nomeRegiao")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeRegiao { get; set; }

    [Column("codCanal")]
    [StringLength(40)]
    [Unicode(false)]
    public string CodCanal { get; set; }

    [Column("cidade")]
    [StringLength(50)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [Column("codClienteAgrupador")]
    public int? CodClienteAgrupador { get; set; }

    [Column("codRamoAtividade")]
    public int? CodRamoAtividade { get; set; }

    [Column("nomeRamoAtividade")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeRamoAtividade { get; set; }

    [Column("codCidade")]
    public int? CodCidade { get; set; }

    [Column("cep")]
    [StringLength(10)]
    [Unicode(false)]
    public string Cep { get; set; }

    [Column("latitude")]
    public double? Latitude { get; set; }

    [Column("longitude")]
    public double? Longitude { get; set; }
}