// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtCadCentroCustoTipo
{
    [Key]
    [Column("codTipoCC")]
    public int CodTipoCc { get; set; }

    [Column("nomeTipo")]
    [StringLength(100)]
    public string NomeTipo { get; set; }
}