// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodFinanciamento")]
public partial class MvtCtbFinanciamento
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codFinanciamento")]
    public int CodFinanciamento { get; set; }

    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Column("dataLiberacao", TypeName = "date")]
    public DateTime? DataLiberacao { get; set; }

    [Required]
    [Column("descricao")]
    [StringLength(100)]
    public string Descricao { get; set; }

    [Column("sistemaAmortizacao")]
    public int SistemaAmortizacao { get; set; }

    [Column("valor")]
    public double Valor { get; set; }

    [Column("tipo")]
    public int Tipo { get; set; }

    [Column("moeda")]
    public int Moeda { get; set; }

    [Column("modalidade")]
    public int Modalidade { get; set; }

    [Column("taxaJuros")]
    public double? TaxaJuros { get; set; }

    [Column("periodoJuros")]
    public int? PeriodoJuros { get; set; }

    [Column("codIndicadorCorrecao")]
    public int? CodIndicadorCorrecao { get; set; }

    [Column("tipoJurosCorrecao")]
    public int? TipoJurosCorrecao { get; set; }

    [Column("tipoJuros")]
    public int? TipoJuros { get; set; }

    [Column("carencia")]
    public int Carencia { get; set; }

    [Column("prazoCarencia")]
    public double? PrazoCarencia { get; set; }

    [Column("periodoPrazoCarencia")]
    public int? PeriodoPrazoCarencia { get; set; }

    [Column("freqPgtoCarencia")]
    public double? FreqPgtoCarencia { get; set; }

    [Column("periodoFreqPgtoCarencia")]
    public int? PeriodoFreqPgtoCarencia { get; set; }

    [Column("percProprio")]
    public int? PercProprio { get; set; }

    [Column("dataDesembolso", TypeName = "date")]
    public DateTime? DataDesembolso { get; set; }

    [Column("percTerceiro")]
    public int? PercTerceiro { get; set; }

    [Column("dataInicio", TypeName = "date")]
    public DateTime? DataInicio { get; set; }

    [Column("numParcelas")]
    public int? NumParcelas { get; set; }

    [Column("freqPgto")]
    public double? FreqPgto { get; set; }

    [Column("periodoFreqPgto")]
    public int? PeriodoFreqPgto { get; set; }

    [Column("tipoInstituicao")]
    public int TipoInstituicao { get; set; }

    [Required]
    [Column("nomeInstituicao")]
    [StringLength(100)]
    public string NomeInstituicao { get; set; }

    [Column("pgtoAntecipado")]
    public int? PgtoAntecipado { get; set; }

    [Column("diaPgtoCarencia")]
    public int? DiaPgtoCarencia { get; set; }

    [Column("diaPgtoAmortizacao")]
    public int? DiaPgtoAmortizacao { get; set; }

    [Column("tipoCalculoCarencia")]
    public int? TipoCalculoCarencia { get; set; }

    [Column("projecao")]
    public int Projecao { get; set; }

    [Column("percComissao")]
    public double? PercComissao { get; set; }

    [Column("dataInicioCarencia", TypeName = "date")]
    public DateTime? DataInicioCarencia { get; set; }

    [Column("codNatFinanceira")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNatFinanceira { get; set; }

    [Column("taxaCambio")]
    public double? TaxaCambio { get; set; }

    [Column("possuiJuros")]
    public int? PossuiJuros { get; set; }

    [Column("possuiJurosDiferenciado")]
    public int? PossuiJurosDiferenciado { get; set; }

    [Column("freqPgtoJurosDiferenciado")]
    public int? FreqPgtoJurosDiferenciado { get; set; }

    [Column("periodoJurosDiferenciado")]
    public int? PeriodoJurosDiferenciado { get; set; }

    [Column("ratearCarencia")]
    public int? RatearCarencia { get; set; }

    [Column("indicadorCorrePercAplicado")]
    public double? IndicadorCorrePercAplicado { get; set; }

    [Column("diasBaseJuros")]
    public int? DiasBaseJuros { get; set; }

    [Column("numeroOrcamento")]
    public int? NumeroOrcamento { get; set; }

    [Column("anoOrcamento")]
    public int? AnoOrcamento { get; set; }

    [Column("moedaSwap")]
    public int? MoedaSwap { get; set; }

    [Column("modalidadeSwap")]
    public int? ModalidadeSwap { get; set; }

    [Column("taxaJurosSwap")]
    public double? TaxaJurosSwap { get; set; }

    [Column("tipoJurosCorrecaoSwap")]
    public int? TipoJurosCorrecaoSwap { get; set; }

    [Column("tipoJurosSwap")]
    public int? TipoJurosSwap { get; set; }

    [Column("periodoJurosSwap")]
    public int? PeriodoJurosSwap { get; set; }

    [Column("diasBaseJurosSwap")]
    public int? DiasBaseJurosSwap { get; set; }

    [Column("codIndicadorCorrecaoSwap")]
    public int? CodIndicadorCorrecaoSwap { get; set; }

    [Column("indicadorCorrecaoPercAplicadoSwap")]
    public double? IndicadorCorrecaoPercAplicadoSwap { get; set; }

    [Column("temSwap")]
    public int? TemSwap { get; set; }

    [Column("taxaCambioSwap")]
    public double? TaxaCambioSwap { get; set; }

    [Column("numIDERP")]
    public int? NumIderp { get; set; }
}