// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodFinanciamento", "Data", "Swap", "Tipo")]
public partial class MvtCtbFinanciamentoParcela
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codFinanciamento")]
    public int CodFinanciamento { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("swap")]
    public bool Swap { get; set; }

    [Key]
    [Column("tipo")]
    public int Tipo { get; set; }

    [Column("valorParcela")]
    public double? ValorParcela { get; set; }

    [Column("valorJuros")]
    public double? ValorJuros { get; set; }

    [Column("valorJurosAcumulado")]
    public double? ValorJurosAcumulado { get; set; }

    [Column("valorCaptacao")]
    public double? ValorCaptacao { get; set; }

    [Column("saldoInicialCalc")]
    public double SaldoInicialCalc { get; set; }

    [Column("valorCaptacaoCalc")]
    public double ValorCaptacaoCalc { get; set; }

    [Column("variacaoCambialCalc")]
    public double VariacaoCambialCalc { get; set; }

    [Column("valorJurosAcumuladoPeriodo")]
    public double ValorJurosAcumuladoPeriodo { get; set; }

    [Column("valorJurosAcumuladoPeriodoCalc")]
    public double ValorJurosAcumuladoPeriodoCalc { get; set; }

    [Column("somaJurosAcumuladoPeriodoCalc")]
    public double SomaJurosAcumuladoPeriodoCalc { get; set; }

    [Column("valorAmortizacaoCalc")]
    public double ValorAmortizacaoCalc { get; set; }

    [Column("valorJurosAcumuladoCalc")]
    public double ValorJurosAcumuladoCalc { get; set; }

    [Column("valorParcelaCalc")]
    public double ValorParcelaCalc { get; set; }

    [Column("saldoFinalCalc")]
    public double SaldoFinalCalc { get; set; }

    [Column("totalCPCalc")]
    public double TotalCpcalc { get; set; }

    [Column("totalLPCalc")]
    public double TotalLpcalc { get; set; }

    [Column("dataDesembolso", TypeName = "date")]
    public DateTime? DataDesembolso { get; set; }

    [Column("saldoInicial")]
    public double? SaldoInicial { get; set; }

    [Column("saldoFinal")]
    public double? SaldoFinal { get; set; }

    [Column("totalCP")]
    public double? TotalCp { get; set; }

    [Column("totalLP")]
    public double? TotalLp { get; set; }
}