// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Codigo")]
[Microsoft.EntityFrameworkCore.Index("CodEmpresa", "Codigo", "Grupo", Name = "IdxGrupoConta")]
public partial class MvtCtbContaContabil
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codigo")]
    [StringLength(10)]
    [Unicode(false)]
    public string Codigo { get; set; }

    [Column("nome")]
    [StringLength(250)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("tipo")]
    [StringLength(1)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("classificacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Classificacao { get; set; }

    [Column("caracteristica")]
    [StringLength(20)]
    [Unicode(false)]
    public string Caracteristica { get; set; }

    [Column("contaPai")]
    [StringLength(10)]
    [Unicode(false)]
    public string ContaPai { get; set; }

    [Column("grupo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Grupo { get; set; }
}
