// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Data", "CodItem")]
public partial class MvtCusProduto
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("codItem")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodItem { get; set; }

    [Column("qtdeProducao")]
    public double? QtdeProducao { get; set; }

    [Column("vlrMaterialTotal")]
    public double? VlrMaterialTotal { get; set; }

    [Column("vlrGGFTotal")]
    public double? VlrGgftotal { get; set; }

    [Column("vlrMobDirTotal")]
    public double? VlrMobDirTotal { get; set; }

    [Column("vlrMobIndTotal")]
    public double? VlrMobIndTotal { get; set; }

    [Column("vlrMaterial")]
    public double? VlrMaterial { get; set; }

    [Column("vlrGGF")]
    public double? VlrGgf { get; set; }

    [Column("vlrMobDir")]
    public double? VlrMobDir { get; set; }

    [Column("vlrMobInd")]
    public double? VlrMobInd { get; set; }
}