// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodNivel")]
public partial class MvtCadNivelHierarq
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codNivel")]
    public int CodNivel { get; set; }

    [Column("nomeNivel")]
    [StringLength(200)]
    public string NomeNivel { get; set; }

    [Column("usuarioResponsavel")]
    [StringLength(100)]
    public string UsuarioResponsavel { get; set; }
}