// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodCentroCusto")]
public partial class MvtCadCentroCusto
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Column("nomeCentroCusto")]
    [StringLength(300)]
    [Unicode(false)]
    public string NomeCentroCusto { get; set; }

    [Column("tipo")]
    [StringLength(1)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("classificacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Classificacao { get; set; }

    [Column("caracteristica")]
    [StringLength(20)]
    [Unicode(false)]
    public string Caracteristica { get; set; }

    [Column("codTipo")]
    public int? CodTipo { get; set; }

    [Column("situacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Situacao { get; set; }
}