// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtCadCidade
{
    [Key]
    [Column("codCidade")]
    [StringLength(5)]
    [Unicode(false)]
    public string CodCidade { get; set; }

    [Column("nomeCidade")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeCidade { get; set; }

    [Column("siglaEstado")]
    [StringLength(50)]
    [Unicode(false)]
    public string SiglaEstado { get; set; }

    [Required]
    [Column("codIBGE")]
    [StringLength(15)]
    [Unicode(false)]
    public string CodIbge { get; set; }
}