// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodGrupo", "CodEmpresa")]
public partial class MvtCadGrupoEmpresaItem
{
    [Key]
    [Column("codGrupo")]
    public int CodGrupo { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }
}