// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodInvestimento", "NumeroOrcamento", "Ano")]
public partial class MvtCtbOrcamentoCapitaisCapa
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codInvestimento")]
    public int CodInvestimento { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Column("tipoInvestimento")]
    public int TipoInvestimento { get; set; }

    [Required]
    [Column("descricao")]
    [StringLength(1000)]
    public string Descricao { get; set; }

    [Required]
    [Column("gestor")]
    [StringLength(50)]
    public string Gestor { get; set; }

    [Column("ifrs")]
    public double Ifrs { get; set; }

    [Column("societario")]
    public double Societario { get; set; }

    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Column("codEmpresaFinanciamento")]
    public int? CodEmpresaFinanciamento { get; set; }

    [Column("codFinanciamento")]
    public int? CodFinanciamento { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Column("aprovado")]
    public int? Aprovado { get; set; }

    [Column("origemInvestimento")]
    public int? OrigemInvestimento { get; set; }

    [Column("tipoPagamento")]
    public int? TipoPagamento { get; set; }

    [Column("valorProjeto")]
    public double? ValorProjeto { get; set; }

    [Column("financiamentoMovtech")]
    public int? FinanciamentoMovtech { get; set; }

    [Column("percentualPagoEmpresa")]
    public double? PercentualPagoEmpresa { get; set; }

    [Column("codArea")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodArea { get; set; }

    [Column("numProjeto")]
    public int? NumProjeto { get; set; }

    [Column("descricaoProjeto")]
    [StringLength(150)]
    [Unicode(false)]
    public string DescricaoProjeto { get; set; }

    [Column("numSeqItemTovts")]
    public int? NumSeqItemTovts { get; set; }

    [Column("dataInicioDepreciacao", TypeName = "date")]
    public DateTime? DataInicioDepreciacao { get; set; }
}