// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodPacote", "CodEmpresa")]
public partial class MvtCtbPacoteResponsavel
{
    [Key]
    [Column("codPacote")]
    public int CodPacote { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("responsavel")]
    [StringLength(50)]
    [Unicode(false)]
    public string Responsavel { get; set; }
}