// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodInvestimento", "NumeroOrcamento", "Ano", "DataParcela")]
public partial class MvtCtbOrcamentoCapitaisParcelas
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codInvestimento")]
    public int CodInvestimento { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("dataParcela", TypeName = "date")]
    public DateTime DataParcela { get; set; }

    [Column("valorParcela")]
    public double? ValorParcela { get; set; }

    [Column("antecipada")]
    public bool? Antecipada { get; set; }
}