// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "TipoFuncionario", "CodFuncionario")]
public partial class MvtCadFuncionario
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("tipoFuncionario")]
    [StringLength(10)]
    [Unicode(false)]
    public string TipoFuncionario { get; set; }

    [Key]
    [Column("codFuncionario")]
    public int CodFuncionario { get; set; }

    [Column("nomeFuncionario")]
    [StringLength(40)]
    [Unicode(false)]
    public string NomeFuncionario { get; set; }

    [Column("dataAdmissao", TypeName = "date")]
    public DateTime? DataAdmissao { get; set; }

    [Column("situacao")]
    [StringLength(40)]
    [Unicode(false)]
    public string Situacao { get; set; }

    [Column("codCargo")]
    [StringLength(24)]
    [Unicode(false)]
    public string CodCargo { get; set; }

    [Column("codCentroCusto")]
    public int? CodCentroCusto { get; set; }

    [Column("dataNascimento", TypeName = "date")]
    public DateTime? DataNascimento { get; set; }
}