// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Data", "CodDeposito", "CodItem", "CodLote")]
public partial class MvtEstPosicaoMensal
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("codDeposito")]
    public int CodDeposito { get; set; }

    [Key]
    [Column("codItem")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodItem { get; set; }

    [Key]
    [Column("codLote")]
    [StringLength(30)]
    [Unicode(false)]
    public string CodLote { get; set; }

    [Column("qtdeSaldoInicial")]
    public double? QtdeSaldoInicial { get; set; }

    [Column("qtdeSaldoFinal")]
    public double? QtdeSaldoFinal { get; set; }

    [Column("qtdeSaldoAtual")]
    public double? QtdeSaldoAtual { get; set; }

    [Column("vlrInicial")]
    public double? VlrInicial { get; set; }

    [Column("vlrPeriodo")]
    public double? VlrPeriodo { get; set; }

    [Column("vlrCustoMedio")]
    public double? VlrCustoMedio { get; set; }
}