// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodRepresent")]
public partial class MvtFatRepresentante
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codRepresent")]
    public int CodRepresent { get; set; }

    [Column("nome")]
    [StringLength(200)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("cnpjcpf")]
    [StringLength(50)]
    [Unicode(false)]
    public string Cnpjcpf { get; set; }
}