// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodModelo", "CodConta", "CodEmpresa")]
[Table("MvtGestaoDREContasEmpresaCalculada")]
public partial class MvtGestaoDrecontasEmpresaCalculada
{
    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Key]
    [Column("codConta")]
    public int CodConta { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }
}