// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("IdSimulacao", "CodModelo", "IdConta")]
[Table("MvtGestaoDRESimulacaoCfgContas")]
public partial class MvtGestaoDresimulacaoCfgContas
{
    [Key]
    [Column("idSimulacao")]
    public int IdSimulacao { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Key]
    [Column("idConta")]
    [StringLength(150)]
    [Unicode(false)]
    public string IdConta { get; set; }

    [Column("tipoCalculo")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoCalculo { get; set; }

    [Column("codContaBase")]
    public int? CodContaBase { get; set; }

    [Column("ocultar")]
    public int? Ocultar { get; set; }
}