// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodSlide")]
public partial class MvtGestaoPainelVisaoSlide
{
    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Key]
    [Column("codSlide")]
    public int CodSlide { get; set; }

    [Column("descricao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("duracao")]
    public double? Duracao { get; set; }

    [Column("atualizacao")]
    public double? Atualizacao { get; set; }

    [Column("ordem")]
    public double? Ordem { get; set; }
}