// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Data", "Identificador", "Sequencia")]
public partial class MvtGestaoAnaliseCausa
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("identificador")]
    [StringLength(50)]
    [Unicode(false)]
    public string Identificador { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Column("causa")]
    [StringLength(500)]
    [Unicode(false)]
    public string Causa { get; set; }

    [Column("justificativa")]
    [StringLength(1000)]
    [Unicode(false)]
    public string Justificativa { get; set; }

    [Column("gerarPlanoAcao")]
    public int? GerarPlanoAcao { get; set; }

    [Column("dataCausa", TypeName = "date")]
    public DateTime? DataCausa { get; set; }

    [Column("usuario")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Column("origem")]
    [StringLength(50)]
    [Unicode(false)]
    public string Origem { get; set; }

    [Column("descricaoIdentificador")]
    [StringLength(500)]
    [Unicode(false)]
    public string DescricaoIdentificador { get; set; }
}