// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Ano", "CodContrato", "CodIndicador", "CodProduto", "Linha", "Grupo", "UnidadeNegocio", "Segmento")]
public partial class MvtGestaoIndicadorContratoOrcVendas
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("codContrato")]
    public int CodContrato { get; set; }

    [Key]
    [Column("codIndicador")]
    public int CodIndicador { get; set; }

    [Key]
    [Column("codProduto")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodProduto { get; set; }

    [Key]
    [Column("linha")]
    [StringLength(50)]
    [Unicode(false)]
    public string Linha { get; set; }

    [Key]
    [Column("grupo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Grupo { get; set; }

    [Key]
    [Column("unidadeNegocio")]
    [StringLength(50)]
    [Unicode(false)]
    public string UnidadeNegocio { get; set; }

    [Key]
    [Column("segmento")]
    [StringLength(50)]
    [Unicode(false)]
    public string Segmento { get; set; }
}