// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodObjeto")]
public partial class MvtGestaoPainelVisaoObjeto
{
    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Key]
    [Column("codObjeto")]
    public int CodObjeto { get; set; }

    [Column("descricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("tipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("modelo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Modelo { get; set; }

    [Column("codSlide")]
    public int? CodSlide { get; set; }

    [Column("codArea")]
    public int? CodArea { get; set; }

    [Column("codColuna")]
    public int? CodColuna { get; set; }

    [Column("codLinha")]
    public int? CodLinha { get; set; }

    [Column("rotuloFonte")]
    [StringLength(50)]
    [Unicode(false)]
    public string RotuloFonte { get; set; }

    [Column("rotuloCorTexto")]
    [StringLength(50)]
    [Unicode(false)]
    public string RotuloCorTexto { get; set; }

    [Column("rotuloCorFundo")]
    [StringLength(50)]
    [Unicode(false)]
    public string RotuloCorFundo { get; set; }

    [Column("rotuloAlinhamento")]
    [StringLength(50)]
    [Unicode(false)]
    public string RotuloAlinhamento { get; set; }

    [Column("rotuloTexto")]
    [StringLength(50)]
    [Unicode(false)]
    public string RotuloTexto { get; set; }

    [Column("medidorCabecalho")]
    [StringLength(50)]
    [Unicode(false)]
    public string MedidorCabecalho { get; set; }

    [Column("medidorRodape")]
    [StringLength(50)]
    [Unicode(false)]
    public string MedidorRodape { get; set; }

    [Column("medidorEscalaMaior")]
    public double? MedidorEscalaMaior { get; set; }

    [Column("medidorEscalaMenor")]
    public double? MedidorEscalaMenor { get; set; }
}