// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("NomeColuna", "ValorColuna")]
[Microsoft.EntityFrameworkCore.Index("CodPerimetro", Name = "IX_MvtGeoPerimetroVinculo_codPerimetro")]
public partial class MvtGeoPerimetroVinculo
{
    [Key]
    [Column("nomeColuna")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeColuna { get; set; }

    [Key]
    [Column("valorColuna")]
    [StringLength(200)]
    [Unicode(false)]
    public string ValorColuna { get; set; }

    [Column("codPerimetro")]
    public int CodPerimetro { get; set; }
}
