// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodModelo", "CodIndicador")]
public partial class MvtGestaoDadoGerencialIndicador
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Key]
    [Column("codIndicador")]
    public int CodIndicador { get; set; }

    [Column("nomeIndicador")]
    [StringLength(300)]
    [Unicode(false)]
    public string NomeIndicador { get; set; }

    [Column("unidade")]
    [StringLength(50)]
    [Unicode(false)]
    public string Unidade { get; set; }

    [Column("formato")]
    [StringLength(50)]
    [Unicode(false)]
    public string Formato { get; set; }

    [Column("responsavel")]
    [StringLength(50)]
    [Unicode(false)]
    public string Responsavel { get; set; }

    [Column("perspectiva")]
    [StringLength(50)]
    [Unicode(false)]
    public string Perspectiva { get; set; }

    [Column("tipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("informacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Informacao { get; set; }

    [Column("totalizar")]
    [StringLength(50)]
    [Unicode(false)]
    public string Totalizar { get; set; }

    [Column("codIniciativa")]
    public int? CodIniciativa { get; set; }

    [Column("codObjetivo")]
    public int? CodObjetivo { get; set; }

    [Column("codAcao")]
    public int? CodAcao { get; set; }

    [Column("codArea")]
    public int? CodArea { get; set; }

    [Column("codNivel")]
    public int? CodNivel { get; set; }

    [Column("tipoCalculo")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoCalculo { get; set; }

    [Column("metodoEspecifico")]
    [StringLength(200)]
    [Unicode(false)]
    public string MetodoEspecifico { get; set; }

    [Column("visivel")]
    [StringLength(10)]
    [Unicode(false)]
    public string Visivel { get; set; }

    [Column("codContratoResultado")]
    public int? CodContratoResultado { get; set; }

    [Column("codIndicadorContrato")]
    public int? CodIndicadorContrato { get; set; }

    [Column("ordenacao")]
    public int? Ordenacao { get; set; }

    [Column("formula")]
    [StringLength(1000)]
    [Unicode(false)]
    public string Formula { get; set; }

    [Column("resultadoExercicio")]
    public int? ResultadoExercicio { get; set; }

    [Column("corFundo")]
    public int? CorFundo { get; set; }

    [Column("corTexto")]
    public int? CorTexto { get; set; }

    [Column("ruim")]
    public double? Ruim { get; set; }

    [Column("regular")]
    public double? Regular { get; set; }

    [Column("bom")]
    public double? Bom { get; set; }

    [Column("otimo")]
    public double? Otimo { get; set; }

    [Column("peso")]
    public double? Peso { get; set; }

    [Column("autorizadoPor")]
    [StringLength(50)]
    [Unicode(false)]
    public string AutorizadoPor { get; set; }

    [Column("justificativa")]
    [StringLength(200)]
    [Unicode(false)]
    public string Justificativa { get; set; }

    [Column("ambiente")]
    [StringLength(200)]
    [Unicode(false)]
    public string Ambiente { get; set; }

    [Column("metodo")]
    [StringLength(200)]
    [Unicode(false)]
    public string Metodo { get; set; }

    [Column("frequencia")]
    [StringLength(200)]
    [Unicode(false)]
    public string Frequencia { get; set; }

    [Column("quemUtiliza")]
    [StringLength(200)]
    [Unicode(false)]
    public string QuemUtiliza { get; set; }

    [Column("medida")]
    [StringLength(200)]
    [Unicode(false)]
    public string Medida { get; set; }

    [Column("idCalculo")]
    [StringLength(300)]
    [Unicode(false)]
    public string IdCalculo { get; set; }

    [Column("resultadoOrcVenda")]
    [StringLength(50)]
    [Unicode(false)]
    public string ResultadoOrcVenda { get; set; }

    [Column("inverteSinalRealizado")]
    public int? InverteSinalRealizado { get; set; }

    [Column("inverteSinalMeta")]
    public int? InverteSinalMeta { get; set; }

    [Column("codUnidadeNegocio")]
    public int? CodUnidadeNegocio { get; set; }

    [Column("codModeloBudget")]
    public int? CodModeloBudget { get; set; }

    [Column("codContaBudget")]
    public int? CodContaBudget { get; set; }

    [Column("colunaValorMatrizResultado")]
    [StringLength(50)]
    [Unicode(false)]
    public string ColunaValorMatrizResultado { get; set; }

    [Column("variacao")]
    public double? Variacao { get; set; }

    [Column("empresaPDI")]
    public int? EmpresaPdi { get; set; }

    [Column("codPlanoPDI")]
    public int? CodPlanoPdi { get; set; }

    [Column("codColaboradorPDI")]
    public int? CodColaboradorPdi { get; set; }

    [Column("idCompetenciaPDI")]
    [StringLength(10)]
    [Unicode(false)]
    public string IdCompetenciaPdi { get; set; }

    [Column("multiplicaResultado")]
    public int? MultiplicaResultado { get; set; }
}