// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Data", "Empresa", "EstabelecimentoNome", "ConsolidadoUnidNegocio", "ConsolidadoSegmento", "Canal", "ConsolidadoRegional", "ConsolidadoHistMacroRegiao", "ItemSegmItemCodigo", "ClienteCodigo")]
public partial class MvtGestaoDadoGerencialMatrizResultado
{
    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Column("ano")]
    public int? Ano { get; set; }

    [Column("mes")]
    [StringLength(10)]
    [Unicode(false)]
    public string Mes { get; set; }

    [Key]
    [Column("empresa")]
    [StringLength(100)]
    [Unicode(false)]
    public string Empresa { get; set; }

    [Key]
    [Column("estabelecimentoNome")]
    [StringLength(100)]
    [Unicode(false)]
    public string EstabelecimentoNome { get; set; }

    [Key]
    [Column("consolidadoUnidNegocio")]
    [StringLength(100)]
    [Unicode(false)]
    public string ConsolidadoUnidNegocio { get; set; }

    [Key]
    [Column("consolidadoSegmento")]
    [StringLength(100)]
    [Unicode(false)]
    public string ConsolidadoSegmento { get; set; }

    [Key]
    [Column("canal")]
    [StringLength(100)]
    [Unicode(false)]
    public string Canal { get; set; }

    [Key]
    [Column("consolidadoRegional")]
    [StringLength(100)]
    [Unicode(false)]
    public string ConsolidadoRegional { get; set; }

    [Key]
    [Column("consolidadoHistMacroRegiao")]
    [StringLength(100)]
    [Unicode(false)]
    public string ConsolidadoHistMacroRegiao { get; set; }

    [Column("itemSegmReferenciaCom")]
    [StringLength(100)]
    [Unicode(false)]
    public string ItemSegmReferenciaCom { get; set; }

    [Column("itemSegmGrupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string ItemSegmGrupo { get; set; }

    [Key]
    [Column("itemSegmItemCodigo")]
    public int ItemSegmItemCodigo { get; set; }

    [Column("itemSegmLinha")]
    [StringLength(100)]
    [Unicode(false)]
    public string ItemSegmLinha { get; set; }

    [Column("itemSegmReferencia")]
    [StringLength(100)]
    [Unicode(false)]
    public string ItemSegmReferencia { get; set; }

    [Key]
    [Column("clienteCodigo")]
    public int ClienteCodigo { get; set; }

    [Column("clienteNome")]
    [StringLength(100)]
    [Unicode(false)]
    public string ClienteNome { get; set; }

    [Column("clienteNomeAbreviado")]
    [StringLength(100)]
    [Unicode(false)]
    public string ClienteNomeAbreviado { get; set; }

    [Column("clienteAgrupadorEmitenteCod")]
    public int? ClienteAgrupadorEmitenteCod { get; set; }

    [Column("clienteCidade")]
    [StringLength(100)]
    [Unicode(false)]
    public string ClienteCidade { get; set; }

    [Column("clienteEstado")]
    [StringLength(100)]
    [Unicode(false)]
    public string ClienteEstado { get; set; }

    [Column("clientePais")]
    [StringLength(100)]
    [Unicode(false)]
    public string ClientePais { get; set; }

    [Column("quantidadeFaturadaUn")]
    public double? QuantidadeFaturadaUn { get; set; }

    [Column("quantidadeDevolvidaUn")]
    public double? QuantidadeDevolvidaUn { get; set; }

    [Column("valorTabela")]
    public double? ValorTabela { get; set; }

    [Column("valorPrecoMedioUnitarioVendas")]
    public double? ValorPrecoMedioUnitarioVendas { get; set; }

    [Column("percentualDesconto")]
    public double? PercentualDesconto { get; set; }

    [Column("valorReceitaBruta")]
    public double? ValorReceitaBruta { get; set; }

    [Column("valorDeducoes")]
    public double? ValorDeducoes { get; set; }

    [Column("valorDevolucao")]
    public double? ValorDevolucao { get; set; }

    [Column("percentualDevolucao")]
    public double? PercentualDevolucao { get; set; }

    [Column("valorFreteFaturado")]
    public double? ValorFreteFaturado { get; set; }

    [Column("valorImpostos")]
    public double? ValorImpostos { get; set; }

    [Column("valorIPI")]
    public double? ValorIpi { get; set; }

    [Column("valorICMSSubst")]
    public double? ValorIcmssubst { get; set; }

    [Column("valorICMS")]
    public double? ValorIcms { get; set; }

    [Column("valorPIS")]
    public double? ValorPis { get; set; }

    [Column("valorCOFINS")]
    public double? ValorCofins { get; set; }

    [Column("valorISS")]
    public double? ValorIss { get; set; }

    [Column("valorDescontoAbatimento")]
    public double? ValorDescontoAbatimento { get; set; }

    [Column("valorReceitaLiquida")]
    public double? ValorReceitaLiquida { get; set; }

    [Column("valorCustosVariaveis")]
    public double? ValorCustosVariaveis { get; set; }

    [Column("valorCustoInsumos")]
    public double? ValorCustoInsumos { get; set; }

    [Column("valorCustoMaterial")]
    public double? ValorCustoMaterial { get; set; }

    [Column("valorInventario")]
    public double? ValorInventario { get; set; }

    [Column("valorCustoMobGGFVar")]
    public double? ValorCustoMobGgfvar { get; set; }

    [Column("valorCustoBonificacao")]
    public double? ValorCustoBonificacao { get; set; }

    [Column("percentualBonificacao")]
    public double? PercentualBonificacao { get; set; }

    [Column("valorMargemInterCompanhia")]
    public double? ValorMargemInterCompanhia { get; set; }

    [Column("valorDespesasVariaveis")]
    public double? ValorDespesasVariaveis { get; set; }

    [Column("valorFrete")]
    public double? ValorFrete { get; set; }

    [Column("valorComissao")]
    public double? ValorComissao { get; set; }

    [Column("valorRoyalties")]
    public double? ValorRoyalties { get; set; }

    [Column("valorVerbasContratuaisVariaveis")]
    public double? ValorVerbasContratuaisVariaveis { get; set; }

    [Column("valorMargemContribuicao")]
    public double? ValorMargemContribuicao { get; set; }

    [Column("percentualMargemContribuicao")]
    public double? PercentualMargemContribuicao { get; set; }

    [Column("valorEBITRegional")]
    public double? ValorEbitregional { get; set; }

    [Column("percentualEBITRegional")]
    public double? PercentualEbitregional { get; set; }

    [Column("valorDespesasFixas")]
    public double? ValorDespesasFixas { get; set; }

    [Column("valorCustoFixoProd")]
    public double? ValorCustoFixoProd { get; set; }

    [Column("valorDFAdm")]
    public double? ValorDfadm { get; set; }

    [Column("valorDFRegional")]
    public double? ValorDfregional { get; set; }

    [Column("valorDFVerbasContr")]
    public double? ValorDfverbasContr { get; set; }

    [Column("valorDFMarketing")]
    public double? ValorDfmarketing { get; set; }

    [Column("valorDFComercias")]
    public double? ValorDfcomercias { get; set; }

    [Column("valorEBIT")]
    public double? ValorEbit { get; set; }

    [Column("percentualEBIT")]
    public double? PercentualEbit { get; set; }

    [Column("valorDepreciacaoAmortizacao")]
    public double? ValorDepreciacaoAmortizacao { get; set; }

    [Column("valorEBITDA")]
    public double? ValorEbitda { get; set; }

    [Column("percentualEBITDA")]
    public double? PercentualEbitda { get; set; }

    [Column("percentualPtoEquilibrio")]
    public double? PercentualPtoEquilibrio { get; set; }

    [Column("valorCPV")]
    public double? ValorCpv { get; set; }

    [Column("percentualCPV")]
    public double? PercentualCpv { get; set; }

    [Column("valorDesconto")]
    public double? ValorDesconto { get; set; }
}