// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "CodModelo", "CodConta", "CodDivisao", "Mercado", "Tipo", "DataProjecao", "Data")]
[Table("MvtGestaoDREDadosBI")]
public partial class MvtGestaoDredadosBi
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Key]
    [Column("codConta")]
    public int CodConta { get; set; }

    [Key]
    [Column("tipo")]
    [StringLength(10)]
    public string Tipo { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Column("valor")]
    public double Valor { get; set; }

    [Key]
    [Column("dataProjecao", TypeName = "date")]
    public DateTime DataProjecao { get; set; }

    [Key]
    [Column("codDivisao")]
    public int CodDivisao { get; set; }

    [Key]
    [Column("mercado")]
    [StringLength(10)]
    [Unicode(false)]
    public string Mercado { get; set; }
}