// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("IdSimulacao", "Sequencia")]
[Table("MvtGestaoDRESimulacaoPeriodos")]
public partial class MvtGestaoDresimulacaoPeriodos
{
    [Key]
    [Column("idSimulacao")]
    public int IdSimulacao { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Column("dataInicio", TypeName = "date")]
    public DateTime? DataInicio { get; set; }

    [Column("dataFim", TypeName = "date")]
    public DateTime? DataFim { get; set; }

    [Column("tipoBase")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoBase { get; set; }

    [Column("dataInicioBase", TypeName = "date")]
    public DateTime? DataInicioBase { get; set; }

    [Column("dataFimBase", TypeName = "date")]
    public DateTime? DataFimBase { get; set; }
}