// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Keyless]
public partial class MvtGestaoDadoGerencialModeloAtributo
{
    [Column("codEmpresa")]
    public int? CodEmpresa { get; set; }

    [Column("codModelo")]
    public int? CodModelo { get; set; }

    [Column("codAtributo")]
    public int? CodAtributo { get; set; }

    [Column("ordem")]
    public int? Ordem { get; set; }
}