// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtGestaoIndicadorBloqueio
{
    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Column("bloqueado")]
    public int? Bloqueado { get; set; }
}