// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodContrato")]
public partial class MvtGestaoIndicadorContrato
{
    [Key]
    [Column("codContrato")]
    public int CodContrato { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("codFuncionarioResponsavel")]
    public int CodFuncionarioResponsavel { get; set; }

    [Column("nome")]
    [StringLength(200)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("nomeResponsavel")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeResponsavel { get; set; }

    [Column("responsavel")]
    [StringLength(200)]
    [Unicode(false)]
    public string Responsavel { get; set; }

    [Column("tipoContrato")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoContrato { get; set; }
}