// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodUnidadeNegocio")]
public partial class MvtGestaoDadoGerencialUnidadeNegocio
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codUnidadeNegocio")]
    public int CodUnidadeNegocio { get; set; }

    [Column("nomeUnidadeNegocio")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeUnidadeNegocio { get; set; }

    [Column("ordenacao")]
    public int? Ordenacao { get; set; }

    [Column("corFundo")]
    public int? CorFundo { get; set; }

    [Column("corTexto")]
    public int? CorTexto { get; set; }
}