// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "IdSimulacao", "Sequencia", "Data")]
[Table("MvtGestaoDRESimulacaoOrcCustoMPValor")]
public partial class MvtGestaoDresimulacaoOrcCustoMpvalor
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("idSimulacao")]
    public int IdSimulacao { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Column("percentualAjuste")]
    public double? PercentualAjuste { get; set; }

    [Column("vlrCustoOrcOriginal")]
    public double? VlrCustoOrcOriginal { get; set; }

    [Column("vlrCustoOrcSimOrcVenda")]
    public double? VlrCustoOrcSimOrcVenda { get; set; }

    [Column("vlrCustoFinal")]
    public double? VlrCustoFinal { get; set; }
}