// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtGeoPerimetro
{
    [Key]
    [Column("codPerimetro")]
    public int CodPerimetro { get; set; }

    [Required]
    [Column("descricao")]
    [StringLength(200)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Required]
    [Column("dados")]
    [Unicode(false)]
    public string Dados { get; set; }
}