// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Table("MvtGestaoDREImpressao")]
public partial class MvtGestaoDreimpressao
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Required]
    [Column("descricao")]
    [StringLength(200)]
    public string Descricao { get; set; }

    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Required]
    [Column("empresas")]
    [StringLength(50)]
    public string Empresas { get; set; }

    [Column("orcadoRealizado")]
    public int OrcadoRealizado { get; set; }

    [Column("analiseVertical")]
    public int AnaliseVertical { get; set; }

    [Column("analiseHorizontal")]
    public int AnaliseHorizontal { get; set; }

    [Column("realizadoPeriodoAnterior")]
    public int RealizadoPeriodoAnterior { get; set; }

    [Column("dividirMil")]
    public int DividirMil { get; set; }

    [Column("totalizar")]
    public int Totalizar { get; set; }

    [Required]
    [Column("tipo")]
    [StringLength(20)]
    public string Tipo { get; set; }

    [Column("ordem")]
    public int Ordem { get; set; }

    [Column("acumulado")]
    public int Acumulado { get; set; }

    [Column("expandir")]
    public int Expandir { get; set; }

    [Column("mostrarFormulas")]
    public int MostrarFormulas { get; set; }

    [Column("projecaoBaseZero")]
    public int ProjecaoBaseZero { get; set; }
}