// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodConta", "CodEmpresa", "CodModelo", "Data", "TipoResultado", "NumeroOrcamento")]
[Table("MvtGestaoDREResultadoManual")]
public partial class MvtGestaoDreresultadoManual
{
    [Key]
    [Column("codConta")]
    public int CodConta { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Column("percentual")]
    public int? Percentual { get; set; }

    [Key]
    [Column("tipoResultado")]
    public int TipoResultado { get; set; }

    [Column("valor")]
    public double? Valor { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }
}