// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Id", "Sequencia")]
[Table("MvtGestaoDREConsultaSalvaControle")]
public partial class MvtGestaoDreconsultaSalvaControle
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Column("nomeObjeto")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeObjeto { get; set; }

    [Column("tipoObjeto")]
    [StringLength(150)]
    [Unicode(false)]
    public string TipoObjeto { get; set; }

    [Column("valorObjeto")]
    [StringLength(150)]
    [Unicode(false)]
    public string ValorObjeto { get; set; }

    [Column("paiObjeto")]
    [StringLength(150)]
    [Unicode(false)]
    public string PaiObjeto { get; set; }
}