// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodArea")]
public partial class MvtGestaoDadoGerencialArea
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codArea")]
    public int CodArea { get; set; }

    [Column("nomeArea")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeArea { get; set; }

    [Column("ordenacao")]
    public int? Ordenacao { get; set; }

    [Column("corFundo")]
    public int? CorFundo { get; set; }

    [Column("corTexto")]
    public int? CorTexto { get; set; }

    [Column("responsavel")]
    [StringLength(50)]
    [Unicode(false)]
    public string Responsavel { get; set; }

    [Column("codAreaPai")]
    public int? CodAreaPai { get; set; }
}