// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Data", "Identificador")]
public partial class MvtGestaoAnaliseCausaEfeito
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("identificador")]
    [StringLength(50)]
    [Unicode(false)]
    public string Identificador { get; set; }

    [Column("maoObra")]
    [StringLength(250)]
    [Unicode(false)]
    public string MaoObra { get; set; }

    [Column("maquina")]
    [StringLength(250)]
    [Unicode(false)]
    public string Maquina { get; set; }

    [Column("meioAmbiente")]
    [StringLength(250)]
    [Unicode(false)]
    public string MeioAmbiente { get; set; }

    [Column("medicao")]
    [StringLength(250)]
    [Unicode(false)]
    public string Medicao { get; set; }

    [Column("metodo")]
    [StringLength(250)]
    [Unicode(false)]
    public string Metodo { get; set; }

    [Column("material")]
    [StringLength(250)]
    [Unicode(false)]
    public string Material { get; set; }

    [Column("efeito")]
    [StringLength(250)]
    [Unicode(false)]
    public string Efeito { get; set; }
}