// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Ano", "CodContrato", "CodIndicador", "CodModeloGerencial", "CodIndicadorGerencial")]
public partial class MvtGestaoIndicadorContratoIndGer
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("codContrato")]
    public int CodContrato { get; set; }

    [Key]
    [Column("codIndicador")]
    public int CodIndicador { get; set; }

    [Key]
    [Column("codModeloGerencial")]
    public int CodModeloGerencial { get; set; }

    [Key]
    [Column("codIndicadorGerencial")]
    public int CodIndicadorGerencial { get; set; }
}