// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEstrutura", "CodTipo")]
public partial class MvtGeoEstruturaTipo
{
    [Key]
    [Column("codEstrutura")]
    public int CodEstrutura { get; set; }

    [Key]
    [Column("codTipo")]
    public int CodTipo { get; set; }
}