// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "Origem", "Nome")]
public partial class MvtGestaoDadoGerencialVisaoItem
{
    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Key]
    [Column("origem")]
    [StringLength(50)]
    [Unicode(false)]
    public string Origem { get; set; }

    [Key]
    [Column("nome")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("valor")]
    [Unicode(false)]
    public string Valor { get; set; }
}