// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodContrato", "CodIndicador", "Data")]
public partial class MvtGestaoIndicadorContratoResu
{
    [Column("ano")]
    public int? Ano { get; set; }

    [Key]
    [Column("codContrato")]
    public int CodContrato { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codIndicador")]
    public double CodIndicador { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Column("pesoMeta")]
    public double? PesoMeta { get; set; }

    [Column("pesoMetaAcumulado")]
    public double? PesoMetaAcumulado { get; set; }

    [Column("pesoRealizado")]
    public double? PesoRealizado { get; set; }

    [Column("pesoRealizadoAcumulado")]
    public double? PesoRealizadoAcumulado { get; set; }

    [Column("pesoRealizadoAcumuladoauto")]
    public double? PesoRealizadoAcumuladoauto { get; set; }

    [Column("pesoRealizadoAutomatico")]
    public double? PesoRealizadoAutomatico { get; set; }

    [Column("tipoIndicador")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoIndicador { get; set; }

    [Column("tipoResultadoIndicador")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoResultadoIndicador { get; set; }

    [Column("valorMeta")]
    public double? ValorMeta { get; set; }

    [Column("valorMetaAcumulado")]
    public double? ValorMetaAcumulado { get; set; }

    [Column("valorMetaAcumuladoauto")]
    public double? ValorMetaAcumuladoauto { get; set; }

    [Column("valorRealizado")]
    public double? ValorRealizado { get; set; }

    [Column("valorRealizadoAcumulado")]
    public double? ValorRealizadoAcumulado { get; set; }

    [Column("valorRealizadoAcumuladoauto")]
    public double? ValorRealizadoAcumuladoauto { get; set; }

    [Column("valorRealizadoAutomatico")]
    public double? ValorRealizadoAutomatico { get; set; }
}