// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtGestaoPainelVisao
{
    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Column("descricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("usuarioCriacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioCriacao { get; set; }

    [Column("dataHoraCriacao", TypeName = "datetime")]
    public DateTime? DataHoraCriacao { get; set; }
}