// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[Table("MvtGestaoDREModelos")]
public partial class MvtGestaoDremodelos
{
    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Column("nomeModelo")]
    [StringLength(50)]
    public string NomeModelo { get; set; }

    [Column("fluxoCaixa")]
    public int? FluxoCaixa { get; set; }

    [Column("analiseRentabilidade")]
    public int AnaliseRentabilidade { get; set; }

    [Column("consideraAjusteGerencial")]
    public int? ConsideraAjusteGerencial { get; set; }

    [Column("empresas")]
    [StringLength(50)]
    [Unicode(false)]
    public string Empresas { get; set; }

    [Column("administradores")]
    [StringLength(500)]
    [Unicode(false)]
    public string Administradores { get; set; }

    [Column("corFonteAnalise")]
    public int? CorFonteAnalise { get; set; }

    [Column("corFundoAnalise")]
    public int? CorFundoAnalise { get; set; }

    [Column("estiloAnaliseEspecifico")]
    public bool? EstiloAnaliseEspecifico { get; set; }

    [Column("consideraTransferenciaCPV")]
    public bool? ConsideraTransferenciaCpv { get; set; }
}