// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "IdSimulacao", "Sequencia")]
[Table("MvtGestaoDRESimulacaoOrcCustoMP")]
public partial class MvtGestaoDresimulacaoOrcCustoMp
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("idSimulacao")]
    public int IdSimulacao { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Column("familia")]
    [StringLength(150)]
    [Unicode(false)]
    public string Familia { get; set; }

    [Column("percentualRepresentatividade")]
    public double? PercentualRepresentatividade { get; set; }

    [Column("aumentoOriginalOrcamento")]
    public double? AumentoOriginalOrcamento { get; set; }
}