// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodContrato", "CodIndicador", "Ano")]
public partial class MvtGestaoIndicadorContratoInd
{
    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("codContrato")]
    public int CodContrato { get; set; }

    [Column("codContratoIndicadorIgual")]
    public int? CodContratoIndicadorIgual { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codIndicador")]
    public double CodIndicador { get; set; }

    [Column("codIndicadorIgual")]
    public double? CodIndicadorIgual { get; set; }

    [Column("nomeContrato")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeContrato { get; set; }

    [Column("nomeIndicador")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeIndicador { get; set; }

    [Column("perspectivaIndicador")]
    [StringLength(50)]
    [Unicode(false)]
    public string PerspectivaIndicador { get; set; }

    [Column("resultado")]
    [StringLength(50)]
    [Unicode(false)]
    public string Resultado { get; set; }

    [Column("tipoCalculo")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoCalculo { get; set; }

    [Column("tipoIndicador")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoIndicador { get; set; }

    [Column("unidadeIndicador")]
    [StringLength(50)]
    [Unicode(false)]
    public string UnidadeIndicador { get; set; }

    [Column("codEmpresaIndicadorIgual")]
    public int? CodEmpresaIndicadorIgual { get; set; }

    [Column("ordemIndicador")]
    public int? OrdemIndicador { get; set; }

    [Column("inverteSinal")]
    public int? InverteSinal { get; set; }
}