// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodModelo", "CodIndicador", "CodCentroCusto", "CodContaContabil")]
[Table("MvtGestaoDadoGerencialIndicadorCCusto")]
public partial class MvtGestaoDadoGerencialIndicadorCcusto
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Key]
    [Column("codIndicador")]
    public int CodIndicador { get; set; }

    [Key]
    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Key]
    [Column("codContaContabil")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaContabil { get; set; }

    [Column("codCentroCustoFim")]
    public int? CodCentroCustoFim { get; set; }

    [Column("codContaContabilFim")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaContabilFim { get; set; }
}