// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodModelo", "Usuario")]
[Table("MvtGestaoDRECfgLiberacaoModelo")]
public partial class MvtGestaoDrecfgLiberacaoModelo
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Key]
    [Column("usuario")]
    [StringLength(50)]
    public string Usuario { get; set; }

    [Column("dataLiberacao", TypeName = "date")]
    public DateTime? DataLiberacao { get; set; }
}