// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodModelo", "Data", "CodIndicador")]
public partial class MvtGestaoDadoGerencialRealizado
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("codIndicador")]
    public int CodIndicador { get; set; }

    [Column("valorRealizado")]
    public double? ValorRealizado { get; set; }

    [Column("valorRealizadoAcumulado")]
    public double? ValorRealizadoAcumulado { get; set; }

    [Column("usuarioResponsavel")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioResponsavel { get; set; }

    [Column("atingimentoRuim")]
    public double? AtingimentoRuim { get; set; }

    [Column("atingimentoRegular")]
    public double? AtingimentoRegular { get; set; }

    [Column("atingimentoBom")]
    public double? AtingimentoBom { get; set; }

    [Column("atingimentoOtimo")]
    public double? AtingimentoOtimo { get; set; }
}