// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("IdSimulacao", "CodCampo")]
[Table("MvtGestaoDRESimulacaoCampoOrcVenda")]
public partial class MvtGestaoDresimulacaoCampoOrcVenda
{
    [Key]
    [Column("idSimulacao")]
    public int IdSimulacao { get; set; }

    [Key]
    [Column("codCampo")]
    public int CodCampo { get; set; }
}