// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Ano", "CodContrato", "CodIndicador", "CodCentroCusto", "CodContaContabil")]
[Table("MvtGestaoIndicadorContratoDespCC")]
public partial class MvtGestaoIndicadorContratoDespCc
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("codContrato")]
    public int CodContrato { get; set; }

    [Key]
    [Column("codIndicador")]
    public int CodIndicador { get; set; }

    [Key]
    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Column("nomeCentroCusto")]
    [StringLength(25)]
    [Unicode(false)]
    public string NomeCentroCusto { get; set; }

    [Key]
    [Column("codContaContabil")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaContabil { get; set; }

    [Column("nomeContaContabil")]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeContaContabil { get; set; }
}