// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodAnexo", "CodIdentificador", "NomeAnexo")]
[Table("MvtGestaoDRESimulacaoAnexo")]
public partial class MvtGestaoDresimulacaoAnexo
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codAnexo")]
    public int CodAnexo { get; set; }

    [Key]
    [Column("codIdentificador")]
    [StringLength(50)]
    [Unicode(false)]
    public string CodIdentificador { get; set; }

    [Key]
    [Column("nomeAnexo")]
    [StringLength(300)]
    [Unicode(false)]
    public string NomeAnexo { get; set; }

    [Column("nomeOriginal")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeOriginal { get; set; }

    [Column("usuario")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Column("dataRegistro", TypeName = "date")]
    public DateTime? DataRegistro { get; set; }

    [Column("dataModificacao", TypeName = "date")]
    public DateTime? DataModificacao { get; set; }

    [Column("dataExclusao", TypeName = "date")]
    public DateTime? DataExclusao { get; set; }

    [Column("usuarioExclusao")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioExclusao { get; set; }

    [Column("situacao")]
    [StringLength(10)]
    [Unicode(false)]
    public string Situacao { get; set; }
}