// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("IdSimulacao", "CodModelo", "IdConta", "Sequencia")]
[Table("MvtGestaoDRESimulacaoCfgContasProporcao")]
public partial class MvtGestaoDresimulacaoCfgContasProporcao
{
    [Key]
    [Column("idSimulacao")]
    public int IdSimulacao { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Key]
    [Column("idConta")]
    [StringLength(150)]
    [Unicode(false)]
    public string IdConta { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Column("codModeloProp")]
    public int CodModeloProp { get; set; }

    [Column("codContaProp")]
    public int CodContaProp { get; set; }
}