// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("IdSimulacao", "EmpresaPrincipal")]
[Table("MvtGestaoDRESimulacaoSimOrcVenda")]
public partial class MvtGestaoDresimulacaoSimOrcVenda
{
    [Key]
    [Column("idSimulacao")]
    public int IdSimulacao { get; set; }

    [Key]
    [Column("empresaPrincipal")]
    public int EmpresaPrincipal { get; set; }

    [Column("codSimulacaoOrcVenda")]
    public int CodSimulacaoOrcVenda { get; set; }
}