// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "DataHoraAlteracao", "Identificador", "Sequencia", "SequenciaPlanoAcao")]
public partial class MvtGestaoAnaliseCausaPlanoAcaoHistorico
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("dataHoraAlteracao", TypeName = "datetime")]
    public DateTime DataHoraAlteracao { get; set; }

    [Key]
    [Column("identificador")]
    [StringLength(50)]
    [Unicode(false)]
    public string Identificador { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Key]
    [Column("sequenciaPlanoAcao")]
    public int SequenciaPlanoAcao { get; set; }

    [Column("usuarioAlteracao")]
    [StringLength(100)]
    [Unicode(false)]
    public string UsuarioAlteracao { get; set; }

    [Column("dataPrazoAnterior", TypeName = "date")]
    public DateTime? DataPrazoAnterior { get; set; }

    [Column("dataPrazo", TypeName = "date")]
    public DateTime? DataPrazo { get; set; }
}