// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("IdSimulacao", "CodModelo")]
[Table("MvtGestaoDRESimulacaoCenario")]
public partial class MvtGestaoDresimulacaoCenario
{
    [Key]
    [Column("idSimulacao")]
    public int IdSimulacao { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Column("tipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("numeroOrcamento")]
    public int? NumeroOrcamento { get; set; }

    [Column("dataInicioProjecao", TypeName = "date")]
    public DateTime? DataInicioProjecao { get; set; }

    [Column("anoAnterior")]
    public int? AnoAnterior { get; set; }

    [Column("colMeses")]
    [StringLength(50)]
    [Unicode(false)]
    public string ColMeses { get; set; }

    [Column("mostrarTotal")]
    public int? MostrarTotal { get; set; }

    [Column("avMes")]
    public int? AvMes { get; set; }

    [Column("ahMes")]
    public int? AhMes { get; set; }

    [Column("difMes")]
    public int? DifMes { get; set; }

    [Column("avTotal")]
    public int? AvTotal { get; set; }

    [Column("ahTotal")]
    public int? AhTotal { get; set; }

    [Column("difTotal")]
    public int? DifTotal { get; set; }

    [Column("codConfigBase")]
    public int? CodConfigBase { get; set; }
}