// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodModelo", "CodConta")]
[Table("MvtGestaoDREContas")]
public partial class MvtGestaoDrecontas
{
    [Column("baseAnaliseVertical")]
    public int? BaseAnaliseVertical { get; set; }

    [Column("camposConsultaProjecao")]
    [StringLength(150)]
    public string CamposConsultaProjecao { get; set; }

    [Column("classeConsultaProjecao")]
    [StringLength(150)]
    public string ClasseConsultaProjecao { get; set; }

    [Key]
    [Column("codConta")]
    public int CodConta { get; set; }

    [Column("codContaAgrupadora")]
    public int? CodContaAgrupadora { get; set; }

    [Column("codContaBase")]
    public int? CodContaBase { get; set; }

    [Column("codContaBaseProjecao")]
    public int? CodContaBaseProjecao { get; set; }

    [Column("codEmpresaBase")]
    public int? CodEmpresaBase { get; set; }

    [Column("codIndicadorPrazoMedio")]
    [StringLength(50)]
    public string CodIndicadorPrazoMedio { get; set; }

    [Key]
    [Column("codModelo")]
    public int CodModelo { get; set; }

    [Column("corFundo")]
    public double? CorFundo { get; set; }

    [Column("corTexto")]
    public double? CorTexto { get; set; }

    [Column("detalhaCentroCusto")]
    public int? DetalhaCentroCusto { get; set; }

    [Column("divideDiretoIndireto")]
    public int? DivideDiretoIndireto { get; set; }

    [Column("expandir")]
    public int? Expandir { get; set; }

    [Column("fonteNegrito")]
    public int? FonteNegrito { get; set; }

    [Column("inverterSinal")]
    public int? InverterSinal { get; set; }

    [Column("inverterSinalProjecao")]
    public int? InverterSinalProjecao { get; set; }

    [Column("mercado")]
    [StringLength(50)]
    public string Mercado { get; set; }

    [Column("naoAceitaNegativo")]
    public int? NaoAceitaNegativo { get; set; }

    [Column("nomeConta")]
    [StringLength(150)]
    public string NomeConta { get; set; }

    [Column("ordem")]
    public double? Ordem { get; set; }

    [Column("ordenacaoGeral")]
    public int? OrdenacaoGeral { get; set; }

    [Column("outrosFiltrosConsultaProjecao")]
    [StringLength(150)]
    public string OutrosFiltrosConsultaProjecao { get; set; }

    [Column("percRateio")]
    public double? PercRateio { get; set; }

    [Column("percentual")]
    public int? Percentual { get; set; }

    [Column("superIntendencia")]
    [StringLength(50)]
    public string SuperIntendencia { get; set; }

    [Column("tipoCalculo")]
    [StringLength(50)]
    public string TipoCalculo { get; set; }

    [Column("tipoContaSalario")]
    public int? TipoContaSalario { get; set; }

    [Column("tipoProjecao")]
    [StringLength(50)]
    public string TipoProjecao { get; set; }

    [Column("tipoSaldo")]
    public int? TipoSaldo { get; set; }

    [Column("tipoTotalizacao")]
    public int? TipoTotalizacao { get; set; }

    [Column("totaliza")]
    public int? Totaliza { get; set; }

    [Column("valorRef")]
    public int? ValorRef { get; set; }

    [Column("invisivel")]
    public int? Invisivel { get; set; }

    [Column("naoTotalizar")]
    public int? NaoTotalizar { get; set; }

    [Column("casasDecimais")]
    public int? CasasDecimais { get; set; }

    [Column("mesAnterior")]
    public int MesAnterior { get; set; }

    [Column("operacao")]
    [StringLength(1)]
    public string Operacao { get; set; }

    [Column("valorOperacao")]
    public double? ValorOperacao { get; set; }

    [Column("descricao")]
    [StringLength(100)]
    public string Descricao { get; set; }

    [Column("acumula")]
    public int? Acumula { get; set; }

    [Required]
    [Column("permissao")]
    [StringLength(500)]
    public string Permissao { get; set; }

    [Column("tipoEspecifico")]
    [StringLength(50)]
    public string TipoEspecifico { get; set; }

    [Column("acumulaValorOperacao")]
    public int? AcumulaValorOperacao { get; set; }

    [Column("tipoAcumuloFormula")]
    public int? TipoAcumuloFormula { get; set; }

    [Column("carregaRentDivisao")]
    public int? CarregaRentDivisao { get; set; }

    [Column("calculoFormulaColTotal")]
    public int? CalculoFormulaColTotal { get; set; }

    [Column("filtraDivisao")]
    public int? FiltraDivisao { get; set; }

    [Column("acumuladoFinalPeriodo")]
    public int? AcumuladoFinalPeriodo { get; set; }

    [Column("numCasasDecimais")]
    public int? NumCasasDecimais { get; set; }

    [Column("consideraTipoTotalizacao")]
    public int? ConsideraTipoTotalizacao { get; set; }

    [Column("ocultarValores")]
    public int? OcultarValores { get; set; }

    [Column("casaDecimal")]
    public int? CasaDecimal { get; set; }

    [Column("operacaoTipo")]
    [StringLength(1)]
    [Unicode(false)]
    public string OperacaoTipo { get; set; }

    [Column("operacaoValor")]
    public double? OperacaoValor { get; set; }

    [Column("resultadoPeriodoAnterior")]
    public int? ResultadoPeriodoAnterior { get; set; }

    [Column("formula")]
    [StringLength(150)]
    [Unicode(false)]
    public string Formula { get; set; }

    [Column("checaBaseConversao")]
    public int? ChecaBaseConversao { get; set; }

    [Column("configPorFaixa")]
    public int? ConfigPorFaixa { get; set; }

    [Column("numCasaDecimal")]
    public double? NumCasaDecimal { get; set; }

    [Column("desconsiderarTransfCPV")]
    public bool? DesconsiderarTransfCpv { get; set; }
}