// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodSlide", "CodArea")]
public partial class MvtGestaoPainelVisaoArea
{
    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Key]
    [Column("codSlide")]
    public int CodSlide { get; set; }

    [Key]
    [Column("codArea")]
    public int CodArea { get; set; }

    [Column("descricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("codPai")]
    public int? CodPai { get; set; }

    [Column("codColuna")]
    public int? CodColuna { get; set; }

    [Column("codLinha")]
    public int? CodLinha { get; set; }
}