// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("NomeBotao", "NomeModulo")]
public partial class MvtMenuItem
{
    [Key]
    [Column("nomeModulo")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeModulo { get; set; }

    [Key]
    [Column("nomeBotao")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeBotao { get; set; }

    [Column("descricaoOpcao")]
    [StringLength(500)]
    [Unicode(false)]
    public string DescricaoOpcao { get; set; }

    [Column("nomeExibicao")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeExibicao { get; set; }

    [Column("menuPrincipal")]
    [StringLength(100)]
    [Unicode(false)]
    public string MenuPrincipal { get; set; }

    [Column("programa")]
    [StringLength(150)]
    [Unicode(false)]
    public string Programa { get; set; }

    [Column("tipo")]
    public int? Tipo { get; set; }

    [Column("sistema")]
    [StringLength(50)]
    [Unicode(false)]
    public string Sistema { get; set; }

    [Column("atalho")]
    [StringLength(50)]
    [Unicode(false)]
    public string Atalho { get; set; }

    [Column("visible")]
    public int? Visible { get; set; }

    [Column("abrecomfilho")]
    public int? Abrecomfilho { get; set; }
}