// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Sequencia", "TipoPermissaoExecucao", "UsuarioGrupo")]
public partial class MvtMenuAgendamentoPermissao
{
    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Key]
    [Column("tipoPermissaoExecucao")]
    public int TipoPermissaoExecucao { get; set; }

    [Key]
    [Column("usuarioGrupo")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioGrupo { get; set; }
}