// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Sequencia", "DataHoraFimLog")]
public partial class MvtMenuAgendamentoLog
{
    [Required]
    [Column("programa")]
    [StringLength(800)]
    [Unicode(false)]
    public string Programa { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Key]
    [Column("dataHoraFimLog", TypeName = "datetime")]
    public DateTime DataHoraFimLog { get; set; }

    [Column("dataHoraInicio", TypeName = "datetime")]
    public DateTime? DataHoraInicio { get; set; }

    [Column("tipoExecucao")]
    public int? TipoExecucao { get; set; }

    [Column("tipoRepeticao")]
    public int? TipoRepeticao { get; set; }

    [Column("intervaloRepeticao")]
    public int? IntervaloRepeticao { get; set; }

    [Column("usuarioAgendamento")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioAgendamento { get; set; }

    [Column("dataHoraAgendamento", TypeName = "datetime")]
    public DateTime? DataHoraAgendamento { get; set; }

    [Column("usuarioExecucao")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioExecucao { get; set; }

    [Column("nome")]
    [StringLength(800)]
    public string Nome { get; set; }
}