// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("NomeExecutavel", "NomeReferencia")]
public partial class MvtMenuItemReferencia
{
    [Key]
    [Column("nomeExecutavel")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeExecutavel { get; set; }

    [Key]
    [Column("nomeReferencia")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeReferencia { get; set; }
}