// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Sequencia", "DataHora")]
public partial class MvtMenuAgendamentoErro
{
    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Key]
    [Column("dataHora", TypeName = "datetime")]
    public DateTime DataHora { get; set; }

    [Column("erro")]
    [StringLength(8000)]
    [Unicode(false)]
    public string Erro { get; set; }

    [Column("progama")]
    [StringLength(8000)]
    [Unicode(false)]
    public string Progama { get; set; }
}