// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtMenuEmpresa
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("fantasia")]
    [StringLength(100)]
    [Unicode(false)]
    public string Fantasia { get; set; }

    [Column("cnpj")]
    public long? Cnpj { get; set; }

    [Column("inscricaoEstadual")]
    public long? InscricaoEstadual { get; set; }

    [Column("cep")]
    public int? Cep { get; set; }

    [Column("endereco")]
    [StringLength(100)]
    [Unicode(false)]
    public string Endereco { get; set; }

    [Column("bairro")]
    [StringLength(50)]
    [Unicode(false)]
    public string Bairro { get; set; }

    [Column("complemento")]
    [StringLength(100)]
    [Unicode(false)]
    public string Complemento { get; set; }

    [Column("cidade")]
    [StringLength(100)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [Column("codUF")]
    [StringLength(5)]
    [Unicode(false)]
    public string CodUf { get; set; }

    [Column("endCxPostal")]
    [StringLength(50)]
    [Unicode(false)]
    public string EndCxPostal { get; set; }

    [Column("endNumero")]
    public int? EndNumero { get; set; }

    [Column("codMunicipioIBGE")]
    public int? CodMunicipioIbge { get; set; }

    [Column("telefone")]
    [StringLength(50)]
    [Unicode(false)]
    public string Telefone { get; set; }

    [Column("codUFIBGE")]
    [StringLength(50)]
    [Unicode(false)]
    public string CodUfibge { get; set; }

    [Column("emailServidor")]
    [StringLength(100)]
    [Unicode(false)]
    public string EmailServidor { get; set; }

    [Column("emailAutenticacao")]
    [StringLength(150)]
    [Unicode(false)]
    public string EmailAutenticacao { get; set; }

    [Column("emailEndereco")]
    [StringLength(150)]
    [Unicode(false)]
    public string EmailEndereco { get; set; }

    [Column("emailSenha")]
    [StringLength(150)]
    [Unicode(false)]
    public string EmailSenha { get; set; }
}