// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("MaquinaUsuario", "Chave")]
public partial class MvtMenuLock
{
    [Key]
    [Column("maquinaUsuario")]
    [StringLength(500)]
    public string MaquinaUsuario { get; set; }

    [Key]
    [Column("chave")]
    [StringLength(500)]
    public string Chave { get; set; }

    [Column("dataHora", TypeName = "datetime")]
    public DateTime DataHora { get; set; }
}