// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtMenuAjuda
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Required]
    [Column("titulo")]
    [StringLength(200)]
    [Unicode(false)]
    public string Titulo { get; set; }

    [Required]
    [Column("url")]
    [StringLength(100)]
    [Unicode(false)]
    public string Url { get; set; }

    [Column("ordem")]
    public int Ordem { get; set; }
}