// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Pendencia", "Identificador")]
public partial class MvtMenuPendencia
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("dataAbertura", TypeName = "date")]
    public DateTime? DataAbertura { get; set; }

    [Column("dataBaixa", TypeName = "date")]
    public DateTime? DataBaixa { get; set; }

    [Column("dataDemonstracao", TypeName = "date")]
    public DateTime? DataDemonstracao { get; set; }

    [Column("descricao")]
    [StringLength(300)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("diasEmAberto")]
    public int? DiasEmAberto { get; set; }

    [Column("horaAbertura")]
    public TimeSpan? HoraAbertura { get; set; }

    [Column("horaBaixa")]
    public TimeSpan? HoraBaixa { get; set; }

    [Key]
    [Column("identificador")]
    [StringLength(30)]
    [Unicode(false)]
    public string Identificador { get; set; }

    [Column("imagem")]
    [StringLength(50)]
    [Unicode(false)]
    public string Imagem { get; set; }

    [Key]
    [Column("pendencia")]
    [StringLength(30)]
    [Unicode(false)]
    public string Pendencia { get; set; }

    [Column("prazo", TypeName = "date")]
    public DateTime? Prazo { get; set; }

    [Column("prioridadeGestor")]
    public int? PrioridadeGestor { get; set; }

    [Column("programa")]
    [StringLength(50)]
    [Unicode(false)]
    public string Programa { get; set; }

    [Column("situacao")]
    public int? Situacao { get; set; }

    [Column("titulo")]
    [StringLength(150)]
    [Unicode(false)]
    public string Titulo { get; set; }

    [Column("usuarioAbertura")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioAbertura { get; set; }

    [Column("usuariobaixa")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuariobaixa { get; set; }

    [Column("usuarioResponsavel")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioResponsavel { get; set; }
}