// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Ano", "NumeroOrcamento", "NomeConta")]
public partial class MvtOrcamentoConfigConta
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("nomeConta")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeConta { get; set; }

    [Column("codContaContabil")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaContabil { get; set; }

    [Column("nomeContaContabil")]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeContaContabil { get; set; }

    [Column("tipoCalculo")]
    [StringLength(100)]
    [Unicode(false)]
    public string TipoCalculo { get; set; }

    [Column("inverteSinal")]
    public int? InverteSinal { get; set; }

    [Column("taxaJuros")]
    public int? TaxaJuros { get; set; }

    [Column("tipoJuros")]
    public int? TipoJuros { get; set; }

    [Column("tipoSaldo")]
    public int? TipoSaldo { get; set; }

    [Column("periodoSaldo")]
    public int? PeriodoSaldo { get; set; }

    [Column("grupoContabilizacao")]
    public int? GrupoContabilizacao { get; set; }

    [Column("codContraPartida")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContraPartida { get; set; }

    [Column("geraFluxo")]
    public int? GeraFluxo { get; set; }

    [Column("tipoMovimento")]
    [StringLength(2)]
    [Unicode(false)]
    public string TipoMovimento { get; set; }

    [Column("percentualContabilizado")]
    public double? PercentualContabilizado { get; set; }

    [Column("codCentroCusto")]
    public int? CodCentroCusto { get; set; }
}