// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtOrcamentoConfigOrcDespesa
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("dataFinal", TypeName = "date")]
    public DateTime? DataFinal { get; set; }

    [Column("dataInicial", TypeName = "date")]
    public DateTime? DataInicial { get; set; }

    [Column("numeroOrcamento")]
    public int? NumeroOrcamento { get; set; }

    [Column("numeroOrcamentoElaboracao")]
    public int? NumeroOrcamentoElaboracao { get; set; }

    [Column("dataLimiteReal", TypeName = "date")]
    public DateTime? DataLimiteReal { get; set; }
}