// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "Ano", "Versao", "CodTabela", "CodProduto", "Grupo", "Subgrupo", "Linha", "CodRepresentante")]
public partial class MvtOrcamentoVendaTabPrecoItem
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("versao")]
    public int Versao { get; set; }

    [Key]
    [Column("codTabela")]
    public int CodTabela { get; set; }

    [Key]
    [Column("codProduto")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodProduto { get; set; }

    [Column("preco")]
    public double? Preco { get; set; }

    [Key]
    [Column("grupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string Grupo { get; set; }

    [Key]
    [Column("subgrupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string Subgrupo { get; set; }

    [Key]
    [Column("linha")]
    [StringLength(100)]
    [Unicode(false)]
    public string Linha { get; set; }

    [Key]
    [Column("codRepresentante")]
    public int CodRepresentante { get; set; }

    [Column("mesReferencia", TypeName = "date")]
    public DateTime? MesReferencia { get; set; }
}