// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Ano", "NumeroOrcamento", "NomeConta", "SeqRateio", "AnoMes")]
public partial class MvtOrcamentoConfigContaNatureza
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("nomeConta")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeConta { get; set; }

    [Key]
    [Column("seqRateio")]
    public int SeqRateio { get; set; }

    [Key]
    [Column("anoMes", TypeName = "date")]
    public DateTime AnoMes { get; set; }

    [Column("codNatureza")]
    [StringLength(30)]
    [Unicode(false)]
    public string CodNatureza { get; set; }

    [Column("codCentroCusto")]
    [StringLength(30)]
    [Unicode(false)]
    public string CodCentroCusto { get; set; }

    [Column("percentual")]
    public double? Percentual { get; set; }
}