// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "AnoOrcamento", "Sequencia")]
public partial class MvtOrcamentoCfgCtbGeralBaseLucroContas
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("anoOrcamento")]
    public int AnoOrcamento { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Column("tipo")]
    [StringLength(25)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("codContaContabil")]
    [StringLength(15)]
    [Unicode(false)]
    public string CodContaContabil { get; set; }
}