// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "Ano", "Versao", "CodTabela")]
public partial class MvtOrcamentoVendaTabPreco
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("versao")]
    public int Versao { get; set; }

    [Key]
    [Column("codTabela")]
    public int CodTabela { get; set; }

    [Column("descricao")]
    [StringLength(250)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("dataInicioPeriodo", TypeName = "date")]
    public DateTime? DataInicioPeriodo { get; set; }

    [Column("dataFimPeriodo", TypeName = "date")]
    public DateTime? DataFimPeriodo { get; set; }

    [Column("tabelaPadrao")]
    public int? TabelaPadrao { get; set; }
}