// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "AnoOrcamento", "Data", "Sequencia")]
public partial class MvtOrcamentoCfgCtbGeralAdicaoExclusao
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("anoOrcamento")]
    public int AnoOrcamento { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Column("descricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Required]
    [Column("tributo")]
    [StringLength(15)]
    [Unicode(false)]
    public string Tributo { get; set; }

    [Required]
    [Column("tipo")]
    [StringLength(15)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("diferido")]
    public bool Diferido { get; set; }

    [Column("valor")]
    public double? Valor { get; set; }
}