// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "AnoOrcamento", "Versao", "TipoCodigo", "CodigoDe", "CodigoPara", "CodigoItem")]
public partial class MvtOrcamentoVendaCfgConversaoItem
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("anoOrcamento")]
    public int AnoOrcamento { get; set; }

    [Key]
    [Column("versao")]
    public int Versao { get; set; }

    [Key]
    [Column("tipoCodigo")]
    [StringLength(20)]
    [Unicode(false)]
    public string TipoCodigo { get; set; }

    [Key]
    [Column("codigoDe")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodigoDe { get; set; }

    [Key]
    [Column("codigoPara")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodigoPara { get; set; }

    [Key]
    [Column("codigoItem")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodigoItem { get; set; }

    [Column("percentualConversao")]
    public double? PercentualConversao { get; set; }
}