// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "DesOrcamento")]
public partial class MvtOrcamentoOrcamentoLiberacao
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("desOrcamento")]
    [StringLength(150)]
    [Unicode(false)]
    public string DesOrcamento { get; set; }

    [Column("usuarios")]
    [StringLength(550)]
    [Unicode(false)]
    public string Usuarios { get; set; }

    [Column("dataLimite", TypeName = "date")]
    public DateTime? DataLimite { get; set; }
}