// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodSimulacao", "Sequencia", "CodCampo", "NomeCampo")]
public partial class MvtOrcamentoSimulacaoOrcVendaItemCampo
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codSimulacao")]
    public int CodSimulacao { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Key]
    [Column("codCampo")]
    public int CodCampo { get; set; }

    [Key]
    [Column("nomeCampo")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeCampo { get; set; }

    [Column("valorCampo")]
    [StringLength(300)]
    [Unicode(false)]
    public string ValorCampo { get; set; }
}