// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "AnoMes", "CodCentroCusto", "CodContaContabil")]
public partial class MvtOrcamentoOrcamentoDespesaJustifica
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("anoMes", TypeName = "date")]
    public DateTime AnoMes { get; set; }

    [Key]
    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Key]
    [Column("codContaContabil")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaContabil { get; set; }

    [Column("origem")]
    [StringLength(150)]
    [Unicode(false)]
    public string Origem { get; set; }

    [Column("motivo")]
    [StringLength(150)]
    [Unicode(false)]
    public string Motivo { get; set; }

    [Column("acao")]
    [StringLength(550)]
    [Unicode(false)]
    public string Acao { get; set; }

    [Column("dataInicio", TypeName = "date")]
    public DateTime? DataInicio { get; set; }

    [Column("dataFim", TypeName = "date")]
    public DateTime? DataFim { get; set; }
}