// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodContaContabil", "CodCentroCusto")]
public partial class MvtOrcamentoMatrizDespesaDireta
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codContaContabil")]
    public int CodContaContabil { get; set; }

    [Key]
    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Column("percRateioJan")]
    public double? PercRateioJan { get; set; }

    [Column("percRateioFev")]
    public double? PercRateioFev { get; set; }

    [Column("percRateioMar")]
    public double? PercRateioMar { get; set; }

    [Column("percRateioAbr")]
    public double? PercRateioAbr { get; set; }

    [Column("percRateioMai")]
    public double? PercRateioMai { get; set; }

    [Column("percRateioJun")]
    public double? PercRateioJun { get; set; }

    [Column("percRateioJul")]
    public double? PercRateioJul { get; set; }

    [Column("percRateioAgo")]
    public double? PercRateioAgo { get; set; }

    [Column("percRateioSet")]
    public double? PercRateioSet { get; set; }

    [Column("percRateioOut")]
    public double? PercRateioOut { get; set; }

    [Column("percRateioNov")]
    public double? PercRateioNov { get; set; }

    [Column("percRateioDez")]
    public double? PercRateioDez { get; set; }
}