// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodContaContabil")]
public partial class MvtOrcamentoContaControlada
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codContaContabil")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodContaContabil { get; set; }

    [Column("faturamento")]
    public int? Faturamento { get; set; }

    [Column("diasUteis")]
    public int? DiasUteis { get; set; }
}