// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "AnoOrcamento", "Versao", "Codigo")]
public partial class MvtOrcamentoVendaCfgInclusao
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("anoOrcamento")]
    public int AnoOrcamento { get; set; }

    [Key]
    [Column("versao")]
    public int Versao { get; set; }

    [Key]
    [Column("codigo")]
    [StringLength(20)]
    [Unicode(false)]
    public string Codigo { get; set; }

    [Column("codigoBase")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodigoBase { get; set; }

    [Column("mesInclusao", TypeName = "date")]
    public DateTime? MesInclusao { get; set; }

    [Column("volumeVendido")]
    public double? VolumeVendido { get; set; }

    [Column("todaVersao")]
    public int? TodaVersao { get; set; }

    [Column("preco")]
    public double? Preco { get; set; }
}