// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtOrcamentoNaturezaFinanceira
{
    [Key]
    [Column("codNatureza")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNatureza { get; set; }

    [Required]
    [Column("nomeNatureza")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeNatureza { get; set; }
}