// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "AnoOrcamento", "Versao", "Seq")]
public partial class MvtOrcamentoVendaHistAlteracao
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("anoOrcamento")]
    public int AnoOrcamento { get; set; }

    [Key]
    [Column("versao")]
    public int Versao { get; set; }

    [Column("data", TypeName = "date")]
    public DateTime? Data { get; set; }

    [Column("usuario")]
    [StringLength(150)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Key]
    [Column("seq")]
    public int Seq { get; set; }
}