// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento")]
public partial class MvtOrcamentoOrcamento
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("nomeOrcamento")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeOrcamento { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Column("codModeloOficialDRE")]
    public int? CodModeloOficialDre { get; set; }

    [Column("nivelOrcPessoa")]
    public int? NivelOrcPessoa { get; set; }
}