// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodSimulacao", "Sequencia", "Data")]
public partial class MvtOrcamentoSimulacaoOrcVendaItemValor
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codSimulacao")]
    public int CodSimulacao { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Column("qtdeBase")]
    public double? QtdeBase { get; set; }

    [Column("percAjusteQtde")]
    public double? PercAjusteQtde { get; set; }

    [Column("precoBase")]
    public double? PrecoBase { get; set; }

    [Column("percAjustePreco")]
    public double? PercAjustePreco { get; set; }

    [Column("custoUnitBase")]
    public double? CustoUnitBase { get; set; }
}