// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Ano", "NumeroOrcamento", "NomeConta", "NomeValor")]
public partial class MvtOrcamentoConfigContaValor
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("nomeConta")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeConta { get; set; }

    [Key]
    [Column("nomeValor")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeValor { get; set; }

    [Column("valor")]
    public double? Valor { get; set; }

    [Column("strValor")]
    [StringLength(50)]
    [Unicode(false)]
    public string StrValor { get; set; }
}