// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "Ano")]
public partial class MvtOrcamentoConfigJustificativaDespesa
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Column("acimaValor")]
    public double? AcimaValor { get; set; }

    [Column("acimaPercentual")]
    public double? AcimaPercentual { get; set; }

    [Column("percentualAtencao")]
    public double? PercentualAtencao { get; set; }
}