// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "AnoOrcamento", "EmpresaEquivalencia")]
public partial class MvtOrcamentoCfgCtbGeralEquivalencia
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("anoOrcamento")]
    public int AnoOrcamento { get; set; }

    [Key]
    [Column("empresaEquivalencia")]
    public int EmpresaEquivalencia { get; set; }

    [Column("codContaEquivalencia")]
    [StringLength(15)]
    [Unicode(false)]
    public string CodContaEquivalencia { get; set; }

    [Column("codContraPartida")]
    [StringLength(15)]
    [Unicode(false)]
    public string CodContraPartida { get; set; }
}