// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "Ano", "Versao", "CodTabela", "DataMes")]
public partial class MvtOrcamentoVendaTabPrecoMes
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("versao")]
    public int Versao { get; set; }

    [Key]
    [Column("codTabela")]
    public int CodTabela { get; set; }

    [Key]
    [Column("dataMes", TypeName = "date")]
    public DateTime DataMes { get; set; }
}