// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodInvestimento")]
public partial class MvtOrcamentoTipoInvestimento
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codInvestimento")]
    public int CodInvestimento { get; set; }

    [Required]
    [Column("nomeInvestimento")]
    [StringLength(50)]
    public string NomeInvestimento { get; set; }

    [Column("ifrs")]
    public double Ifrs { get; set; }

    [Column("societario")]
    public double Societario { get; set; }

    [Column("codContaContabil")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaContabil { get; set; }

    [Column("codContaDepreciacaoAdm")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaDepreciacaoAdm { get; set; }

    [Column("codContaDepreciacaoCml")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaDepreciacaoCml { get; set; }

    [Column("codContaDepreciacaoProd")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaDepreciacaoProd { get; set; }

    [Column("codContaDepreciacaoAcumulada")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaDepreciacaoAcumulada { get; set; }

    [Column("codContaCreditoPis")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaCreditoPis { get; set; }

    [Column("codContaCreditoCofins")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaCreditoCofins { get; set; }
}