// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodOrcamento", "Data", "CodMoeda")]
public partial class MvtOrcamentoCotacaoMoeda
{
    [Key]
    [Column("codOrcamento")]
    public int CodOrcamento { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("codMoeda")]
    public int CodMoeda { get; set; }

    [Column("valor")]
    public double? Valor { get; set; }
}