// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "AnoOrcamento")]
public partial class MvtOrcamentoCfgCtbGeral
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("anoOrcamento")]
    public int AnoOrcamento { get; set; }

    [Column("codMoedaOrcVenda")]
    public int CodMoedaOrcVenda { get; set; }

    [Required]
    [Column("codContaCaixa")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaCaixa { get; set; }

    [Column("codContaFinanciamentoCP")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaFinanciamentoCp { get; set; }

    [Column("codContaFinanciamentoLP")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaFinanciamentoLp { get; set; }

    [Column("codNaturezaCaptacao")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNaturezaCaptacao { get; set; }

    [Column("codNaturezaAmortizacao")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNaturezaAmortizacao { get; set; }

    [Column("codNaturezaJuros")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNaturezaJuros { get; set; }

    [Column("codContaDespFinanceira")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaDespFinanceira { get; set; }

    [Column("codContaVariacaoCambial")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaVariacaoCambial { get; set; }

    [Column("codContaFornecedor")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaFornecedor { get; set; }

    [Column("codContaAplicacao")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaAplicacao { get; set; }

    [Column("codNaturezaAplicacao")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNaturezaAplicacao { get; set; }

    [Column("codNaturezaResgate")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNaturezaResgate { get; set; }

    [Column("codRendimentoAplicacao")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodRendimentoAplicacao { get; set; }

    [Column("codContaEstoqueInicial")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaEstoqueInicial { get; set; }

    [Column("codContaEstoqueFinal")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaEstoqueFinal { get; set; }

    [Column("codContaLucro")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaLucro { get; set; }

    [Column("codContaProvisaoIR")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaProvisaoIr { get; set; }

    [Column("codContraPartidaProvisaoIR")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContraPartidaProvisaoIr { get; set; }

    [Column("codContaIRCompensar")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaIrcompensar { get; set; }

    [Column("codContaProvisaoCSLL")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaProvisaoCsll { get; set; }

    [Column("codContraPartidaProvisaoCSLL")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContraPartidaProvisaoCsll { get; set; }

    [Column("codContaCSLLCompensar")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaCsllcompensar { get; set; }

    [Column("codContaLucroAcumulado")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaLucroAcumulado { get; set; }

    [Column("codNaturezaInvestimento")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNaturezaInvestimento { get; set; }

    [Column("codNaturezaIR")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNaturezaIr { get; set; }

    [Column("codNaturezaCsll")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNaturezaCsll { get; set; }

    [Column("possuiEquivalencia")]
    public int? PossuiEquivalencia { get; set; }

    [Column("empresasEquivalencia")]
    [StringLength(150)]
    [Unicode(false)]
    public string EmpresasEquivalencia { get; set; }

    [Column("lucroReal")]
    public int? LucroReal { get; set; }

    [Column("dataLimiteFinanciamento", TypeName = "date")]
    public DateTime? DataLimiteFinanciamento { get; set; }

    [Column("codContaIRDiferido")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaIrdiferido { get; set; }

    [Column("codContraPartidaIRDiferido")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContraPartidaIrdiferido { get; set; }

    [Column("codContaCSLLDiferido")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaCslldiferido { get; set; }

    [Column("codContraPartidaCSLLDiferido")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContraPartidaCslldiferido { get; set; }

    [Column("prejuizoCompensavel")]
    public double? PrejuizoCompensavel { get; set; }

    [Column("codNatCaptacaoInvest")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNatCaptacaoInvest { get; set; }

    [Column("codNatAmortizacaoInvest")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNatAmortizacaoInvest { get; set; }

    [Column("codNatJurosInvest")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodNatJurosInvest { get; set; }

    [Column("codContaAntecipForn")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaAntecipForn { get; set; }

    [Column("mesBaseEstoque", TypeName = "date")]
    public DateTime? MesBaseEstoque { get; set; }

    [Column("naturezaEstoqueBase")]
    public int? NaturezaEstoqueBase { get; set; }
}