// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtOrcamentoGestorOrcamento
{
    [Key]
    [Column("usuarioGestor")]
    [StringLength(100)]
    [Unicode(false)]
    public string UsuarioGestor { get; set; }

    [Column("modulo")]
    [StringLength(200)]
    [Unicode(false)]
    public string Modulo { get; set; }
}