// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodSimulacao")]
public partial class MvtOrcamentoSimulacaoOrcVenda
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codSimulacao")]
    public int CodSimulacao { get; set; }

    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Column("versao")]
    public int Versao { get; set; }

    [Column("dataInicio", TypeName = "date")]
    public DateTime? DataInicio { get; set; }

    [Column("datafim", TypeName = "date")]
    public DateTime? Datafim { get; set; }
}