// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtOrcamentoConfigContaSalario
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Required]
    [Column("codContaContabil")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaContabil { get; set; }

    [Column("codCentroCusto")]
    public int? CodCentroCusto { get; set; }

    [Column("codCargo")]
    public int? CodCargo { get; set; }

    [Column("codFuncionario")]
    public int? CodFuncionario { get; set; }

    [Column("salarioDe")]
    public double? SalarioDe { get; set; }

    [Column("salarioAte")]
    public double? SalarioAte { get; set; }

    [Column("tipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("tipoConta")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoConta { get; set; }

    [Column("percentual")]
    public double? Percentual { get; set; }
}