// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "DataProjecao", "CodCentroCusto", "CodContaContabil", "SeqDespesa")]
public partial class MvtOrcamentoOrcamentoDespesaDetalha
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("dataProjecao", TypeName = "date")]
    public DateTime DataProjecao { get; set; }

    [Key]
    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Key]
    [Column("codContaContabil")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaContabil { get; set; }

    [Key]
    [Column("seqDespesa")]
    public int SeqDespesa { get; set; }

    [Column("nomeDespesa")]
    [StringLength(250)]
    [Unicode(false)]
    public string NomeDespesa { get; set; }

    [Column("valor")]
    public double? Valor { get; set; }

    [Column("valorOriginal")]
    public double? ValorOriginal { get; set; }

    [Column("tipoConta")]
    [StringLength(20)]
    [Unicode(false)]
    public string TipoConta { get; set; }

    [Column("nomeCentroCusto")]
    [StringLength(25)]
    [Unicode(false)]
    public string NomeCentroCusto { get; set; }

    [Column("nomeContaContabil")]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeContaContabil { get; set; }
}