// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtOrcamentoVenda
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("nomeEmpresa")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeEmpresa { get; set; }

    [Column("versao")]
    public int? Versao { get; set; }

    [Column("data", TypeName = "date")]
    public DateTime? Data { get; set; }

    [Column("segmento")]
    [StringLength(200)]
    [Unicode(false)]
    public string Segmento { get; set; }

    [Column("mercado")]
    [StringLength(200)]
    [Unicode(false)]
    public string Mercado { get; set; }

    [Column("quantidade")]
    public double? Quantidade { get; set; }

    [Column("valorTotal")]
    public double? ValorTotal { get; set; }

    [Column("operacao")]
    public int? Operacao { get; set; }

    [Column("numeroOrcamento")]
    public int? NumeroOrcamento { get; set; }

    [Column("anoOrcamento")]
    public int? AnoOrcamento { get; set; }

    [Column("grupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string Grupo { get; set; }

    [Column("subGrupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string SubGrupo { get; set; }

    [Column("codRepresentante")]
    public int? CodRepresentante { get; set; }

    [Column("linha")]
    [StringLength(100)]
    [Unicode(false)]
    public string Linha { get; set; }

    [Column("regiaoCobertura")]
    [StringLength(200)]
    [Unicode(false)]
    public string RegiaoCobertura { get; set; }

    [Column("nomeRepresentante")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeRepresentante { get; set; }

    [Column("status")]
    public int? Status { get; set; }

    [Column("usuarioAlteracao")]
    [StringLength(100)]
    [Unicode(false)]
    public string UsuarioAlteracao { get; set; }

    [Column("dataAlteracao", TypeName = "date")]
    public DateTime? DataAlteracao { get; set; }

    [Column("vlrUnitario")]
    public double? VlrUnitario { get; set; }

    [Column("codProduto")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodProduto { get; set; }

    [Column("estado")]
    [StringLength(5)]
    [Unicode(false)]
    public string Estado { get; set; }

    [Column("codRepresentanteAtual")]
    public int? CodRepresentanteAtual { get; set; }

    [Column("nomeRepresentanteAtual")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeRepresentanteAtual { get; set; }
}