// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("NumeroOrcamento", "AnoOrcamento", "CodEmpresa")]
public partial class MvtOrcamentoConfigVenda
{
    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("anoOrcamento")]
    public int AnoOrcamento { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("tipo")]
    [StringLength(20)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("campoCalculado")]
    [StringLength(20)]
    [Unicode(false)]
    public string CampoCalculado { get; set; }
}