// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Ano", "NumeroOrcamento", "CodGrupo", "Sequencia")]
public partial class MvtOrcamentoGrupoContabilizacaoItem
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("codGrupo")]
    public int CodGrupo { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Required]
    [Column("codContaDebito")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaDebito { get; set; }

    [Required]
    [Column("codContaCredito")]
    [StringLength(10)]
    [Unicode(false)]
    public string CodContaCredito { get; set; }

    [Column("nomeContaDebito")]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeContaDebito { get; set; }

    [Column("nomeContaCredito")]
    [StringLength(255)]
    [Unicode(false)]
    public string NomeContaCredito { get; set; }

    [Column("percentual")]
    public double? Percentual { get; set; }

    [Column("sequenciaBase")]
    public int? SequenciaBase { get; set; }

    [Column("geraFluxo")]
    public int? GeraFluxo { get; set; }
}