// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodContaContabil", "CodCentroCusto", "Data")]
public partial class MvtOrcamentoMatDespesaDireta
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codContaContabil")]
    public int CodContaContabil { get; set; }

    [Key]
    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Column("percRateio")]
    public double? PercRateio { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }
}