// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "Ano", "CodProduto", "Data")]
public partial class MvtOrcamentoCustoProduto
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("codProduto")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodProduto { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Column("vlrCustoMatPrima")]
    public double? VlrCustoMatPrima { get; set; }

    [Column("vlrCustoMaoObra")]
    public double? VlrCustoMaoObra { get; set; }

    [Column("vlrMargemMatPrima")]
    public double? VlrMargemMatPrima { get; set; }
}