// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Ano", "Versao")]
public partial class MvtOrcamentoVendaVersaoTeste
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("ano")]
    public int Ano { get; set; }

    [Key]
    [Column("versao")]
    public int Versao { get; set; }

    [Column("descricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("descricaoCompleta")]
    [StringLength(1000)]
    [Unicode(false)]
    public string DescricaoCompleta { get; set; }

    [Column("oficial")]
    public int? Oficial { get; set; }

    [Column("usadoHistVenda")]
    public int? UsadoHistVenda { get; set; }

    [Column("dataInicioHist", TypeName = "date")]
    public DateTime? DataInicioHist { get; set; }

    [Column("dataFimHist", TypeName = "date")]
    public DateTime? DataFimHist { get; set; }

    [Column("usadoOrcamento")]
    public int? UsadoOrcamento { get; set; }

    [Column("anoOrcamentoBase")]
    public int? AnoOrcamentoBase { get; set; }

    [Column("versaoOrcamentoBase")]
    public int? VersaoOrcamentoBase { get; set; }

    [Column("dataInicioOrcamento", TypeName = "date")]
    public DateTime? DataInicioOrcamento { get; set; }

    [Column("dataFimOrcamento", TypeName = "date")]
    public DateTime? DataFimOrcamento { get; set; }

    [Column("dadosGerados")]
    public int? DadosGerados { get; set; }

    [Column("situacao")]
    public int? Situacao { get; set; }

    [Column("usuarioGeracao")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioGeracao { get; set; }

    [Column("addAnosHist")]
    public int? AddAnosHist { get; set; }

    [Column("addAnosOrc")]
    public int? AddAnosOrc { get; set; }
}