// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtOrcamentoCfgCtbGeralFilial
{
    [Key]
    [Column("codEmpresaFilial")]
    public int CodEmpresaFilial { get; set; }

    [Column("codEmpresaMatriz")]
    public int? CodEmpresaMatriz { get; set; }
}