// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "NumeroOrcamento", "Data", "CodCentroCusto", "CodCargo", "CodFuncionario")]
public partial class MvtRhOrcamentoSalarial
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("numeroOrcamento")]
    public int NumeroOrcamento { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Key]
    [Column("codCargo")]
    [StringLength(24)]
    [Unicode(false)]
    public string CodCargo { get; set; }

    [Key]
    [Column("codFuncionario")]
    public int CodFuncionario { get; set; }

    [Column("qtdeFuncionarios")]
    public int QtdeFuncionarios { get; set; }

    [Column("salarioMedio")]
    public double? SalarioMedio { get; set; }

    [Column("justificativa")]
    [StringLength(250)]
    [Unicode(false)]
    public string Justificativa { get; set; }
}