// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodRecipiente")]
public partial class MvtStatsDashRecipiente
{
    [Column("altura")]
    public int? Altura { get; set; }

    [Key]
    [Column("codRecipiente")]
    public int CodRecipiente { get; set; }

    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }
}