// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodRecipiente", "CodPosicao")]
public partial class MvtStatsDashRecipientePosicao
{
    [Key]
    [Column("codPosicao")]
    public int CodPosicao { get; set; }

    [Key]
    [Column("codRecipiente")]
    public int CodRecipiente { get; set; }

    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Column("largura")]
    public int Largura { get; set; }

    [Column("titulo")]
    [StringLength(100)]
    [Unicode(false)]
    public string Titulo { get; set; }
}