// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtStatsPermissaoDadosCfg
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Required]
    [Column("descricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Required]
    [Column("nomeCampoCodigo")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeCampoCodigo { get; set; }

    [Required]
    [Column("nomeCampoUsuario")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeCampoUsuario { get; set; }

    [Required]
    [Column("nomeTabela")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeTabela { get; set; }

    [Required]
    [Column("nomeColuna")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeColuna { get; set; }
}