// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodObjeto", "CodFiltro")]
public partial class MvtStatsDashObjetoFiltro
{
    [Column("codColuna")]
    [StringLength(50)]
    [Unicode(false)]
    public string CodColuna { get; set; }

    [Key]
    [Column("codFiltro")]
    public int CodFiltro { get; set; }

    [Key]
    [Column("codObjeto")]
    public int CodObjeto { get; set; }

    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Required]
    [Column("tipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("tipoOperacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoOperacao { get; set; }

    [Required]
    [Column("valor")]
    [StringLength(500)]
    [Unicode(false)]
    public string Valor { get; set; }
}