// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtStatsDashVisao
{
    [Column("codModelo")]
    public int? CodModelo { get; set; }

    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Column("imagem")]
    [Unicode(false)]
    public string Imagem { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Required]
    [Column("usuarioCadastro")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioCadastro { get; set; }

    [Column("grupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string Grupo { get; set; }

    [Column("modoEscuro")]
    public int? ModoEscuro { get; set; }
}