// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodObjeto", "CodItem")]
public partial class MvtStatsDashObjetoItem
{
    [Column("codColuna")]
    [StringLength(50)]
    [Unicode(false)]
    public string CodColuna { get; set; }

    [Key]
    [Column("codItem")]
    public int CodItem { get; set; }

    [Key]
    [Column("codObjeto")]
    public int CodObjeto { get; set; }

    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Column("colunaSql")]
    [StringLength(500)]
    [Unicode(false)]
    public string ColunaSql { get; set; }

    [Column("corFundo")]
    [StringLength(50)]
    [Unicode(false)]
    public string CorFundo { get; set; }

    [Required]
    [Column("descricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("formatoExibicao")]
    [StringLength(100)]
    [Unicode(false)]
    public string FormatoExibicao { get; set; }

    [Column("ordemExibicao")]
    public int OrdemExibicao { get; set; }

    [Column("seqOrdenacao")]
    public int? SeqOrdenacao { get; set; }

    [Required]
    [Column("tipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Required]
    [Column("tipoColuna")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoColuna { get; set; }

    [Column("tipoFormato")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoFormato { get; set; }

    [Column("tipoOrdenacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoOrdenacao { get; set; }

    [Column("tipoPeriodoExibicao")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoPeriodoExibicao { get; set; }

    [Column("tipoPeriodoFiltro")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoPeriodoFiltro { get; set; }

    [Column("tipoPeriodoIntervalo")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoPeriodoIntervalo { get; set; }

    [Column("valorPeriodoIntervaloAte")]
    public int? ValorPeriodoIntervaloAte { get; set; }

    [Column("valorPeriodoIntervaloDe")]
    public int? ValorPeriodoIntervaloDe { get; set; }

    [Column("variavel")]
    [StringLength(50)]
    [Unicode(false)]
    public string Variavel { get; set; }

    [Column("visivel")]
    public int Visivel { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TipoObjeto { get; set; }

    [Column("corFundoAleatoria")]
    public int? CorFundoAleatoria { get; set; }

    [Column("valorPeriodoFixoDe", TypeName = "date")]
    public DateTime? ValorPeriodoFixoDe { get; set; }

    [Column("valorPeriodoFixoAte", TypeName = "date")]
    public DateTime? ValorPeriodoFixoAte { get; set; }

    [Column("codColunaData")]
    [StringLength(50)]
    [Unicode(false)]
    public string CodColunaData { get; set; }
}