// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodObjeto")]
public partial class MvtStatsDashObjeto
{
    [Key]
    [Column("codObjeto")]
    public int CodObjeto { get; set; }

    [Column("codPosicao")]
    public int? CodPosicao { get; set; }

    [Column("codRecipiente")]
    public int? CodRecipiente { get; set; }

    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Column("limiteRegistros")]
    public int? LimiteRegistros { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(100)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("propriedades")]
    [Unicode(false)]
    public string Propriedades { get; set; }

    [Required]
    [Column("tipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("transporPrimeiraColuna")]
    public int? TransporPrimeiraColuna { get; set; }

    [Column("titulo")]
    [StringLength(100)]
    [Unicode(false)]
    public string Titulo { get; set; }

    [Column("tamanhoX")]
    public int? TamanhoX { get; set; }

    [Column("tamanhoY")]
    public int? TamanhoY { get; set; }

    [Column("posicaoX")]
    public int? PosicaoX { get; set; }

    [Column("posicaoY")]
    public int? PosicaoY { get; set; }
}