// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodObjeto", "CodItem", "CodTipo")]
public partial class MvtStatsDashObjetoItemOrigem
{
    [Key]
    [Column("codItem")]
    public int CodItem { get; set; }

    [Key]
    [Column("codObjeto")]
    public int CodObjeto { get; set; }

    [Key]
    [Column("codTipo")]
    public int CodTipo { get; set; }

    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }
}