// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodVisao", "CodGrupo")]
public partial class MvtStatsDashPermissaoGrupo
{
    [Key]
    [Column("codGrupo")]
    public int CodGrupo { get; set; }

    [Key]
    [Column("codVisao")]
    public int CodVisao { get; set; }

    [Column("permissaoEdicao")]
    public int? PermissaoEdicao { get; set; }
}