// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Programa", "Usuario", "CodCentroCusto", "CodEmpresa")]
public partial class MvtTempPermissaoCentroCusto
{
    [Key]
    [Column("programa")]
    [StringLength(150)]
    public string Programa { get; set; }

    [Key]
    [Column("usuario")]
    [StringLength(150)]
    public string Usuario { get; set; }

    [Key]
    [Column("codCentroCusto")]
    public int CodCentroCusto { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("liberacaoEspecial")]
    public int? LiberacaoEspecial { get; set; }
}