// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Usuario", "Nome", "Valor")]
public partial class MvtVendasEstruturaPermissaoUsuarioDados
{
    [Column("descricao")]
    [StringLength(500)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Key]
    [Column("nome")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Key]
    [Column("usuario")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Key]
    [Column("valor")]
    [StringLength(50)]
    [Unicode(false)]
    public string Valor { get; set; }
}