// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Tipo", "Destino")]
public partial class MvtVendasTipoEstatisticaImportacao
{
    [Key]
    [Column("tipo")]
    public int Tipo { get; set; }

    [Key]
    [Column("destino")]
    [StringLength(20)]
    [Unicode(false)]
    public string Destino { get; set; }

    [Column("dataInicio", TypeName = "date")]
    public DateTime? DataInicio { get; set; }

    [Column("horaInicio")]
    public TimeSpan? HoraInicio { get; set; }

    [Column("dataFim", TypeName = "date")]
    public DateTime? DataFim { get; set; }

    [Column("horaFim")]
    public TimeSpan? HoraFim { get; set; }

    [Column("situacao")]
    public int? Situacao { get; set; }

    [Column("somenteDiasUteis")]
    public int? SomenteDiasUteis { get; set; }

    [Column("repeticaoTipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string RepeticaoTipo { get; set; }

    [Column("repeticaoValor")]
    public int? RepeticaoValor { get; set; }

    [Column("repetir")]
    public int? Repetir { get; set; }

    [Column("dataImportacao", TypeName = "date")]
    public DateTime? DataImportacao { get; set; }

    [Column("horaImportacao")]
    public TimeSpan? HoraImportacao { get; set; }
}