// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasEstatisticaModulosApp
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Column("descricao")]
    [StringLength(500)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("icone")]
    [Unicode(false)]
    public string Icone { get; set; }

    [Column("tema")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tema { get; set; }
}