// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Tipo", "Destino", "Empresa")]
public partial class MvtVendasTipoEstatisticaImportacaoEmpresas
{
    [Key]
    [Column("tipo")]
    [StringLength(10)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Key]
    [Column("destino")]
    [StringLength(20)]
    [Unicode(false)]
    public string Destino { get; set; }

    [Key]
    [Column("empresa")]
    public int Empresa { get; set; }
}