// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodEstrutura", "CodTipoAgrupamento")]
public partial class MvtVendasEstruturaConsultaTipoAgrupamento
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codEstrutura")]
    public int CodEstrutura { get; set; }

    [Key]
    [Column("codTipoAgrupamento")]
    public int CodTipoAgrupamento { get; set; }
}