// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEstatisticaTipo", "Cfop")]
[Table("MvtVendasTipoEstatisticaCFOP")]
public partial class MvtVendasTipoEstatisticaCfop
{
    [Key]
    [Column("CFOP")]
    public int Cfop { get; set; }

    [Key]
    [Column("codEstatisticaTipo")]
    public int CodEstatisticaTipo { get; set; }

    [Column("geraEstatistica")]
    public int? GeraEstatistica { get; set; }
}