// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodEstrutura", "Sequencia")]
public partial class MvtVendasEstruturaConsultaColuna
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codEstrutura")]
    public int CodEstrutura { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Column("nomeCampo")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeCampo { get; set; }

    [Column("nomeVisualizacao")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeVisualizacao { get; set; }

    [Column("nomeExibicao")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeExibicao { get; set; }

    [Column("nomeColuna")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeColuna { get; set; }
}