// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodPlanoMeta", "Data", "CodAtendente", "CodCliente", "CodFamilia", "CodRepresentante", "Mercado", "NomeGrupo", "NomeSubGrupo", "NomeCanal", "CodProduto")]
public partial class MvtVendasEstruturaMetaCliente
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codPlanoMeta")]
    public int CodPlanoMeta { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("codAtendente")]
    public int CodAtendente { get; set; }

    [Key]
    [Column("codCliente")]
    public int CodCliente { get; set; }

    [Key]
    [Column("codFamilia")]
    public int CodFamilia { get; set; }

    [Key]
    [Column("codRepresentante")]
    public int CodRepresentante { get; set; }

    [Key]
    [Column("mercado")]
    public int Mercado { get; set; }

    [Key]
    [Column("nomeGrupo")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeGrupo { get; set; }

    [Key]
    [Column("nomeSubGrupo")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeSubGrupo { get; set; }

    [Key]
    [Column("nomeCanal")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeCanal { get; set; }

    [Key]
    [Column("codProduto")]
    [StringLength(200)]
    [Unicode(false)]
    public string CodProduto { get; set; }

    [Column("cep")]
    [StringLength(200)]
    [Unicode(false)]
    public string Cep { get; set; }

    [Column("ano")]
    public int? Ano { get; set; }

    [Column("cidade")]
    [StringLength(200)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [Column("codCNPJCliente")]
    [StringLength(200)]
    [Unicode(false)]
    public string CodCnpjcliente { get; set; }

    [Column("codClienteAgrupador")]
    public int? CodClienteAgrupador { get; set; }

    [Column("codGerente")]
    public int? CodGerente { get; set; }

    [Column("codRepresentanteCliCalc")]
    public int? CodRepresentanteCliCalc { get; set; }

    [Column("codRepreentanteCongelado")]
    public int? CodRepreentanteCongelado { get; set; }

    [Column("codRepresentanteMetaCalc")]
    public int? CodRepresentanteMetaCalc { get; set; }

    [Column("codSupervisor")]
    public int? CodSupervisor { get; set; }

    [Column("codVendedor")]
    public int? CodVendedor { get; set; }

    [Column("dataEmissao", TypeName = "date")]
    public DateTime? DataEmissao { get; set; }

    [Column("divisao")]
    [StringLength(200)]
    [Unicode(false)]
    public string Divisao { get; set; }

    [Column("estado")]
    [StringLength(200)]
    [Unicode(false)]
    public string Estado { get; set; }

    [Column("marca")]
    [StringLength(200)]
    [Unicode(false)]
    public string Marca { get; set; }

    [Column("mes")]
    [StringLength(200)]
    [Unicode(false)]
    public string Mes { get; set; }

    [Column("nomeCliente")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeCliente { get; set; }

    [Column("nomeClienteAgrupador")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeClienteAgrupador { get; set; }

    [Column("nomeFamilia")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeFamilia { get; set; }

    [Column("nomeFamiliaCalc")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeFamiliaCalc { get; set; }

    [Column("nomeGerente")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeGerente { get; set; }

    [Column("nomeMercado")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeMercado { get; set; }

    [Column("nomeProduto")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeProduto { get; set; }

    [Column("nomeRepresentante")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeRepresentante { get; set; }

    [Column("nomeRepresentanteCliCalc")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeRepresentanteCliCalc { get; set; }

    [Column("nomeRepresentanteMetaCalc")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeRepresentanteMetaCalc { get; set; }

    [Column("nomeSupervisor")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeSupervisor { get; set; }

    [Column("nomeVendedor")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeVendedor { get; set; }

    [Column("percent")]
    public double? Percent { get; set; }

    [Column("percentCalc")]
    public double? PercentCalc { get; set; }

    [Column("precoMedio")]
    public double? PrecoMedio { get; set; }

    [Column("qtde")]
    [StringLength(200)]
    [Unicode(false)]
    public string Qtde { get; set; }

    [Column("qtdeMeta")]
    public double? QtdeMeta { get; set; }

    [Column("qtdeMetaCli")]
    public double? QtdeMetaCli { get; set; }

    [Column("regiao")]
    [StringLength(200)]
    [Unicode(false)]
    public string Regiao { get; set; }

    [Column("usuarioRegiao")]
    [StringLength(200)]
    [Unicode(false)]
    public string UsuarioRegiao { get; set; }

    [Column("valorMeta")]
    public double? ValorMeta { get; set; }

    [Column("valorMetaCli")]
    public double? ValorMetaCli { get; set; }

    [Column("metaMargemDepartamento")]
    public double? MetaMargemDepartamento { get; set; }

    [Column("metaDepartamento")]
    public double? MetaDepartamento { get; set; }

    [Column("metaPositivacao")]
    public double? MetaPositivacao { get; set; }

    [Column("metaQtdeSubCat")]
    public double? MetaQtdeSubCat { get; set; }

    [Column("metaCashMargin")]
    public double? MetaCashMargin { get; set; }

    [Column("metaMargemMercado")]
    public double? MetaMargemMercado { get; set; }

    [Column("metaLucroBruto")]
    public double? MetaLucroBruto { get; set; }

    [Column("metaROL")]
    public double? MetaRol { get; set; }

    [Column("metaLucroBrutoDepartamento")]
    public double? MetaLucroBrutoDepartamento { get; set; }

    [Column("metaROLDepartamento")]
    public double? MetaRoldepartamento { get; set; }

    [Column("metaPercDesc")]
    public double? MetaPercDesc { get; set; }

    [Column("nomeGrupoCalc")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeGrupoCalc { get; set; }

    [Column("nomeSubGrupoCalc")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeSubGrupoCalc { get; set; }

    [Column("valorAcumuladoMetaCli")]
    public double? ValorAcumuladoMetaCli { get; set; }
}