// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Usuario", "NomeConsulta", "DataHora")]
public partial class MvtVendasEstruturaConsultaSalvaCapa
{
    [Key]
    [Column("usuario")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usuario { get; set; }

    [Key]
    [Column("nomeConsulta")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeConsulta { get; set; }

    [Key]
    [Column("dataHora", TypeName = "datetime")]
    public DateTime DataHora { get; set; }

    [Column("corFundo")]
    [StringLength(200)]
    [Unicode(false)]
    public string CorFundo { get; set; }

    [Column("imagem")]
    [StringLength(200)]
    [Unicode(false)]
    public string Imagem { get; set; }

    [Column("nomePai")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomePai { get; set; }

    [Column("qtdeUso")]
    public int? QtdeUso { get; set; }

    [Column("imagemBase64")]
    [Unicode(false)]
    public string ImagemBase64 { get; set; }
}