// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasEstruturaCorPercent
{
    [Column("bom")]
    public double? Bom { get; set; }

    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("otimo")]
    public double? Otimo { get; set; }

    [Column("regular")]
    public double? Regular { get; set; }

    [Column("ruim")]
    public double? Ruim { get; set; }

    [Column("corOtimo")]
    [StringLength(10)]
    [Unicode(false)]
    public string CorOtimo { get; set; }

    [Column("corBom ")]
    [StringLength(10)]
    [Unicode(false)]
    public string CorBom { get; set; }

    [Column("corRegular")]
    [StringLength(10)]
    [Unicode(false)]
    public string CorRegular { get; set; }

    [Column("corRuim")]
    [StringLength(10)]
    [Unicode(false)]
    public string CorRuim { get; set; }
}