// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Codigo", "CodigoSimultaneo")]
public partial class MvtVendasTipoEstatisticaAgrupamentoSimultaneo
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Key]
    [Column("codigoSimultaneo")]
    public int CodigoSimultaneo { get; set; }
}