// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasEstruturaConsultaValorOpcao
{
    [Column("descricao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("formato")]
    [StringLength(500)]
    [Unicode(false)]
    public string Formato { get; set; }

    [Column("liberadaApp")]
    public int? LiberadaApp { get; set; }

    [Key]
    [Column("nome")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("nomeGroup")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeGroup { get; set; }

    [Column("nomeHeader")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeHeader { get; set; }

    [Column("nomeOrder")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeOrder { get; set; }

    [Column("nomeSelect")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelect { get; set; }

    [Column("nomeSelectCarteira")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelectCarteira { get; set; }

    [Column("nomeSelectCidade")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelectCidade { get; set; }

    [Column("nomeSelectCliente")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelectCliente { get; set; }

    [Column("nomeSelectEstoque")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelectEstoque { get; set; }

    [Column("nomeSelectMeta")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelectMeta { get; set; }

    [Column("nomeSelectPrevisaoVenda")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelectPrevisaoVenda { get; set; }

    [Column("nomeSelectTotal")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelectTotal { get; set; }

    [Column("nomeSelectVerba")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelectVerba { get; set; }

    [Column("ordenacao")]
    public int? Ordenacao { get; set; }

    [Column("totalSQL")]
    public int? TotalSql { get; set; }

    [Column("atingimento")]
    public int? Atingimento { get; set; }
}