// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasLockAtualizacaoEstatistica
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Column("dataHoraFim", TypeName = "datetime")]
    public DateTime? DataHoraFim { get; set; }

    [Column("dataHoraInicio", TypeName = "datetime")]
    public DateTime? DataHoraInicio { get; set; }

    [Column("emAtualizacao")]
    public int? EmAtualizacao { get; set; }
}