// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasTipoEstatistica
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Column("tipo")]
    [StringLength(20)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("nome")]
    [StringLength(500)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("tooltip")]
    [StringLength(500)]
    [Unicode(false)]
    public string Tooltip { get; set; }

    [Column("apenasParaAbrirBaseAntiga")]
    public int? ApenasParaAbrirBaseAntiga { get; set; }

    [Column("ordem")]
    public int? Ordem { get; set; }

    [Column("liberadoParaConsulta")]
    public int? LiberadoParaConsulta { get; set; }

    [Column("sqlBase")]
    [Unicode(false)]
    public string SqlBase { get; set; }
}