// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Empresa", "Tipo", "DataHoraInicio", "Destino")]
public partial class MvtVendasTipoEstatisticaLogImportacao
{
    [Key]
    public int Empresa { get; set; }

    [Key]
    [Column("tipo")]
    public int Tipo { get; set; }

    [Column("nomeTipo")]
    [StringLength(250)]
    [Unicode(false)]
    public string NomeTipo { get; set; }

    [Key]
    [Column("dataHoraInicio", TypeName = "datetime")]
    public DateTime DataHoraInicio { get; set; }

    [Column("dataHoraFim", TypeName = "datetime")]
    public DateTime? DataHoraFim { get; set; }

    [Column("textoLog", TypeName = "text")]
    public string TextoLog { get; set; }

    [Key]
    [Column("destino")]
    [StringLength(50)]
    [Unicode(false)]
    public string Destino { get; set; }
}