// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("Tipo", "Campo", "CodTipoAgrSimultaneo")]
public partial class MvtVendasTipoEstatisticaAgrupamentoCampo
{
    [Key]
    [Column("tipo")]
    public int Tipo { get; set; }

    [Key]
    [Column("campo")]
    [StringLength(4000)]
    [Unicode(false)]
    public string Campo { get; set; }

    [Key]
    [Column("codTipoAgrSimultaneo")]
    public int CodTipoAgrSimultaneo { get; set; }

    [Column("restritoATodos")]
    public int? RestritoAtodos { get; set; }

    [Column("tipoCampo")]
    public int? TipoCampo { get; set; }
}