// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasEstruturaConsultaColunaOpcao
{
    [Column("descricao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("liberadaApp")]
    public int? LiberadaApp { get; set; }

    [Key]
    [Column("nome")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("nomeAgrupamento")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeAgrupamento { get; set; }

    [Column("nomeGroup")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeGroup { get; set; }

    [Column("nomeHeader")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeHeader { get; set; }

    [Column("nomeSelect")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelect { get; set; }

    [Column("nomeSelectExibicao")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeSelectExibicao { get; set; }

    [Column("filtroData")]
    public int? FiltroData { get; set; }

    [Column("nomeOrder")]
    [StringLength(2000)]
    [Unicode(false)]
    public string NomeOrder { get; set; }

    [Column("formato")]
    [StringLength(500)]
    [Unicode(false)]
    public string Formato { get; set; }

    [Column("geoTipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string GeoTipo { get; set; }

    [Column("geoColunaLatitude")]
    [StringLength(50)]
    [Unicode(false)]
    public string GeoColunaLatitude { get; set; }

    [Column("geoColunaLongitude")]
    [StringLength(50)]
    [Unicode(false)]
    public string GeoColunaLongitude { get; set; }

    [Column("geoPerimetroTipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string GeoPerimetroTipo { get; set; }

    [Column("geoColunaCodigo")]
    [StringLength(50)]
    [Unicode(false)]
    public string GeoColunaCodigo { get; set; }
}