// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasTipoEstatisticaAgrupamento
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Column("tipo")]
    [StringLength(20)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("tipoVisual")]
    [StringLength(20)]
    [Unicode(false)]
    public string TipoVisual { get; set; }

    [Column("cabecalhoColuna")]
    [StringLength(20)]
    [Unicode(false)]
    public string CabecalhoColuna { get; set; }

    [Column("confrontaMeta")]
    public int? ConfrontaMeta { get; set; }

    [Column("nome")]
    [StringLength(500)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("colunaExibicaoPadrao")]
    [StringLength(500)]
    [Unicode(false)]
    public string ColunaExibicaoPadrao { get; set; }

    [Column("filtros")]
    [StringLength(4000)]
    [Unicode(false)]
    public string Filtros { get; set; }

    [Column("ordem")]
    public int? Ordem { get; set; }

    [Column("nomeTipo")]
    [StringLength(500)]
    [Unicode(false)]
    public string NomeTipo { get; set; }
}