// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Tipo")]
public partial class MvtVendasEstruturaImportacaoCfg
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("tipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("descricao")]
    [StringLength(2000)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Required]
    [StringLength(3000)]
    [Unicode(false)]
    public string ErpTable { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string ErpTableUnionAll { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string ErpTableUnionAll1 { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string ErpWhereClause { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string ErpWhereClauseUnionAll { get; set; }

    [StringLength(2000)]
    [Unicode(false)]
    public string ErpWhereClauseUnionAll1 { get; set; }

    [Column("FILTRAREMPRESANODELETE")]
    public int? Filtrarempresanodelete { get; set; }

    [Column("IGNORAREMPRESANODELETE")]
    public int? Ignorarempresanodelete { get; set; }

    [Column("statsTable")]
    [StringLength(2000)]
    [Unicode(false)]
    public string StatsTable { get; set; }

    [Column("stringConexao")]
    [StringLength(2000)]
    [Unicode(false)]
    public string StringConexao { get; set; }

    [Column("incluirCamposManualmente")]
    public int? IncluirCamposManualmente { get; set; }

    [Column("dataHoraUltimaImportacao", TypeName = "datetime")]
    public DateTime? DataHoraUltimaImportacao { get; set; }

    [Column("executarApos")]
    [StringLength(2000)]
    [Unicode(false)]
    public string ExecutarApos { get; set; }
}