// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasEstruturaPermissaoDados
{
    [Key]
    [Column("nome")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("calculada")]
    public int? Calculada { get; set; }

    [Column("sqlColuna")]
    [StringLength(500)]
    [Unicode(false)]
    public string SqlColuna { get; set; }

    [Column("sqlConsulta")]
    [StringLength(500)]
    [Unicode(false)]
    public string SqlConsulta { get; set; }
}