// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasEstatisticaCadastro
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Column("nome")]
    [StringLength(500)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("tabela")]
    [StringLength(500)]
    [Unicode(false)]
    public string Tabela { get; set; }
}