// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasCfgFiltroAdicional
{
    [Column("ativo")]
    public int? Ativo { get; set; }

    [Key]
    [Column("codFiltro")]
    public int CodFiltro { get; set; }

    [Column("descricao")]
    [StringLength(100)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("ordem")]
    public int? Ordem { get; set; }

    [Column("sqlCampo")]
    [StringLength(500)]
    [Unicode(false)]
    public string SqlCampo { get; set; }

    [Column("sqlPesquisa")]
    [StringLength(500)]
    [Unicode(false)]
    public string SqlPesquisa { get; set; }

    [Column("sqlValidacao")]
    [StringLength(500)]
    [Unicode(false)]
    public string SqlValidacao { get; set; }
}