// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodEstrutura", "Sequencia")]
public partial class MvtVendasEstruturaConsultaValor
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codEstrutura")]
    public int CodEstrutura { get; set; }

    [Key]
    [Column("sequencia")]
    public int Sequencia { get; set; }

    [Column("corFundo")]
    public int? CorFundo { get; set; }

    [Column("corTexto")]
    public int? CorTexto { get; set; }

    [Column("fonteNegrito")]
    public int? FonteNegrito { get; set; }

    [Column("nomeCampo")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeCampo { get; set; }

    [Column("nomeVisualizacao")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeVisualizacao { get; set; }

    [Column("nomeColuna")]
    [StringLength(50)]
    [Unicode(false)]
    public string NomeColuna { get; set; }

    [Column("atingimento")]
    public int? Atingimento { get; set; }
}