// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Tipo", "GeraEstatisticaFin", "Data", "Documento", "CodProduto", "CodMotivo")]
public partial class MvtVendasEstruturaFaturamento
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("tipo")]
    [StringLength(200)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Key]
    [Column("geraEstatisticaFin")]
    public int GeraEstatisticaFin { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("documento")]
    [StringLength(200)]
    [Unicode(false)]
    public string Documento { get; set; }

    [Key]
    [Column("codProduto")]
    [StringLength(200)]
    [Unicode(false)]
    public string CodProduto { get; set; }

    [Key]
    [Column("codMotivo")]
    [StringLength(200)]
    [Unicode(false)]
    public string CodMotivo { get; set; }

    [Column("ano")]
    public int? Ano { get; set; }

    [Column("bimestre")]
    [StringLength(200)]
    [Unicode(false)]
    public string Bimestre { get; set; }

    [Column("cidade")]
    [StringLength(200)]
    [Unicode(false)]
    public string Cidade { get; set; }

    [Column("codCliente")]
    public int? CodCliente { get; set; }

    [Column("codRepresentante")]
    public int? CodRepresentante { get; set; }

    [Column("dataEmissao", TypeName = "date")]
    public DateTime? DataEmissao { get; set; }

    [Column("estado")]
    [StringLength(200)]
    [Unicode(false)]
    public string Estado { get; set; }

    [Column("fantasiaCliente")]
    [StringLength(200)]
    [Unicode(false)]
    public string FantasiaCliente { get; set; }

    [Column("mercado")]
    [StringLength(200)]
    [Unicode(false)]
    public string Mercado { get; set; }

    [Column("mercadoNome")]
    [StringLength(200)]
    [Unicode(false)]
    public string MercadoNome { get; set; }

    [Column("mes")]
    [StringLength(200)]
    [Unicode(false)]
    public string Mes { get; set; }

    [Column("nomeCliente")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeCliente { get; set; }

    [Column("nomeEmpresa")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeEmpresa { get; set; }

    [Column("nomeMotivo")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeMotivo { get; set; }

    [Column("nomeProduto")]
    [StringLength(300)]
    [Unicode(false)]
    public string NomeProduto { get; set; }

    [Column("nomeRepresentante")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeRepresentante { get; set; }

    [Column("qtde")]
    public double? Qtde { get; set; }

    [Column("regiao")]
    [StringLength(200)]
    [Unicode(false)]
    public string Regiao { get; set; }

    [Column("semana")]
    public int? Semana { get; set; }

    [Column("semestre")]
    [StringLength(200)]
    [Unicode(false)]
    public string Semestre { get; set; }

    [Column("trimestre")]
    [StringLength(200)]
    [Unicode(false)]
    public string Trimestre { get; set; }

    [Column("valor")]
    public double? Valor { get; set; }

    [Column("valorFaturado")]
    public double? ValorFaturado { get; set; }

    [Column("unidadeMedida")]
    [StringLength(200)]
    [Unicode(false)]
    public string UnidadeMedida { get; set; }

    [Column("operacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string Operacao { get; set; }

    [Column("quantidadeDevolvidaUn")]
    public double? QuantidadeDevolvidaUn { get; set; }

    [Column("valorTabela")]
    public double? ValorTabela { get; set; }

    [Column("valorPrecoMedioUnitarioVendas")]
    public double? ValorPrecoMedioUnitarioVendas { get; set; }

    [Column("valorDevolucao")]
    public double? ValorDevolucao { get; set; }

    [Column("codGrupo")]
    public int? CodGrupo { get; set; }

    [Column("nomeGrupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeGrupo { get; set; }

    [Column("codSubGrupo")]
    public int? CodSubGrupo { get; set; }

    [Column("nomeSubGrupo")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeSubGrupo { get; set; }

    [Column("codLinha")]
    public int? CodLinha { get; set; }

    [Column("nomeLinha")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeLinha { get; set; }

    [Column("codPedido")]
    public int? CodPedido { get; set; }

    [Column("situacaoDigitacao")]
    [StringLength(2)]
    [Unicode(false)]
    public string SituacaoDigitacao { get; set; }

    [Column("situacaoEstoque")]
    [StringLength(2)]
    [Unicode(false)]
    public string SituacaoEstoque { get; set; }

    [Column("cnpj")]
    [StringLength(20)]
    [Unicode(false)]
    public string Cnpj { get; set; }

    [Column("codRamoAtividade")]
    public int? CodRamoAtividade { get; set; }

    [Column("nomeRamoAtividade")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeRamoAtividade { get; set; }

    [Column("ranking")]
    [StringLength(10)]
    [Unicode(false)]
    public string Ranking { get; set; }

    [Column("codTipoNota")]
    [StringLength(2)]
    [Unicode(false)]
    public string CodTipoNota { get; set; }

    [Column("codPais")]
    [StringLength(5)]
    [Unicode(false)]
    public string CodPais { get; set; }

    [Column("nomePais")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomePais { get; set; }

    [Column("codRegiaoCobertura")]
    [StringLength(8)]
    [Unicode(false)]
    public string CodRegiaoCobertura { get; set; }

    [Column("nomeRegiaoCobertura")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeRegiaoCobertura { get; set; }

    [Column("codCondPagamento")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodCondPagamento { get; set; }

    [Column("nomeCondPagamento")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeCondPagamento { get; set; }

    [Column("cfop")]
    [StringLength(5)]
    [Unicode(false)]
    public string Cfop { get; set; }

    [Column("peso")]
    public double? Peso { get; set; }

    [Column("vlrIcms")]
    public double? VlrIcms { get; set; }

    [Column("vlrIpi")]
    public double? VlrIpi { get; set; }

    [Column("vlrPis")]
    public double? VlrPis { get; set; }

    [Column("vlrCofins")]
    public double? VlrCofins { get; set; }

    [Column("vlrFrete")]
    public double? VlrFrete { get; set; }

    [Column("vlrComiss")]
    public double? VlrComiss { get; set; }

    [Column("vlrSeguro")]
    public double? VlrSeguro { get; set; }

    [Column("vlrCsll")]
    public double? VlrCsll { get; set; }

    [Column("vlrCustoProdutoInsumo")]
    public double? VlrCustoProdutoInsumo { get; set; }

    [Column("codModelo")]
    public int? CodModelo { get; set; }

    [Column("sequencia")]
    public int? Sequencia { get; set; }

    [Column("numeroOrcamento")]
    public int? NumeroOrcamento { get; set; }

    [Column("codConta")]
    public int? CodConta { get; set; }

    [Column("nomeModelo")]
    [StringLength(150)]
    [Unicode(false)]
    public string NomeModelo { get; set; }

    [Column("nomeConta")]
    [StringLength(250)]
    [Unicode(false)]
    public string NomeConta { get; set; }

    [Column("orcadoRealizado")]
    [StringLength(50)]
    [Unicode(false)]
    public string OrcadoRealizado { get; set; }

    [Column("dataProjecao", TypeName = "date")]
    public DateTime? DataProjecao { get; set; }

    [Column("vlrFreteM3")]
    public double? VlrFreteM3 { get; set; }

    [Column("vlrFreteTxEntrada")]
    public double? VlrFreteTxEntrada { get; set; }

    [Column("vlrFreteAdicional")]
    public double? VlrFreteAdicional { get; set; }

    [Column("vlrFreteFechamento")]
    public double? VlrFreteFechamento { get; set; }

    [Column("vlrTaxaDescarga")]
    public double? VlrTaxaDescarga { get; set; }

    [Column("codTransportador")]
    public int? CodTransportador { get; set; }

    [StringLength(250)]
    [Unicode(false)]
    public string NomeTransportador { get; set; }

    [Column("codRepresentanteAtual")]
    public int? CodRepresentanteAtual { get; set; }

    [Column("nomeRepresentanteAtual")]
    [StringLength(200)]
    [Unicode(false)]
    public string NomeRepresentanteAtual { get; set; }

    [Column("codCidade")]
    public int? CodCidade { get; set; }

    [Column("microrregiao")]
    [StringLength(200)]
    [Unicode(false)]
    public string Microrregiao { get; set; }

    [Column("mesorregiao")]
    [StringLength(200)]
    [Unicode(false)]
    public string Mesorregiao { get; set; }

    [Column("codMesorregiao")]
    public int? CodMesorregiao { get; set; }

    [Column("codMicrorregiao")]
    public int? CodMicrorregiao { get; set; }

    [Column("vlrCustoTotal")]
    public double? VlrCustoTotal { get; set; }

    [Column("codIbgeCidade")]
    public int? CodIbgeCidade { get; set; }
}