// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasCfgEmailDinamico
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Required]
    [Column("descricao")]
    [StringLength(250)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Required]
    [Column("emailDestino")]
    [StringLength(500)]
    [Unicode(false)]
    public string EmailDestino { get; set; }

    [Required]
    [Column("tituloEmail")]
    [StringLength(250)]
    [Unicode(false)]
    public string TituloEmail { get; set; }

    [Required]
    [Column("prioridadeEmail")]
    [StringLength(50)]
    [Unicode(false)]
    public string PrioridadeEmail { get; set; }

    [Column("corpoEmail")]
    [Unicode(false)]
    public string CorpoEmail { get; set; }

    [Required]
    [Column("consultaSql")]
    [Unicode(false)]
    public string ConsultaSql { get; set; }

    [Required]
    [Column("periodoConsulta")]
    [StringLength(50)]
    [Unicode(false)]
    public string PeriodoConsulta { get; set; }

    [Required]
    [Column("periodoIntervalo")]
    [StringLength(50)]
    [Unicode(false)]
    public string PeriodoIntervalo { get; set; }

    [Column("periodoIntervaloDe")]
    public int PeriodoIntervaloDe { get; set; }

    [Column("periodoIntervaloAte")]
    public int PeriodoIntervaloAte { get; set; }

    [Column("dataHoraInicio", TypeName = "datetime")]
    public DateTime DataHoraInicio { get; set; }

    [Column("dataHoraTermino", TypeName = "datetime")]
    public DateTime? DataHoraTermino { get; set; }

    [Column("erroUltimoEnvio")]
    [Unicode(false)]
    public string ErroUltimoEnvio { get; set; }

    [Column("dataHoraProximoEnvio", TypeName = "datetime")]
    public DateTime DataHoraProximoEnvio { get; set; }

    [Column("diasSemanaEnvio")]
    public int DiasSemanaEnvio { get; set; }

    [Column("enviaSomenteDiasUteis")]
    public int EnviaSomenteDiasUteis { get; set; }

    [Column("enviaCorpoEmail")]
    public int EnviaCorpoEmail { get; set; }

    [Column("enviaAnexoEmail")]
    public int EnviaAnexoEmail { get; set; }

    [Column("ativo")]
    public int Ativo { get; set; }

    [Required]
    [Column("usuarioCadastro")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioCadastro { get; set; }

    [Column("dataHoraCadastro", TypeName = "datetime")]
    public DateTime DataHoraCadastro { get; set; }

    [Required]
    [Column("usuarioAlteracao")]
    [StringLength(50)]
    [Unicode(false)]
    public string UsuarioAlteracao { get; set; }

    [Column("dataHoraUltimaAlteracao", TypeName = "datetime")]
    public DateTime DataHoraUltimaAlteracao { get; set; }

    [Column("dataHoraUltimoEnvio", TypeName = "datetime")]
    public DateTime? DataHoraUltimoEnvio { get; set; }
}