// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "Estabelecimento", "Data", "Operacao", "CodCliente", "CodRepresentante", "CodProduto")]
public partial class MvtVendasHistoricoMensal
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("estabelecimento")]
    public int Estabelecimento { get; set; }

    [Key]
    [Column("data", TypeName = "date")]
    public DateTime Data { get; set; }

    [Key]
    [Column("operacao")]
    [StringLength(30)]
    [Unicode(false)]
    public string Operacao { get; set; }

    [Key]
    [Column("codCliente")]
    public int CodCliente { get; set; }

    [Key]
    [Column("codRepresentante")]
    public int CodRepresentante { get; set; }

    [Key]
    [Column("codProduto")]
    [StringLength(20)]
    [Unicode(false)]
    public string CodProduto { get; set; }

    [Column("cnpjCpf")]
    [StringLength(20)]
    [Unicode(false)]
    public string CnpjCpf { get; set; }

    [Column("quantidade")]
    public double? Quantidade { get; set; }

    [Column("valorMedio")]
    public double? ValorMedio { get; set; }

    [Column("valorTotal")]
    public double? ValorTotal { get; set; }

    [Column("referenciaComlProd")]
    [StringLength(30)]
    [Unicode(false)]
    public string ReferenciaComlProd { get; set; }

    [Column("referenciaProduto")]
    [StringLength(30)]
    [Unicode(false)]
    public string ReferenciaProduto { get; set; }

    [Column("unidadeNegocioProd")]
    [StringLength(30)]
    [Unicode(false)]
    public string UnidadeNegocioProd { get; set; }

    [Column("segmentoProduto")]
    [StringLength(30)]
    [Unicode(false)]
    public string SegmentoProduto { get; set; }

    [Column("grupoProduto")]
    [StringLength(30)]
    [Unicode(false)]
    public string GrupoProduto { get; set; }

    [Column("linhaProduto")]
    [StringLength(30)]
    [Unicode(false)]
    public string LinhaProduto { get; set; }

    [Column("canalCliente")]
    [StringLength(30)]
    [Unicode(false)]
    public string CanalCliente { get; set; }

    [Column("regiaoAbCliente")]
    [StringLength(30)]
    [Unicode(false)]
    public string RegiaoAbCliente { get; set; }

    [Column("codAgrupador")]
    public int? CodAgrupador { get; set; }

    [Column("mercado")]
    [StringLength(7)]
    [Unicode(false)]
    public string Mercado { get; set; }

    [Column("macroRegiao")]
    [StringLength(15)]
    [Unicode(false)]
    public string MacroRegiao { get; set; }

    [Column("operacaoIntercompanhia")]
    public int? OperacaoIntercompanhia { get; set; }
}