// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

[PrimaryKey("CodEmpresa", "CodEstrutura")]
public partial class MvtVendasEstruturaConsulta
{
    [Key]
    [Column("codEmpresa")]
    public int CodEmpresa { get; set; }

    [Key]
    [Column("codEstrutura")]
    public int CodEstrutura { get; set; }

    [Column("nomeEstrutura")]
    [StringLength(100)]
    [Unicode(false)]
    public string NomeEstrutura { get; set; }
}