// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace api_orcamento.Models;

public partial class MvtVendasEstatisticaConsultaSalvaApp
{
    [Key]
    [Column("codigo")]
    public int Codigo { get; set; }

    [Column("descricao")]
    [StringLength(5000)]
    [Unicode(false)]
    public string Descricao { get; set; }

    [Column("icone")]
    [Unicode(false)]
    public string Icone { get; set; }

    [Column("limiteRegistros")]
    public int? LimiteRegistros { get; set; }

    [Column("sistema")]
    [StringLength(50)]
    [Unicode(false)]
    public string Sistema { get; set; }

    [Column("sqlBase")]
    [Unicode(false)]
    public string SqlBase { get; set; }

    [Column("tipoApresentacao")]
    [StringLength(50)]
    [Unicode(false)]
    public string TipoApresentacao { get; set; }

    [Column("codModulo")]
    public int? CodModulo { get; set; }

    [Column("ordem")]
    public int? Ordem { get; set; }
}